module.exports = [
  {
    title: "Dracula",
    author: "Bram Stoker",
    authorBio: "Irish author whose 1897 Gothic epistolary masterpiece established Count Dracula and created modern vampire mythology.",
    year: 1897,
    pages: 418,
    audience: "teen",
    coverId: "12216503",
    description: "Young solicitor Jonathan Harker journeys to Transylvania to conclude a London property deal with Count Dracula, uncovering an ancient bloodthirsty predator.",
    curatorNote: "The supreme Gothic vampire classic exploring technological modernity against primordial terror.",
    gutenbergId: "345",
    openLibraryWorkId: "OL21855W",
    subjects: ["Gothic & Horror", "Vampires", "Count Dracula", "Transylvania", "Gothic Suspense"]
  },
  {
    title: "The Jewel of Seven Stars",
    author: "Bram Stoker",
    authorBio: "Irish author whose 1897 Gothic epistolary masterpiece established Count Dracula and created modern vampire mythology.",
    year: 1903,
    pages: 310,
    audience: "teen",
    coverId: "8232190",
    description: "Malcolm Ross aids archaeologist Abel Trelawny in an occult ritual to resurrect Queen Tera, an ancient Egyptian sorceress possessing seven-fingered mummified hands.",
    curatorNote: "The pioneering novel of Egyptian mummy curses that inspired modern cinematic horror.",
    gutenbergId: "3781",
    openLibraryWorkId: "OL21856W",
    subjects: ["Gothic & Horror", "Mummy Curse", "Occult Ritual", "Egyptian Mystery"]
  },
  {
    title: "The Lair of the White Worm",
    author: "Bram Stoker",
    authorBio: "Irish author whose 1897 Gothic epistolary masterpiece established Count Dracula and created modern vampire mythology.",
    year: 1911,
    pages: 260,
    audience: "adult",
    coverId: "8232191",
    description: "Adam Salton arrives in England from Australia, discovering that alluring aristocrat Arabella March is the human incarnation of a giant prehistoric serpent.",
    curatorNote: "Stoker's strange, hallucinatory folklore horror drawing on pagan dragon mythology.",
    gutenbergId: "2444",
    openLibraryWorkId: "OL21857W",
    subjects: ["Gothic & Horror", "Ancient Serpent", "Folk Horror", "English Pagan Lore"]
  },
  {
    title: "Dracula's Guest",
    subtitle: "And Other Weird Stories",
    author: "Bram Stoker",
    authorBio: "Irish author whose 1897 Gothic epistolary masterpiece established Count Dracula and created modern vampire mythology.",
    year: 1914,
    pages: 200,
    audience: "teen",
    coverId: "8232192",
    description: "Nine chilling short stories including the deleted opening chapter of Dracula featuring Walpurgis Night in Munich, 'The Judge's House', and 'The Squaw'.",
    curatorNote: "Features 'The Judge's House', one of the most terrifying haunted house tales in literature.",
    gutenbergId: "10150",
    openLibraryWorkId: "OL21858W",
    subjects: ["Gothic & Horror", "Walpurgis Night", "Short Stories", "Haunted House"]
  },
  {
    title: "The Fall of the House of Usher",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1839,
    pages: 60,
    audience: "teen",
    coverId: "8232193",
    description: "An unnamed narrator visits Roderick Usher in his crumbling ancestral mansion, where family decay and the premature burial of Madeline bring cataclysmic ruin.",
    curatorNote: "The pinnacle of American Gothic atmosphere, psychological decay, and supernatural dread.",
    gutenbergId: "932",
    openLibraryWorkId: "OL41070W",
    subjects: ["Gothic & Horror", "Psychological Horror", "Ancestral Curse", "Usher Mansion"]
  },
  {
    title: "The Masque of the Red Death",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1842,
    pages: 40,
    audience: "teen",
    coverId: "8232194",
    description: "Prince Prospero barricades a thousand courtiers inside a fortified abbey to escape a devastating pestilence, holding a masked ball until an uninvited guest arrives.",
    curatorNote: "A chilling, allegorical masterpiece on the inescapable inevitability of mortality.",
    gutenbergId: "1064",
    openLibraryWorkId: "OL41071W",
    subjects: ["Gothic & Horror", "Allegory", "Pestilence", "Macabre Ball"]
  },
  {
    title: "The Pit and the Pendulum",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1842,
    pages: 50,
    audience: "teen",
    coverId: "8232195",
    description: "A prisoner of the Spanish Inquisition in Toledo endures psychological torture in pitch-black subterranean cells, surrounded by pits and a descending razor-sharp scythe.",
    curatorNote: "A tour de force of sensory deprivation, psychological claustrophobia, and survival.",
    gutenbergId: "2148",
    openLibraryWorkId: "OL41072W",
    subjects: ["Gothic & Horror", "Spanish Inquisition", "Claustrophobia", "Torture Chamber"]
  },
  {
    title: "The Tell-Tale Heart",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1843,
    pages: 35,
    audience: "teen",
    coverId: "8232196",
    description: "An unhinged narrator insists upon his sanity while recounting how he murdered an old man for his 'vulture eye', only for his guilt to beat like a muffled drum.",
    curatorNote: "A psychological masterclass in unreliable narration and auditory hallucinations of guilt.",
    gutenbergId: "2149",
    openLibraryWorkId: "OL41073W",
    subjects: ["Gothic & Horror", "Psychological Horror", "Unreliable Narrator", "Auditory Guilt"]
  },
  {
    title: "The Black Cat",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1843,
    pages: 45,
    audience: "adult",
    coverId: "8232197",
    description: "Alcoholic deterioration drives a man to maim his beloved cat Pluto and murder his wife, until the walled-up corpse reveals itself to investigating police.",
    curatorNote: "Unsparing study of self-destruction and the perverse spirit of malice.",
    gutenbergId: "2150",
    openLibraryWorkId: "OL41074W",
    subjects: ["Gothic & Horror", "Psychological Decay", "Perversity", "Walled-In Corpse"]
  },
  {
    title: "The Cask of Amontillado",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1846,
    pages: 35,
    audience: "teen",
    coverId: "8232198",
    description: "Montresor lures connoisseur Fortunato into his family catacombs during carnival with the promise of rare Amontillado wine, walling him up alive in revenge.",
    curatorNote: "The cold, immaculate perfection of premeditated revenge without consequence.",
    gutenbergId: "1063",
    openLibraryWorkId: "OL41075W",
    subjects: ["Gothic & Horror", "Revenge", "Carnival Catacombs", "Premature Burial"]
  },
  {
    title: "Ligeia",
    author: "Edgar Allan Poe",
    authorBio: "American master of Gothic horror and the macabre whose psychological tales explored madness, guilt, and terror.",
    year: 1838,
    pages: 45,
    audience: "teen",
    coverId: "8232199",
    description: "Grieving the death of his brilliant, ethereal wife Ligeia, an opium-addicted narrator remarries, only for Ligeia's indomitable will to conquer death in the bridal chamber.",
    curatorNote: "Poe's personal favorite story, exploring the triumph of human will over mortality.",
    gutenbergId: "2151",
    openLibraryWorkId: "OL41076W",
    subjects: ["Gothic & Horror", "Supernatural Resurrection", "Opium Dream", "Gothic Romance"]
  },
  {
    title: "The Call of Cthulhu",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1928,
    pages: 70,
    audience: "teen",
    coverId: "8232200",
    description: "Francis Wayland Thurston pieces together notes, bas-relief carvings, and sailor testimonies regarding the nightmare corpse-city of R'lyeh and sleeping god Cthulhu.",
    curatorNote: "The foundational text of cosmic horror that inaugurated the worldwide Cthulhu Mythos.",
    gutenbergId: "65014",
    openLibraryWorkId: "OL10655W",
    subjects: ["Gothic & Horror", "Cosmic Horror", "Cthulhu Mythos", "R'lyeh", "Ancient Gods"]
  },
  {
    title: "The Dunwich Horror",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1929,
    pages: 90,
    audience: "teen",
    coverId: "8232201",
    description: "In decaying rural Massachusetts, Wilbur Whateley breeds an invisible, gargantuan blasphemy sired by Yog-Sothoth, threatening to wipe humanity off the globe.",
    curatorNote: "A quintessential Lovecraftian regional horror set in the blighted hills of Dunwich.",
    gutenbergId: "65015",
    openLibraryWorkId: "OL10656W",
    subjects: ["Gothic & Horror", "Yog-Sothoth", "New England Decay", "Invisible Monster"]
  },
  {
    title: "The Shadow over Innsmouth",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1936,
    pages: 130,
    audience: "teen",
    coverId: "8232202",
    description: "A traveler stranded in the decaying seaport of Innsmouth uncovers a secret pact between the townsfolk and amphibian sea-dwellers known as the Deep Ones.",
    curatorNote: "Features one of the most terrifying, suspenseful hotel escapes in all horror literature.",
    gutenbergId: "65016",
    openLibraryWorkId: "OL10657W",
    subjects: ["Gothic & Horror", "Deep Ones", "Innsmouth", "Hybrid Curse", "Sea Horrors"]
  },
  {
    title: "At the Mountains of Madness",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1936,
    pages: 160,
    audience: "teen",
    coverId: "8232203",
    description: "A Miskatonic University scientific expedition to Antarctica discovers a titanic cyclopean city behind colossal mountains, carved by the pre-human Elder Things.",
    curatorNote: "Lovecraft's science-fiction and cosmic horror masterpiece detailing alien earth history.",
    gutenbergId: "65017",
    openLibraryWorkId: "OL10658W",
    subjects: ["Gothic & Horror", "Antarctica", "Elder Things", "Cosmic Horror", "Alien Ruin"]
  },
  {
    title: "The Whisperer in Darkness",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1931,
    pages: 110,
    audience: "teen",
    coverId: "8232204",
    description: "Literature professor Wilmarth investigates reports of crustacean fungoid extraterrestrials (the Mi-Go) mining secret mineral nodes in Vermont's lonely hills.",
    curatorNote: "A nerve-wracking epistolary tale blending folklore, brain cylinders, and alien dread.",
    gutenbergId: "65018",
    openLibraryWorkId: "OL10659W",
    subjects: ["Gothic & Horror", "Mi-Go", "Alien Infiltration", "Brain Cylinder"]
  },
  {
    title: "The Colour Out of Space",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1927,
    pages: 65,
    audience: "teen",
    coverId: "8232205",
    description: "A meteorite lands on the Gardner farm near Arkham, releasing an unearthly, indescribable luminescent entity that mutates crops and drains all life into grey brittle dust.",
    curatorNote: "Lovecraft considered this his finest story: an entity that defies all earthly spectrums of light.",
    gutenbergId: "65019",
    openLibraryWorkId: "OL10660W",
    subjects: ["Gothic & Horror", "Alien Radiation", "Unnamable Color", "Extraterrestrial Dread"]
  },
  {
    title: "The Dreams in the Witch House",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1933,
    pages: 80,
    audience: "teen",
    coverId: "8232206",
    description: "Quantum physics student Walter Gilman rents an attic room formerly inhabited by witch Keziah Mason, where non-Euclidean geometry opens portals across space.",
    curatorNote: "Brilliantly connects non-Euclidean geometry and quantum dimensions with Salem witchcraft.",
    gutenbergId: "65020",
    openLibraryWorkId: "OL10661W",
    subjects: ["Gothic & Horror", "Witchcraft", "Non-Euclidean Geometry", "Brown Jenkin"]
  },
  {
    title: "The Case of Charles Dexter Ward",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1941,
    pages: 220,
    audience: "teen",
    coverId: "8232207",
    description: "Dr. Marinus Willett investigates the psychological transformation of Charles Ward, who has resurrected his 18th-century necromancer ancestor Joseph Curwen.",
    curatorNote: "Lovecraft's longest and most intricate tale of colonial necromancy and essential salts.",
    gutenbergId: "65021",
    openLibraryWorkId: "OL10662W",
    subjects: ["Gothic & Horror", "Necromancy", "Providence History", "Essential Salts"]
  },
  {
    title: "The Haunter of the Dark",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1936,
    pages: 60,
    audience: "teen",
    coverId: "8232208",
    description: "Writer Robert Blake explores an abandoned neo-Gothic church in Providence, gazing into the Shining Trapezohedron and summoning an ancient shadow entity.",
    curatorNote: "Lovecraft's final written weird tale, dedicated to young author Robert Bloch.",
    gutenbergId: "65022",
    openLibraryWorkId: "OL10663W",
    subjects: ["Gothic & Horror", "Shining Trapezohedron", "Nyarlathotep", "Abandoned Church"]
  },
  {
    title: "Dagon",
    author: "H.P. Lovecraft",
    authorBio: "American author of weird fiction who created the Cthulhu Mythos, pioneering cosmic horror and humanity's existential insignificance in the universe.",
    year: 1919,
    pages: 30,
    audience: "teen",
    coverId: "8232209",
    description: "A morphine-addicted supercargo recalls drifting onto an abyssal volcanic sea mound and witnessing an enormous fish-monstrosity worship a carved monolith.",
    curatorNote: "The seminal early short story that first established the oceanic horror of the Mythos.",
    gutenbergId: "65023",
    openLibraryWorkId: "OL10664W",
    subjects: ["Gothic & Horror", "Sea Monolith", "Dagon", "Abyssal Terror"]
  },
  {
    title: "Carmilla",
    author: "Sheridan Le Fanu",
    authorBio: "Irish writer of Gothic tales and mystery novels who pioneered the psychological ghost story and modern vampire literature.",
    year: 1872,
    pages: 110,
    audience: "teen",
    coverId: "8232210",
    description: "Laura lives in an isolated Austrian castle and welcomes the mysterious carriage-wreck victim Carmilla, only for nocturnal attacks and draining weakness to follow.",
    curatorNote: "The groundbreaking lesbian vampire classic that predated and heavily inspired Bram Stoker's Dracula.",
    gutenbergId: "10007",
    openLibraryWorkId: "OL10550W",
    subjects: ["Gothic & Horror", "Vampires", "Styria Castle", "Gothic Masterpiece"]
  },
  {
    title: "Uncle Silas",
    author: "Sheridan Le Fanu",
    authorBio: "Irish writer of Gothic tales and mystery novels who pioneered the psychological ghost story and modern vampire literature.",
    year: 1864,
    pages: 480,
    audience: "teen",
    coverId: "8232211",
    description: "Heiress Maud Ruthyn is sent to live with her enigmatic, opium-hazed uncle Silas at Bartram-Haugh, gradually realizing she is trapped in a deadly murder web.",
    curatorNote: "One of the greatest Victorian novels of claustrophobic suspense and psychological terror.",
    gutenbergId: "14850",
    openLibraryWorkId: "OL10551W",
    subjects: ["Gothic & Horror", "Claustrophobic Gothic", "Inheritance Plot", "Bartram-Haugh"]
  },
  {
    title: "In a Glass Darkly",
    author: "Sheridan Le Fanu",
    authorBio: "Irish writer of Gothic tales and mystery novels who pioneered the psychological ghost story and modern vampire literature.",
    year: 1872,
    pages: 350,
    audience: "teen",
    coverId: "8232212",
    description: "Five occult case studies from the files of metaphysical physician Dr. Martin Hesselius, including 'Green Tea', 'The Familiar', and 'Carmilla'.",
    curatorNote: "Pioneered the archetype of the psychic investigator and occult detective in literature.",
    gutenbergId: "10832",
    openLibraryWorkId: "OL10552W",
    subjects: ["Gothic & Horror", "Occult Detective", "Dr. Hesselius", "Supernatural Tales"]
  },
  {
    title: "The House by the Churchyard",
    author: "Sheridan Le Fanu",
    authorBio: "Irish writer of Gothic tales and mystery novels who pioneered the psychological ghost story and modern vampire literature.",
    year: 1863,
    pages: 500,
    audience: "adult",
    coverId: "8232213",
    description: "A dark mystery centered around Chapelizod, Ireland, uncovering an unburied skull with two fatal fractures, ghosts, and a sinister traveler named Dangerfield.",
    curatorNote: "James Joyce drew extensively on this Gothic Dublin mystery while writing Finnegans Wake.",
    gutenbergId: "65024",
    openLibraryWorkId: "OL10553W",
    subjects: ["Gothic & Horror", "Irish Gothic", "Chapelizod", "Unburied Skull"]
  },
  {
    title: "Strange Case of Dr Jekyll and Mr Hyde",
    author: "Robert Louis Stevenson",
    authorBio: "Scottish novelist, poet, and essayist who explored dual human nature in one of the most famous psychological horror novellas ever written.",
    year: 1886,
    pages: 96,
    audience: "all",
    coverId: "8232214",
    description: "Dr. Henry Jekyll invents a chemical tincture to separate his respectable social self from his dark primal impulses, giving birth to the murderous Edward Hyde.",
    curatorNote: "The definitive allegory of the divided self, Victorian hypocrisy, and psychological duality.",
    gutenbergId: "43",
    openLibraryWorkId: "OL24165W",
    subjects: ["Gothic & Horror", "Divided Self", "Dr Jekyll and Mr Hyde", "Psychological Horror"]
  },
  {
    title: "The Body Snatcher",
    author: "Robert Louis Stevenson",
    authorBio: "Scottish novelist, poet, and essayist who explored dual human nature in one of the most famous psychological horror novellas ever written.",
    year: 1884,
    pages: 50,
    audience: "teen",
    coverId: "8232215",
    description: "Medical students in Edinburgh purchase fresh cadavers from grave robbers for anatomical dissection, leading into blackmail, murder, and spectral horror.",
    curatorNote: "Based on the gruesome real-life Burke and Hare murders of 19th-century Edinburgh.",
    gutenbergId: "1485",
    openLibraryWorkId: "OL24166W",
    subjects: ["Gothic & Horror", "Body Snatching", "Grave Robbers", "Edinburgh Medicine"]
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    authorBio: "Irish playwright, poet, and wit whose only novel examined aestheticism, moral decadence, and the supernatural corruption of the soul.",
    year: 1890,
    pages: 260,
    audience: "teen",
    coverId: "8232216",
    description: "Young Dorian Gray trades his soul so that his portrait ages and absorbs his sins while he maintains unblemished youth and indulges in ruthless hedonism.",
    curatorNote: "A sparkling, chilling masterpiece of Decadent Gothic fiction and aesthetic consequence.",
    gutenbergId: "174",
    openLibraryWorkId: "OL1488107W",
    subjects: ["Gothic & Horror", "Faustian Bargain", "Aesthetic Decadence", "Supernatural Portrait"]
  },
  {
    title: "The Castle of Otranto",
    author: "Horace Walpole",
    authorBio: "English art historian, man of letters, and politician who launched the entire Gothic literature genre with his 1764 nightmare romance.",
    year: 1764,
    pages: 140,
    audience: "teen",
    coverId: "8232217",
    description: "The violent death of Prince Conrad by a gigantic falling helmet begins an ancestral curse involving bleeding statues, apparitions, and tyrant Manfred.",
    curatorNote: "The historic first Gothic novel that established haunted castles, subterranean vaults, and family curses.",
    gutenbergId: "696",
    openLibraryWorkId: "OL39827W",
    subjects: ["Gothic & Horror", "Foundational Gothic", "Castle Otranto", "Ancestral Curse"]
  },
  {
    title: "The Mysteries of Udolpho",
    author: "Ann Radcliffe",
    authorBio: "English pioneer of Gothic romance who mastered eerie atmospheric terror and the technique of the 'explained supernatural'.",
    year: 1794,
    pages: 670,
    audience: "teen",
    coverId: "8232218",
    description: "Orphaned Emily St. Aubert is imprisoned in the isolated Apennine fortress of Udolpho by the villainous Signor Montoni amid apparitions behind black veils.",
    curatorNote: "The archetypal Gothic castle romance, parodied by Jane Austen in Northanger Abbey.",
    gutenbergId: "3268",
    openLibraryWorkId: "OL39828W",
    subjects: ["Gothic & Horror", "Castle Udolpho", "Explained Supernatural", "Apennine Mountains"]
  },
  {
    title: "The Italian",
    subtitle: "Or, The Confessional of the Black Penitents",
    author: "Ann Radcliffe",
    authorBio: "English pioneer of Gothic romance who mastered eerie atmospheric terror and the technique of the 'explained supernatural'.",
    year: 1797,
    pages: 450,
    audience: "teen",
    coverId: "8232219",
    description: "Young lovers Vincentio and Ellena are pursued by the ruthless monk Father Schedoni across Italian convents, sea coast ruins, and Inquisition prisons.",
    curatorNote: "Features Father Schedoni, the quintessential brooding Gothic villain that inspired Lord Byron.",
    gutenbergId: "4143",
    openLibraryWorkId: "OL39829W",
    subjects: ["Gothic & Horror", "Byronic Villain", "Inquisition", "Italian Gothic"]
  },
  {
    title: "The Monk",
    author: "Matthew Gregory Lewis",
    authorBio: "English novelist and dramatist whose sensational 1796 Gothic horror masterpiece shocked London with demonic pacts and taboo passions.",
    year: 1796,
    pages: 430,
    audience: "adult",
    coverId: "8232220",
    description: "Capuchin monk Ambrosio, celebrated for piety in Madrid, falls into corruption through the demon-seducer Matilda, selling his soul to Lucifer.",
    curatorNote: "The most scandalous, wildly energetic horror novel of the 18th century.",
    gutenbergId: "601",
    openLibraryWorkId: "OL39830W",
    subjects: ["Gothic & Horror", "Lucifer", "Demonic Pact", "Taboo Gothic"]
  },
  {
    title: "Melmoth the Wanderer",
    author: "Charles Robert Maturin",
    authorBio: "Irish Gothic dramatist and novelist whose 1820 epic represents the ultimate culmination of the classic high-Gothic romance.",
    year: 1820,
    pages: 620,
    audience: "adult",
    coverId: "8232221",
    description: "Melmoth sells his soul for 150 years of life, wandering across prisons, asylums, and storm-lashed seas searching for anyone desperate enough to take his cursed bargain.",
    curatorNote: "Praised by Balzac, Baudelaire, and Oscar Wilde as the greatest Faustian wanderer novel.",
    gutenbergId: "65025",
    openLibraryWorkId: "OL39831W",
    subjects: ["Gothic & Horror", "Melmoth", "Faustian Wanderer", "High Gothic"]
  },
  {
    title: "The Great God Pan",
    author: "Arthur Machen",
    authorBio: "Welsh author and mystic whose decadently chilling novellas transformed ancient Celtic pagan survival into psychological horror.",
    year: 1894,
    pages: 110,
    audience: "adult",
    coverId: "8232222",
    description: "A brain experiment to open human perception to the pagan god Pan drives Mary mad, yielding daughter Helen Vaughan who leaves a trail of suicides across London.",
    curatorNote: "Stephen King called it 'maybe the best horror story in the English language.'",
    gutenbergId: "389",
    openLibraryWorkId: "OL32810W",
    subjects: ["Gothic & Horror", "Pagan Terror", "Ancient Gods", "Decadent Horror"]
  },
  {
    title: "The White People",
    author: "Arthur Machen",
    authorBio: "Welsh author and mystic whose decadently chilling novellas transformed ancient Celtic pagan survival into psychological horror.",
    year: 1904,
    pages: 75,
    audience: "teen",
    coverId: "8232223",
    description: "The 'Green Book' diary of a young girl reveals her gradual initiation into sinister pagan nature rites and communion with the terrifying 'White People'.",
    curatorNote: "A masterpiece of folk horror and subtle, innocent descent into unnameable ancient rites.",
    gutenbergId: "25016",
    openLibraryWorkId: "OL32811W",
    subjects: ["Gothic & Horror", "Folk Horror", "Pagan Ritual", "Green Book"]
  },
  {
    title: "The Three Impostors",
    author: "Arthur Machen",
    authorBio: "Welsh author and mystic whose decadently chilling novellas transformed ancient Celtic pagan survival into psychological horror.",
    year: 1895,
    pages: 250,
    audience: "adult",
    coverId: "8232224",
    description: "An episodic London nightmare novel connecting tales of subterranean Little People, black seals, and occult sects operating behind Mayfair facades.",
    curatorNote: "Includes the chilling horror benchmarks 'The Novel of the Black Seal' and 'The White Powder'.",
    gutenbergId: "3580",
    openLibraryWorkId: "OL32812W",
    subjects: ["Gothic & Horror", "Black Seal", "Subterranean Race", "London Occult"]
  },
  {
    title: "The Willows",
    author: "Algernon Blackwood",
    authorBio: "English broadcaster, journalist, and author whose supernatural fiction focused on nature's awe-inspiring and terrifying occult powers.",
    year: 1907,
    pages: 80,
    audience: "teen",
    coverId: "8232225",
    description: "Two canoeists camping on a deserted Danube island amid endless marshes feel the invasive presence of transcendent, hostile entities from another dimension.",
    curatorNote: "H.P. Lovecraft named this the single greatest piece of weird fiction ever written.",
    gutenbergId: "11438",
    openLibraryWorkId: "OL32813W",
    subjects: ["Gothic & Horror", "Danube River", "Cosmic Nature", "Weird Fiction"]
  },
  {
    title: "The Wendigo",
    author: "Algernon Blackwood",
    authorBio: "English broadcaster, journalist, and author whose supernatural fiction focused on nature's awe-inspiring and terrifying occult powers.",
    year: 1910,
    pages: 90,
    audience: "teen",
    coverId: "8232226",
    description: "A hunting party in the primeval Canadian wilderness encounters the Wendigo, the terrifying Indigenous spirit of the frozen wind that kidnaps men across the sky.",
    curatorNote: "The definitive horror story of northern wilderness madness and the devouring wind.",
    gutenbergId: "10897",
    openLibraryWorkId: "OL32814W",
    subjects: ["Gothic & Horror", "Canadian Wilderness", "Wendigo", "Forest Madness"]
  },
  {
    title: "John Silence, Physician Extraordinary",
    author: "Algernon Blackwood",
    authorBio: "English broadcaster, journalist, and author whose supernatural fiction focused on nature's awe-inspiring and terrifying occult powers.",
    year: 1908,
    pages: 320,
    audience: "teen",
    coverId: "8232227",
    description: "Five cases of Dr. John Silence, the wealthy spiritual doctor who heals psychological and supernatural afflictions caused by werewolves, sorcery, and fire spirits.",
    curatorNote: "The preeminent psychic detective stories combining occult erudition with deep empathy.",
    gutenbergId: "4820",
    openLibraryWorkId: "OL32815W",
    subjects: ["Gothic & Horror", "John Silence", "Psychic Doctor", "Occult Cases"]
  },
  {
    title: "Ghost Stories of an Antiquary",
    author: "M.R. James",
    authorBio: "English medievalist scholar and provost of King's College Cambridge who redefined the ghost story using scholarly settings and tactile, malevolent spectres.",
    year: 1904,
    pages: 180,
    audience: "teen",
    coverId: "8232228",
    description: "Eight classic antiquarian ghost stories including 'Count Magnus', 'Canon Alberic's Scrap-Book', and 'Oh, Whistle, and I'll Come to You, My Lad'.",
    curatorNote: "The gold standard of the English ghost story: academic curiosity awakening terrifying ancient horrors.",
    gutenbergId: "8486",
    openLibraryWorkId: "OL32816W",
    subjects: ["Gothic & Horror", "Antiquarian Ghosts", "Scholarly Horror", "M.R. James"]
  },
  {
    title: "More Ghost Stories of an Antiquary",
    author: "M.R. James",
    authorBio: "English medievalist scholar and provost of King's College Cambridge who redefined the ghost story using scholarly settings and tactile, malevolent spectres.",
    year: 1911,
    pages: 170,
    audience: "teen",
    coverId: "8232229",
    description: "Seven masterful uncanny tales including 'Casting the Runes', 'The Stalls of Barchester Cathedral', and 'Martin's Close'.",
    curatorNote: "Contains 'Casting the Runes', the legendary tale of demonic curses passed by inscribed parchment.",
    gutenbergId: "9629",
    openLibraryWorkId: "OL32817W",
    subjects: ["Gothic & Horror", "Casting the Runes", "Cathedral Ghosts", "Classic Horror"]
  },
  {
    title: "A Thin Ghost and Others",
    author: "M.R. James",
    authorBio: "English medievalist scholar and provost of King's College Cambridge who redefined the ghost story using scholarly settings and tactile, malevolent spectres.",
    year: 1919,
    pages: 150,
    audience: "teen",
    coverId: "8232230",
    description: "Five subtle, chilling tales featuring stained-glass demons, cursed fenland churches, and the unforgettable horror 'The Residence at Whitminster'.",
    curatorNote: "Showcases James' uncanny mastery of eerie ecclesiastical history and tactile manifestations.",
    gutenbergId: "20533",
    openLibraryWorkId: "OL32818W",
    subjects: ["Gothic & Horror", "Stained Glass", "Fenland Horror", "Ecclesiastical Ghosts"]
  },
  {
    title: "The Damned Thing",
    author: "Ambrose Bierce",
    authorBio: "American Civil War veteran, journalist, and satirist celebrated for his cynical wit and macabre psychological horror fiction.",
    year: 1893,
    pages: 40,
    audience: "teen",
    coverId: "8232231",
    description: "A coroner's jury in California hears testimony regarding the mauling of Hugh Morgan by an invisible, ferocious entity that cannot be seen due to light spectrum limitations.",
    curatorNote: "A brilliantly innovative scientific horror story of an invisible apex predator.",
    gutenbergId: "4376",
    openLibraryWorkId: "OL74932W",
    subjects: ["Gothic & Horror", "Invisible Monster", "Light Spectrum", "Frontier Horror"]
  },
  {
    title: "Can Such Things Be?",
    author: "Ambrose Bierce",
    authorBio: "American Civil War veteran, journalist, and satirist celebrated for his cynical wit and macabre psychological horror fiction.",
    year: 1893,
    pages: 250,
    audience: "teen",
    coverId: "8232232",
    description: "Twenty-four uncanny tales of sudden disappearances, ghostly apparitions on Civil War battlefields, and mechanical machines that kill their inventors.",
    curatorNote: "Bierce's premier collection of supernatural and macabre mysteries.",
    gutenbergId: "4382",
    openLibraryWorkId: "OL74933W",
    subjects: ["Gothic & Horror", "Supernatural Tales", "Civil War Ghosts", "Bierce Macabre"]
  },
  {
    title: "The Horla",
    author: "Guy de Maupassant",
    authorBio: "French master of the short story whose psychological horror depicted creeping insanity and invisible parasitic entities.",
    year: 1887,
    pages: 50,
    audience: "adult",
    coverId: "8232233",
    description: "A Parisian bourgeois gentleman records his diary while being invisibly drained of vitality and sleep by an unseen, telepathic entity named 'The Horla'.",
    curatorNote: "One of the greatest psychological horror stories ever written on the dawn of unseen human predators.",
    gutenbergId: "7774",
    openLibraryWorkId: "OL74934W",
    subjects: ["Gothic & Horror", "The Horla", "Creeping Madness", "Invisible Parasite"]
  },
  {
    title: "The Turn of the Screw",
    author: "Henry James",
    authorBio: "American-British author regarded as a key transitional figure between literary realism and modernism, known for complex psychological nuance.",
    year: 1898,
    pages: 140,
    audience: "teen",
    coverId: "8232234",
    description: "A young governess at Bly country manor becomes convinced that the two beautiful children are being spiritually possessed by the ghosts of former servants.",
    curatorNote: "The supreme masterpiece of ambiguous psychological ghost fiction: are the spirits real or a projection?",
    gutenbergId: "209",
    openLibraryWorkId: "OL10665W",
    subjects: ["Gothic & Horror", "Governess", "Haunted Children", "Ambiguous Ghost Story"]
  },
  {
    title: "The King in Yellow",
    author: "Robert W. Chambers",
    authorBio: "American artist and novelist whose 1895 short-story collection influenced H.P. Lovecraft and modern weird fiction.",
    year: 1895,
    pages: 220,
    audience: "teen",
    coverId: "8232235",
    description: "Interconnected Paris and New York art tales centered around a forbidden, cursed play that drives anyone who reads its second act irrevocably insane.",
    curatorNote: "Introduced the Yellow Sign, Carcosa, and the King in Yellow that inspired Lovecraft and True Detective.",
    gutenbergId: "8492",
    openLibraryWorkId: "OL10666W",
    subjects: ["Gothic & Horror", "Carcosa", "The Yellow Sign", "Cursed Book", "Weird Fiction"]
  },
  {
    title: "The House on the Borderland",
    author: "William Hope Hodgson",
    authorBio: "English author of weird fiction and nautical horror who served in the merchant marine before dying in World War I.",
    year: 1908,
    pages: 210,
    audience: "adult",
    coverId: "8232236",
    description: "A manuscript found in Irish ruins details a hermit's fortress besieged by swine-things, leading into a cosmic visionary journey to the end of time and solar system.",
    curatorNote: "A staggering milestone linking Gothic haunted-house terror directly with cosmic time-travel horror.",
    gutenbergId: "10001",
    openLibraryWorkId: "OL10667W",
    subjects: ["Gothic & Horror", "Borderland Fortress", "Swine Creatures", "Cosmic Time Travel"]
  },
  {
    title: "The Night Land",
    author: "William Hope Hodgson",
    authorBio: "English author of weird fiction and nautical horror who served in the merchant marine before dying in World War I.",
    year: 1912,
    pages: 580,
    audience: "adult",
    coverId: "8232237",
    description: "Millions of years after the Sun has died, the remaining human race lives inside a seven-mile-high metal pyramid fortress surrounded by colossal dark monsters.",
    curatorNote: "One of the most monumental works of dark, dying-earth planetary fantasy in world literature.",
    gutenbergId: "10662",
    openLibraryWorkId: "OL10668W",
    subjects: ["Gothic & Horror", "Dying Earth", "Metal Redoubt", "Eternal Darkness"]
  },
  {
    title: "The Phantom of the Opera",
    author: "Gaston Leroux",
    authorBio: "French journalist and author whose 1910 Gothic mystery of the subterranean Paris Opera House remains an immortal cultural sensation.",
    year: 1910,
    pages: 310,
    audience: "all",
    coverId: "8232238",
    description: "In the labyrinthine catacombs beneath the Palais Garnier opera house, disfigured musical genius Erik haunts the theater and coaches soprano Christine Daaé.",
    curatorNote: "The romantic Gothic tragedy par excellence, rich in Parisian grandeur and subterranean mystery.",
    gutenbergId: "175",
    openLibraryWorkId: "OL21822W",
    subjects: ["Gothic & Horror", "Paris Opera House", "Subterranean Lake", "Erik the Phantom"]
  }
];
