module.exports = [
  {
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1902,
    pages: 256,
    audience: "teen",
    coverId: "9411873",
    description: "Sherlock Holmes and Dr. Watson investigate the curse of an otherworldly spectral hound haunting Dartmoor manor following Sir Charles Baskerville's uncanny demise.",
    curatorNote: "The crowning atmospheric masterpiece of Sherlockian deduction and Gothic moorland suspense.",
    gutenbergId: "2852",
    openLibraryWorkId: "OL262426W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Gothic Suspense"]
  },
  {
    title: "A Study in Scarlet",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1887,
    pages: 188,
    audience: "teen",
    coverId: "8231991",
    description: "The historical first meeting of Sherlock Holmes and Dr. John H. Watson leads directly into a complex investigation of murder and transcontinental revenge.",
    curatorNote: "The foundational novella that introduced Sherlock Holmes to the literary world.",
    gutenbergId: "244",
    openLibraryWorkId: "OL262412W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Origins"]
  },
  {
    title: "The Sign of the Four",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1890,
    pages: 160,
    audience: "teen",
    coverId: "8231993",
    description: "A mysterious annual gift of pearls draws Holmes and Watson into an intricate web of stolen Agra treasure, secret pacts, and a poisoned dart pursuit along the Thames.",
    curatorNote: "High-octane Baker Street adventure featuring treasure, deception, and Mary Morstan.",
    gutenbergId: "2097",
    openLibraryWorkId: "OL262415W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Stolen Treasure"]
  },
  {
    title: "The Valley of Fear",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1915,
    pages: 248,
    audience: "teen",
    coverId: "8231995",
    description: "A cryptic cipher warns Holmes of the gruesome murder of John Douglas at Birlstone Manor, leading backwards into an American secret society intrigue.",
    curatorNote: "A gripping dual-narrative crime thriller linked to the machinations of Professor Moriarty.",
    gutenbergId: "3289",
    openLibraryWorkId: "OL262428W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Secret Societies"]
  },
  {
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1892,
    pages: 307,
    audience: "teen",
    coverId: "12836246",
    description: "Twelve quintessential Baker Street cases including 'A Scandal in Bohemia', 'The Red-Headed League', and 'The Speckled Band'.",
    curatorNote: "The ultimate short-story collection celebrating Holmes' razor-sharp deductive genius.",
    gutenbergId: "1661",
    openLibraryWorkId: "OL262418W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Short Stories"]
  },
  {
    title: "The Memoirs of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1894,
    pages: 280,
    audience: "teen",
    coverId: "8231997",
    description: "Eleven classic cases documenting Holmes' brilliant triumphs and culminating in the dramatic confrontation with Moriarty at Reichenbach Falls.",
    curatorNote: "Features 'Silver Blaze', 'The Musgrave Ritual', and the epic 'The Final Problem'.",
    gutenbergId: "834",
    openLibraryWorkId: "OL262420W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Classic Enigmas"]
  },
  {
    title: "The Return of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1905,
    pages: 336,
    audience: "teen",
    coverId: "8231998",
    description: "Presumed dead for three years, Holmes astonishes Watson by reappearing in disguise to crack thirteen baffling new London mysteries.",
    curatorNote: "The celebrated collection resurrecting Holmes with cases like 'The Dancing Men'.",
    gutenbergId: "108",
    openLibraryWorkId: "OL262424W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Resurrection"]
  },
  {
    title: "His Last Bow",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1917,
    pages: 208,
    audience: "teen",
    coverId: "8231999",
    description: "A wartime collection of cases including 'The Bruce-Partington Plans' and Holmes' undercover espionage service on the eve of World War I.",
    curatorNote: "Holmes moves from Victorian fog into geopolitical intrigue with timeless panache.",
    gutenbergId: "2350",
    openLibraryWorkId: "OL262427W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Espionage", "Sherlock Holmes"]
  },
  {
    title: "The Case-Book of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created the legendary detective Sherlock Holmes, pioneering modern forensic mystery fiction.",
    year: 1927,
    pages: 240,
    audience: "teen",
    coverId: "8232001",
    description: "The final dozen Baker Street mysteries, including strange tales like 'The Illustrious Client' and 'The Lion's Mane'.",
    curatorNote: "The historic twilight cases that conclude Doyle's legendary Holmesian canon.",
    gutenbergId: "69700",
    openLibraryWorkId: "OL262430W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sherlock Holmes", "Canon Finale"]
  },
  {
    title: "The Mysterious Affair at Styles",
    author: "Agatha Christie",
    authorBio: "English author famously hailed as the 'Queen of Crime', renowned worldwide for her ingenious whodunit plots and iconic detective Hercule Poirot.",
    year: 1920,
    pages: 296,
    audience: "teen",
    coverId: "8232002",
    description: "Belgian refugee detective Hercule Poirot untangles the strychnine poisoning of wealthy matriarch Emily Inglethorp inside an aristocratic country estate.",
    curatorNote: "The historic debut novel of Agatha Christie and the incomparable Hercule Poirot.",
    gutenbergId: "863",
    openLibraryWorkId: "OL471465W",
    subjects: ["Mystery & Crime", "Hercule Poirot", "Whodunit", "Golden Age Mystery"]
  },
  {
    title: "The Secret Adversary",
    author: "Agatha Christie",
    authorBio: "English author famously hailed as the 'Queen of Crime', renowned worldwide for her ingenious whodunit plots and iconic detective Hercule Poirot.",
    year: 1922,
    pages: 320,
    audience: "teen",
    coverId: "8232003",
    description: "Penniless post-war friends Tommy and Tuppence form 'The Young Adventurers Ltd.' and plunge into a perilous conspiracy surrounding missing secret treaty papers.",
    curatorNote: "Spirited, fast-paced espionage mystery introducing Christie's beloved duo Tommy and Tuppence.",
    gutenbergId: "1155",
    openLibraryWorkId: "OL471466W",
    subjects: ["Mystery & Crime", "Espionage", "Tommy and Tuppence", "Post-War Conspiracy"]
  },
  {
    title: "The Murder on the Links",
    author: "Agatha Christie",
    authorBio: "English author famously hailed as the 'Queen of Crime', renowned worldwide for her ingenious whodunit plots and iconic detective Hercule Poirot.",
    year: 1923,
    pages: 288,
    audience: "teen",
    coverId: "8232004",
    description: "Summoned to Northern France, Poirot arrives too late to save millionaire Paul Renauld, found stabbed in the back on a golf course under construction.",
    curatorNote: "Poirot locks wits with a haughty French police inspector in a battle of forensic methods.",
    gutenbergId: "58866",
    openLibraryWorkId: "OL471467W",
    subjects: ["Mystery & Crime", "Hercule Poirot", "Whodunit", "French Riviera"]
  },
  {
    title: "Poirot Investigates",
    author: "Agatha Christie",
    authorBio: "English author famously hailed as the 'Queen of Crime', renowned worldwide for her ingenious whodunit plots and iconic detective Hercule Poirot.",
    year: 1924,
    pages: 298,
    audience: "teen",
    coverId: "8232005",
    description: "Eleven sparkling short mysteries showcasing Poirot's little grey cells solving jewel thefts, Egyptian curses, and vanishing wills.",
    curatorNote: "A delightful showcase of Poirot's sharpest deductions alongside Captain Hastings.",
    gutenbergId: "61262",
    openLibraryWorkId: "OL471468W",
    subjects: ["Mystery & Crime", "Hercule Poirot", "Short Stories", "Classic Whodunit"]
  },
  {
    title: "The Man in the Brown Suit",
    author: "Agatha Christie",
    authorBio: "English author famously hailed as the 'Queen of Crime', renowned worldwide for her ingenious whodunit plots and iconic detective Hercule Poirot.",
    year: 1924,
    pages: 310,
    audience: "teen",
    coverId: "8232006",
    description: "Spirited young Anne Beddingfeld witnesses a fatal tube-station accident and follows a cryptic clue across ocean liners all the way to South Africa.",
    curatorNote: "A thrilling romantic adventure filled with diamond heists and high-stakes intrigue.",
    gutenbergId: "65074",
    openLibraryWorkId: "OL471469W",
    subjects: ["Mystery & Crime", "Adventure", "Diamond Heist", "South Africa"]
  },
  {
    title: "The Secret of Chimneys",
    author: "Agatha Christie",
    authorBio: "English author famously hailed as the 'Queen of Crime', renowned worldwide for her ingenious whodunit plots and ingenious detective plots.",
    year: 1925,
    pages: 306,
    audience: "teen",
    coverId: "8232007",
    description: "Anthony Cade agrees to deliver a Balkan memoir and letters to London, unwittingly stepping into an assassination plot at historic Chimneys estate.",
    curatorNote: "Classic Christie country-house mystery packed with jewel thieves, diplomats, and secret passages.",
    gutenbergId: "65238",
    openLibraryWorkId: "OL471470W",
    subjects: ["Mystery & Crime", "Country House", "Political Thriller", "Inspector Battle"]
  },
  {
    title: "The Moonstone",
    author: "Wilkie Collins",
    authorBio: "English novelist and playwright recognized as the godfather of the modern detective novel and pioneer of epistolary mystery storytelling.",
    year: 1868,
    pages: 528,
    audience: "teen",
    coverId: "8232008",
    description: "The theft of an invaluable yellow diamond from an English heiress leads Sergeant Cuff into a labyrinth of conflicting testimonies and sleepwalking secrets.",
    curatorNote: "Widely regarded by T.S. Eliot and G.K. Chesterton as the first and greatest modern detective novel.",
    gutenbergId: "528",
    openLibraryWorkId: "OL106093W",
    subjects: ["Mystery & Crime", "Detective Fiction", "Sergeant Cuff", "Victorian Classic"]
  },
  {
    title: "The Woman in White",
    author: "Wilkie Collins",
    authorBio: "English novelist and playwright recognized as the godfather of the modern detective novel and pioneer of epistolary mystery storytelling.",
    year: 1859,
    pages: 640,
    audience: "teen",
    coverId: "8232009",
    description: "Drawing master Walter Hartright's midnight encounter with a terrified woman dressed in white uncovers a sinister plot of identity theft and asylum confinement.",
    curatorNote: "The quintessential Victorian sensation novel featuring the cunning villain Count Fosco.",
    gutenbergId: "583",
    openLibraryWorkId: "OL106094W",
    subjects: ["Mystery & Crime", "Sensation Novel", "Gothic Suspense", "Identity Theft"]
  },
  {
    title: "Armadale",
    author: "Wilkie Collins",
    authorBio: "English novelist and playwright recognized as the godfather of the modern detective novel and pioneer of epistolary mystery storytelling.",
    year: 1866,
    pages: 680,
    audience: "adult",
    coverId: "8232010",
    description: "A father's deathbed confession sets two cousins named Allan Armadale on a collision course orchestrated by the ruthless and mesmerizing Lydia Gwilt.",
    curatorNote: "Collins' darkest and most ambitious study of fate, inheritance, and psychological cunning.",
    gutenbergId: "1895",
    openLibraryWorkId: "OL106095W",
    subjects: ["Mystery & Crime", "Psychological Suspense", "Victorian Thriller", "Femme Fatale"]
  },
  {
    title: "No Name",
    author: "Wilkie Collins",
    authorBio: "English novelist and playwright recognized as the godfather of the modern detective novel and pioneer of epistolary mystery storytelling.",
    year: 1862,
    pages: 600,
    audience: "teen",
    coverId: "8232011",
    description: "When the sudden death of their parents leaves two sisters legally disinherited, Magdalen Vanstone assumes multiple disguises to reclaim her family fortune.",
    curatorNote: "A brilliant tour-de-force of theatrical disguise, legal suspense, and female resilience.",
    gutenbergId: "1438",
    openLibraryWorkId: "OL106096W",
    subjects: ["Mystery & Crime", "Legal Suspense", "Disguise & Intrigue", "Victorian Society"]
  },
  {
    title: "The Murders in the Rue Morgue",
    author: "Edgar Allan Poe",
    authorBio: "American writer, poet, and literary critic who invented the modern detective fiction genre with his brilliant ratiocination tales.",
    year: 1841,
    pages: 64,
    audience: "teen",
    coverId: "8232012",
    description: "C. Auguste Dupin investigates the brutal and seemingly impossible double murder of two women locked inside a fourth-story Paris apartment.",
    curatorNote: "The historic landmark that created the archetype of the eccentric deductive sleuth.",
    gutenbergId: "2147",
    openLibraryWorkId: "OL41059W",
    subjects: ["Mystery & Crime", "Locked Room Mystery", "C. Auguste Dupin", "Foundational Classic"]
  },
  {
    title: "The Mystery of Marie Rogêt",
    author: "Edgar Allan Poe",
    authorBio: "American writer, poet, and literary critic who invented the modern detective fiction genre with his brilliant ratiocination tales.",
    year: 1842,
    pages: 72,
    audience: "teen",
    coverId: "8232013",
    description: "Dupin applies rigorous deductive analysis to newspaper accounts to reconstruct the unsolved murder of a Parisian cigar girl found floating in the Seine.",
    curatorNote: "The first fictional detective story based directly on an actual real-life unsolved crime.",
    gutenbergId: "2148",
    openLibraryWorkId: "OL41060W",
    subjects: ["Mystery & Crime", "Forensic Ratiocination", "True Crime Fiction", "C. Auguste Dupin"]
  },
  {
    title: "The Purloined Letter",
    author: "Edgar Allan Poe",
    authorBio: "American writer, poet, and literary critic who invented the modern detective fiction genre with his brilliant ratiocination tales.",
    year: 1844,
    pages: 48,
    audience: "teen",
    coverId: "8232014",
    description: "When the Parisian police fail to find a stolen royal blackmail letter after scouring an apartment inch by inch, Dupin finds it through psychological reasoning.",
    curatorNote: "A masterclass in psychological insight: the art of hiding things in plain sight.",
    gutenbergId: "2149",
    openLibraryWorkId: "OL41061W",
    subjects: ["Mystery & Crime", "Psychological Deduction", "C. Auguste Dupin", "Classic Enigma"]
  },
  {
    title: "The Gold-Bug",
    author: "Edgar Allan Poe",
    authorBio: "American writer, poet, and literary critic who invented the modern detective fiction genre with his brilliant ratiocination tales.",
    year: 1843,
    pages: 60,
    audience: "all",
    coverId: "8232015",
    description: "William Legrand discovers a rare gold beetle and an encrypted parchment revealing the buried pirate treasure of Captain Kidd on Sullivan's Island.",
    curatorNote: "The pioneering cryptographic treasure mystery that popularized substitution ciphers worldwide.",
    gutenbergId: "2150",
    openLibraryWorkId: "OL41062W",
    subjects: ["Mystery & Crime", "Cryptography", "Pirate Treasure", "Cipher Mystery"]
  },
  {
    title: "Arsène Lupin, Gentleman Burglar",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1907,
    pages: 200,
    audience: "teen",
    coverId: "8232016",
    description: "Nine witty escapades introducing the French master thief who robs the corrupt rich with immaculate aristocratic manners and flawless cunning.",
    curatorNote: "The delightful opening adventures of France's beloved gentleman thief and hero.",
    gutenbergId: "4020",
    openLibraryWorkId: "OL132924W",
    subjects: ["Mystery & Crime", "Gentleman Thief", "Arsène Lupin", "French Intrigue"]
  },
  {
    title: "Arsène Lupin versus Herlock Sholmes",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1908,
    pages: 220,
    audience: "teen",
    coverId: "8232017",
    description: "A battle of wits erupts across Paris when the great British consulting detective is hired to track down and outwit Arsène Lupin.",
    curatorNote: "An irresistible clash between French flamboyant charm and British analytical deduction.",
    gutenbergId: "4021",
    openLibraryWorkId: "OL132925W",
    subjects: ["Mystery & Crime", "Gentleman Thief", "Deduction Duel", "Sherlock Parody"]
  },
  {
    title: "The Hollow Needle",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1909,
    pages: 250,
    audience: "teen",
    coverId: "8232018",
    description: "Young prodigy detective Isidore Beautrelet challenges Lupin to decipher the historic secret treasure vault of the French monarchy hidden in Normandy cliffs.",
    curatorNote: "Widely regarded as Leblanc's grandest, most romantic and dramatic Lupin mystery.",
    gutenbergId: "4022",
    openLibraryWorkId: "OL132926W",
    subjects: ["Mystery & Crime", "Historical Secrets", "Arsène Lupin", "Treasure Hunt"]
  },
  {
    title: "813",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1910,
    pages: 380,
    audience: "adult",
    coverId: "8232019",
    description: "Framed for a triple murder in a luxury hotel, Lupin must unmask an elusive, ruthless adversary known only as 'L.M.' to save his reputation.",
    curatorNote: "A dark, labyrinthine epic taking Lupin into European diplomatic high stakes.",
    gutenbergId: "4023",
    openLibraryWorkId: "OL132927W",
    subjects: ["Mystery & Crime", "Arsène Lupin", "Murder Mystery", "High Stakes Intrigue"]
  },
  {
    title: "The Crystal Stopper",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1912,
    pages: 270,
    audience: "teen",
    coverId: "8232020",
    description: "A botched burglary leaves two of Lupin's associates condemned to the guillotine, sparking a race against time to recover a stolen crystal flask.",
    curatorNote: "Packs relentless pace and suspense as Lupin fights against ruthless political blackmailers.",
    gutenbergId: "4024",
    openLibraryWorkId: "OL132928W",
    subjects: ["Mystery & Crime", "Arsène Lupin", "Race Against Time", "Political Blackmail"]
  },
  {
    title: "The Confessions of Arsène Lupin",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1913,
    pages: 230,
    audience: "teen",
    coverId: "8232021",
    description: "Ten sparkling first-person memoirs revealing how Lupin cracked impenetrable safes, recovered stolen signet rings, and outwitted Parisian police.",
    curatorNote: "Intimate and witty glimpses into Lupin's early career and chivalrous escapades.",
    gutenbergId: "4025",
    openLibraryWorkId: "OL132929W",
    subjects: ["Mystery & Crime", "Arsène Lupin", "Short Stories", "Heist Fiction"]
  },
  {
    title: "The Teeth of the Tiger",
    author: "Maurice Leblanc",
    authorBio: "French novelist who created Arsène Lupin, the world's most charming and chivalrous gentleman thief and master of disguise.",
    year: 1914,
    pages: 350,
    audience: "adult",
    coverId: "8232022",
    description: "A mysterious fortune of one hundred million francs left by Cosmo Mornington brings sudden, horrific death to each named heir in sequence.",
    curatorNote: "Lupin returns under the alias Don Luis Perenna in a thrilling inheritance serial murder case.",
    gutenbergId: "4026",
    openLibraryWorkId: "OL132930W",
    subjects: ["Mystery & Crime", "Serial Murders", "Inheritance Plot", "Arsène Lupin"]
  },
  {
    title: "The Innocence of Father Brown",
    author: "G.K. Chesterton",
    authorBio: "English writer, philosopher, and critic who created Father Brown, the gentle Catholic priest whose deep understanding of human nature solves impossible crimes.",
    year: 1911,
    pages: 280,
    audience: "teen",
    coverId: "8232023",
    description: "Twelve dazzling mysteries featuring the mild-mannered priest solving impossible crimes, including 'The Blue Cross' and 'The Secret Garden'.",
    curatorNote: "The seminal Father Brown collection blending brilliant paradox with moral clarity.",
    gutenbergId: "204",
    openLibraryWorkId: "OL15682W",
    subjects: ["Mystery & Crime", "Father Brown", "Moral Deduction", "Paradoxical Mystery"]
  },
  {
    title: "The Wisdom of Father Brown",
    author: "G.K. Chesterton",
    authorBio: "English writer, philosopher, and critic who created Father Brown, the gentle Catholic priest whose deep understanding of human nature solves impossible crimes.",
    year: 1914,
    pages: 260,
    audience: "teen",
    coverId: "8232024",
    description: "Twelve further enigmatic cases where Father Brown illuminates bizarre crimes, impossible disappearances, and the follies of human pride.",
    curatorNote: "Highlights Chesterton's inimitable wit and Father Brown's profound psychological acumen.",
    gutenbergId: "223",
    openLibraryWorkId: "OL15683W",
    subjects: ["Mystery & Crime", "Father Brown", "Detective Fiction", "Psychological Insight"]
  },
  {
    title: "The Incredulity of Father Brown",
    author: "G.K. Chesterton",
    authorBio: "English writer, philosopher, and critic who created Father Brown, the gentle Catholic priest whose deep understanding of human nature solves impossible crimes.",
    year: 1926,
    pages: 240,
    audience: "teen",
    coverId: "8232025",
    description: "Eight ingenious stories examining seemingly supernatural occurrences—including curses, resurrections, and phantom daggers—revealed as cold human crimes.",
    curatorNote: "Father Brown debunks false superstitions with clear-eyed rational skepticism.",
    gutenbergId: "6500",
    openLibraryWorkId: "OL15684W",
    subjects: ["Mystery & Crime", "Father Brown", "Supernatural Debunking", "Classic Whodunit"]
  },
  {
    title: "The Secret of Father Brown",
    author: "G.K. Chesterton",
    authorBio: "English writer, philosopher, and critic who created Father Brown, the gentle Catholic priest whose deep understanding of human nature solves impossible crimes.",
    year: 1927,
    pages: 230,
    audience: "teen",
    coverId: "8232026",
    description: "Father Brown reveals his secret method of deduction: mentally placing himself inside the mind and heart of the criminal before solving the puzzle.",
    curatorNote: "A fascinating look at the philosophy and empathy underpinning Chesterton's detective priest.",
    gutenbergId: "7000",
    openLibraryWorkId: "OL15685W",
    subjects: ["Mystery & Crime", "Father Brown", "Methodology", "Moral Fiction"]
  },
  {
    title: "The Man Who Was Thursday",
    author: "G.K. Chesterton",
    authorBio: "English writer, philosopher, and critic who created Father Brown, the gentle Catholic priest whose deep understanding of human nature solves impossible crimes.",
    year: 1908,
    pages: 210,
    audience: "teen",
    coverId: "8232027",
    description: "Gabriel Syme is recruited into a secret Scotland Yard philosophical police corps and infiltrates the Central Anarchist Council disguised as 'Thursday'.",
    curatorNote: "A metaphysical detective masterpiece of surreal wit, suspense, and cosmic revelation.",
    gutenbergId: "1695",
    openLibraryWorkId: "OL15686W",
    subjects: ["Mystery & Crime", "Metaphysical Thriller", "Undercover Espionage", "Philosophical Satire"]
  },
  {
    title: "The Mystery of the Yellow Room",
    author: "Gaston Leroux",
    authorBio: "French journalist and author of legendary detective and horror classics including The Phantom of the Opera and the Rouletabille mysteries.",
    year: 1907,
    pages: 270,
    audience: "teen",
    coverId: "8232028",
    description: "Young reporter Joseph Rouletabille investigates an attempted murder inside a locked, shuttered laboratory room with no possible exit.",
    curatorNote: "Widely celebrated by Agatha Christie and John Dickson Carr as the greatest locked-room mystery ever penned.",
    gutenbergId: "1938",
    openLibraryWorkId: "OL21820W",
    subjects: ["Mystery & Crime", "Locked Room Mystery", "Rouletabille", "French Detective Fiction"]
  },
  {
    title: "The Perfume of the Lady in Black",
    author: "Gaston Leroux",
    authorBio: "French journalist and author of legendary detective and horror classics including The Phantom of the Opera and the Rouletabille mysteries.",
    year: 1908,
    pages: 290,
    audience: "teen",
    coverId: "8232029",
    description: "Joseph Rouletabille travels to the Mediterranean Fort Hercules to protect Mademoiselle Stangerson from an elusive adversary who seemingly defies death.",
    curatorNote: "The thrilling sequel to The Mystery of the Yellow Room, full of Gothic atmosphere and revelations.",
    gutenbergId: "65001",
    openLibraryWorkId: "OL21821W",
    subjects: ["Mystery & Crime", "Rouletabille", "Gothic Suspense", "Family Secrets"]
  },
  {
    title: "The Leavenworth Case",
    author: "Anna Katharine Green",
    authorBio: "American poet and novelist recognized as the 'Mother of the Detective Novel', who introduced technical legal realism and ballistic evidence to mystery fiction.",
    year: 1878,
    pages: 350,
    audience: "teen",
    coverId: "8232030",
    description: "Merchant Horatio Leavenworth is found shot dead at his library desk, leaving detective Ebenezer Gryce to decipher clues pointing toward two beloved nieces.",
    curatorNote: "The bestselling pioneer of procedural mystery fiction, admired by Wilkie Collins and Arthur Conan Doyle.",
    gutenbergId: "4031",
    openLibraryWorkId: "OL32800W",
    subjects: ["Mystery & Crime", "Ebenezer Gryce", "Procedural Detective", "Ballistic Clues"]
  },
  {
    title: "That Affair Next Door",
    author: "Anna Katharine Green",
    authorBio: "American poet and novelist recognized as the 'Mother of the Detective Novel', who introduced technical legal realism and ballistic evidence to mystery fiction.",
    year: 1897,
    pages: 340,
    audience: "teen",
    coverId: "8232031",
    description: "Inquisitive spinster Amelia Butterworth discovers a dead woman crushed beneath a bookcase in her neighbor's mansion and outwits the police detective.",
    curatorNote: "Introduced the prototype of the brilliant elderly spinster detective that inspired Miss Marple.",
    gutenbergId: "11579",
    openLibraryWorkId: "OL32801W",
    subjects: ["Mystery & Crime", "Amelia Butterworth", "Spinster Sleuth", "Domestic Mystery"]
  },
  {
    title: "The Circular Study",
    author: "Anna Katharine Green",
    authorBio: "American poet and novelist recognized as the 'Mother of the Detective Novel', who introduced technical legal realism and ballistic evidence to mystery fiction.",
    year: 1900,
    pages: 290,
    audience: "teen",
    coverId: "8232032",
    description: "Detective Gryce and Miss Butterworth collaborate to solve the stabbing murder of Felix Cabot in a room furnished only with circular furniture.",
    curatorNote: "A gripping team-up between Green's two greatest deductive protagonists.",
    gutenbergId: "14838",
    openLibraryWorkId: "OL32802W",
    subjects: ["Mystery & Crime", "Detective Gryce", "Miss Butterworth", "Baffling Crime"]
  },
  {
    title: "The Mill Mystery",
    author: "Anna Katharine Green",
    authorBio: "American poet and novelist recognized as the 'Mother of the Detective Novel', who introduced technical legal realism and ballistic evidence to mystery fiction.",
    year: 1886,
    pages: 280,
    audience: "teen",
    coverId: "8232033",
    description: "A young reverend discovers the body of a mill owner in an isolated flour mill, unveiling long-buried grievances in a quiet mountain community.",
    curatorNote: "Atmospheric early American detective tale emphasizing forensic timeline deduction.",
    gutenbergId: "15980",
    openLibraryWorkId: "OL32803W",
    subjects: ["Mystery & Crime", "American Mystery", "Forensics", "Small Town Secrets"]
  },
  {
    title: "The Silent Bullet",
    author: "Arthur B. Reeve",
    authorBio: "American mystery writer who created Professor Craig Kennedy, known as 'The American Sherlock Holmes' for using cutting-edge forensic science to solve crimes.",
    year: 1912,
    pages: 390,
    audience: "teen",
    coverId: "8232034",
    description: "Columbia chemistry professor Craig Kennedy applies dictaphones, lie detectors, and chemical reagents to unravel twelve baffling scientific murders.",
    curatorNote: "Pioneered scientific forensic procedural mysteries decades ahead of its time.",
    gutenbergId: "2834",
    openLibraryWorkId: "OL74921W",
    subjects: ["Mystery & Crime", "Craig Kennedy", "Forensic Science", "Scientific Sleuth"]
  },
  {
    title: "The Poisoned Pen",
    author: "Arthur B. Reeve",
    authorBio: "American mystery writer who created Professor Craig Kennedy, known as 'The American Sherlock Holmes' for using cutting-edge forensic science to solve crimes.",
    year: 1913,
    pages: 400,
    audience: "teen",
    coverId: "8232035",
    description: "Professor Craig Kennedy and reporter Walter Jameson track down poison dart assassinations, germ-warfare threats, and society blackmailers.",
    curatorNote: "Entertaining high-tech Edwardian crime-solving featuring early forensic laboratory techniques.",
    gutenbergId: "1356",
    openLibraryWorkId: "OL74922W",
    subjects: ["Mystery & Crime", "Craig Kennedy", "Forensics", "High-Tech Crimes"]
  },
  {
    title: "The Exploits of Elaine",
    author: "Arthur B. Reeve",
    authorBio: "American mystery writer who created Professor Craig Kennedy, known as 'The American Sherlock Holmes' for using cutting-edge forensic science to solve crimes.",
    year: 1915,
    pages: 320,
    audience: "teen",
    coverId: "8232036",
    description: "Heiress Elaine Dodge and Professor Craig Kennedy battle a masked villain known as 'The Clutching Hand' in a relentless series of traps and escapes.",
    curatorNote: "The wildly popular serial that defined early 20th-century mystery cliffhangers.",
    gutenbergId: "3022",
    openLibraryWorkId: "OL74923W",
    subjects: ["Mystery & Crime", "Craig Kennedy", "Masked Villain", "Pulp Mystery"]
  },
  {
    title: "Raffles: The Amateur Cracksman",
    author: "E.W. Hornung",
    authorBio: "English author and brother-in-law of Arthur Conan Doyle who created A.J. Raffles, the charming gentleman cricketer and burglar of Mayfair.",
    year: 1899,
    pages: 260,
    audience: "teen",
    coverId: "8232037",
    description: "Eight witty stories chronicling the high-society burglaries of cricket champion A.J. Raffles and his loyal accomplice Bunny Manders.",
    curatorNote: "The classic invert of Sherlock Holmes: charming aristocratic heists in Victorian London.",
    gutenbergId: "706",
    openLibraryWorkId: "OL21845W",
    subjects: ["Mystery & Crime", "Gentleman Thief", "A.J. Raffles", "Victorian Heist"]
  },
  {
    title: "A Thief in the Night",
    author: "E.W. Hornung",
    authorBio: "English author and brother-in-law of Arthur Conan Doyle who created A.J. Raffles, the charming gentleman cricketer and burglar of Mayfair.",
    year: 1905,
    pages: 280,
    audience: "teen",
    coverId: "8232038",
    description: "Further adventures of Raffles and Bunny, chronicling audacious jewel burglaries, close calls with Scotland Yard, and code of honour tests.",
    curatorNote: "Sparkles with high-society banter, tension, and criminal ingenuity.",
    gutenbergId: "1284",
    openLibraryWorkId: "OL21846W",
    subjects: ["Mystery & Crime", "Gentleman Thief", "A.J. Raffles", "Society Heist"]
  },
  {
    title: "The Mystery of a Hansom Cab",
    author: "Fergus Hume",
    authorBio: "English-Australian novelist whose debut detective thriller became one of the biggest international publishing sensations of the Victorian era.",
    year: 1886,
    pages: 320,
    audience: "teen",
    coverId: "8232039",
    description: "A gentleman is found murdered by chloroform inside a horse-drawn cab in Melbourne, sparking an investigation into high society scandals and back-alley secrets.",
    curatorNote: "The historic Australian blockbuster that outsold the first Sherlock Holmes stories.",
    gutenbergId: "4223",
    openLibraryWorkId: "OL10640W",
    subjects: ["Mystery & Crime", "Victorian Thriller", "Melbourne", "Classic Whodunit"]
  },
  {
    title: "The Circular Staircase",
    author: "Mary Roberts Rinehart",
    authorBio: "American author dubbed 'The American Agatha Christie', widely known for inventing the 'Had-I-But-Known' suspense school and the butler-did-it trope.",
    year: 1908,
    pages: 300,
    audience: "teen",
    coverId: "8232040",
    description: "Spunky spinster Rachel Innes rents a country mansion for the summer, only for nighttime gunshots, hidden wall safes, and three murders to shatter the peace.",
    curatorNote: "A delightful blend of spine-tingling suspense, clever deduction, and wry humor.",
    gutenbergId: "580",
    openLibraryWorkId: "OL26390W",
    subjects: ["Mystery & Crime", "Country House", "Rachel Innes", "American Mystery"]
  },
  {
    title: "The Thinking Machine",
    author: "Jacques Futrelle",
    authorBio: "American journalist and mystery writer who created Professor Augustus S.F.X. Van Dusen, known as 'The Thinking Machine', before perishing on the Titanic.",
    year: 1907,
    pages: 310,
    audience: "teen",
    coverId: "8232041",
    description: "Professor Van Dusen solves impossible puzzles through pure logic, famously escaping from Death Cell 13 of Chisholm Prison to prove mind over matter.",
    curatorNote: "Contains 'The Problem of Cell 13', universally recognized as one of the pinnacle locked-room stories.",
    gutenbergId: "599",
    openLibraryWorkId: "OL10540W",
    subjects: ["Mystery & Crime", "The Thinking Machine", "Locked Room Mystery", "Pure Logic"]
  },
  {
    title: "The Red Thumb Mark",
    author: "R. Austin Freeman",
    authorBio: "British physician and writer who created forensic investigator Dr. John Thorndyke and pioneered inverted detective stories and fingerprint science.",
    year: 1907,
    pages: 310,
    audience: "teen",
    coverId: "8232042",
    description: "Dr. John Thorndyke uses microscopy and chemistry to prove that a bloody thumbprint found inside a burgled safe was ingeniously forged to frame an innocent man.",
    curatorNote: "The pioneering novel that introduced forensic science and fingerprint forgery to detective literature.",
    gutenbergId: "3645",
    openLibraryWorkId: "OL10590W",
    subjects: ["Mystery & Crime", "Dr. Thorndyke", "Forensic Science", "Fingerprint Forgery"]
  }
];
