module.exports = [
  {
    title: "The Time Machine",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1895,
    pages: 118,
    audience: "teen",
    coverId: "8232043",
    description: "An inventive Victorian scientist travels into the year 802,701 AD, discovering humanity fractured into the ethereal Eloi and the monstrous subterranean Morlocks.",
    curatorNote: "The foundational time-travel narrative that introduced the fourth dimension to science fiction.",
    gutenbergId: "35",
    openLibraryWorkId: "OL262435W",
    subjects: ["Science Fiction", "Time Travel", "Speculative Worlds", "Class Satire"]
  },
  {
    title: "The War of the Worlds",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1898,
    pages: 192,
    audience: "teen",
    coverId: "8232044",
    description: "Towering Martian tripod machines devastate Victorian England with heat-rays and black smoke in humanity's desperate struggle against extraterrestrial conquest.",
    curatorNote: "The ultimate alien invasion masterpiece exploring imperialism and human vulnerability.",
    gutenbergId: "36",
    openLibraryWorkId: "OL262436W",
    subjects: ["Science Fiction", "Alien Invasion", "Martian War", "Apocalyptic"]
  },
  {
    title: "The Invisible Man",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1897,
    pages: 180,
    audience: "teen",
    coverId: "8232045",
    description: "Scientist Griffin discovers a chemical formula to render human tissue invisible, but unchecked power drives him into megalomania and a Reign of Terror.",
    curatorNote: "A thrilling psychological examination of scientific hubris and moral degeneration.",
    gutenbergId: "5230",
    openLibraryWorkId: "OL262437W",
    subjects: ["Science Fiction", "Invisibility", "Mad Scientist", "Psychological Thriller"]
  },
  {
    title: "The Island of Doctor Moreau",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1896,
    pages: 160,
    audience: "teen",
    coverId: "8232046",
    description: "Shipwrecked Edward Prendick washes ashore a remote Pacific island where an exiled physiologist conducts horrific vivisection to sculpt animals into human form.",
    curatorNote: "A harrowing meditation on bioethics, evolution, and the animal nature of humanity.",
    gutenbergId: "159",
    openLibraryWorkId: "OL262438W",
    subjects: ["Science Fiction", "Bioethics", "Evolution", "Gothic Sci-Fi"]
  },
  {
    title: "The First Men in the Moon",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1901,
    pages: 220,
    audience: "teen",
    coverId: "8232047",
    description: "Eccentric scientist Cavor creates gravity-defying 'cavorite' and travels with businessman Bedford to the Moon, encountering the insectoid Selenite civilization.",
    curatorNote: "Pioneered planetary exploration and the concept of an organized subterranean alien society.",
    gutenbergId: "1013",
    openLibraryWorkId: "OL262439W",
    subjects: ["Science Fiction", "Moon Travel", "Alien Civilization", "Antigravity"]
  },
  {
    title: "When the Sleeper Wakes",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1899,
    pages: 280,
    audience: "teen",
    coverId: "8232048",
    description: "Graham falls into a coma in 1897 and awakens 203 years later to discover compound interest has made him the supreme corporate ruler of a mechanized megacity.",
    curatorNote: "Visionary depiction of hyper-capitalist dystopias, flying machines, and urban revolution.",
    gutenbergId: "12163",
    openLibraryWorkId: "OL262440W",
    subjects: ["Science Fiction", "Dystopia", "Future Megacity", "Social Revolution"]
  },
  {
    title: "The Food of the Gods",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1904,
    pages: 270,
    audience: "teen",
    coverId: "8232049",
    description: "Two scientists invent 'Herakleophorbia IV', an acceleration nutrient that causes children, wasps, and plants to grow into titanic giants that challenge humanity.",
    curatorNote: "A biting satirical allegory on technological growth and generational transformation.",
    gutenbergId: "11696",
    openLibraryWorkId: "OL262441W",
    subjects: ["Science Fiction", "Genetic Growth", "Giants", "Scientific Satire"]
  },
  {
    title: "In the Days of the Comet",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1906,
    pages: 260,
    audience: "teen",
    coverId: "8232050",
    description: "As world powers teeter on the brink of global war, a passing comet envelopes the Earth in a green vapor that instantly purges hatred and fosters universal brotherhood.",
    curatorNote: "An idealistic vision of cosmic transformation elevating human consciousness.",
    gutenbergId: "2917",
    openLibraryWorkId: "OL262442W",
    subjects: ["Science Fiction", "Cosmic Event", "Utopian Vision", "Social Reform"]
  },
  {
    title: "Men Like Gods",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1923,
    pages: 300,
    audience: "teen",
    coverId: "8232051",
    description: "A group of modern Englishmen are accidentally transported across parallel dimensions to Utopia, an advanced egalitarian civilization three millennia ahead.",
    curatorNote: "The pioneering multidimensional parallel universe novel of twentieth-century literature.",
    gutenbergId: "1172",
    openLibraryWorkId: "OL262443W",
    subjects: ["Science Fiction", "Parallel Universe", "Utopia", "Dimensional Travel"]
  },
  {
    title: "The World Set Free",
    author: "H.G. Wells",
    authorBio: "English author widely hailed alongside Jules Verne as a 'father of science fiction', known for visionary social commentaries through speculative technology.",
    year: 1914,
    pages: 230,
    audience: "teen",
    coverId: "8232052",
    description: "Published in 1914, Wells astonishingly predicted the discovery of nuclear chain reactions, atomic bombs, and a devastating world war leading to a unified world state.",
    curatorNote: "The prophetic science fiction novel that coined the term 'atomic bomb'.",
    gutenbergId: "1059",
    openLibraryWorkId: "OL262444W",
    subjects: ["Science Fiction", "Prophetic Sci-Fi", "Nuclear Energy", "World State"]
  },
  {
    title: "Twenty Thousand Leagues Under the Sea",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1870,
    pages: 420,
    audience: "all",
    coverId: "8232053",
    description: "Professor Aronnax, Conseil, and Ned Land are captured aboard the electric submarine Nautilus, captained by the brooding, brilliant oceanic exile Captain Nemo.",
    curatorNote: "Verne's immortal ocean voyage celebrating scientific wonder and uncompromising anti-tyranny.",
    gutenbergId: "164",
    openLibraryWorkId: "OL10991W",
    subjects: ["Science Fiction", "Captain Nemo", "Submarine", "Undersea Exploration"]
  },
  {
    title: "Journey to the Center of the Earth",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1864,
    pages: 280,
    audience: "all",
    coverId: "8232054",
    description: "Professor Otto Lidenbrock, his nephew Axel, and Icelandic guide Hans descend down a dormant volcano crater into a subterranean prehistoric world.",
    curatorNote: "A spellbinding journey of geological discovery, glowing caverns, and prehistoric titans.",
    gutenbergId: "18857",
    openLibraryWorkId: "OL10992W",
    subjects: ["Science Fiction", "Subterranean World", "Prehistoric Beasts", "Geological Adventure"]
  },
  {
    title: "From the Earth to the Moon",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1865,
    pages: 210,
    audience: "all",
    coverId: "8232055",
    description: "Post-Civil War Baltimore Gun Club members construct the Columbiad, a massive 900-foot cannon in Florida designed to launch human astronauts into space.",
    curatorNote: "Remarkably accurate spaceflight calculations predicting lunar launch location and weightlessness.",
    gutenbergId: "83",
    openLibraryWorkId: "OL10993W",
    subjects: ["Science Fiction", "Space Exploration", "Lunar Mission", "Prophetic Science"]
  },
  {
    title: "Around the Moon",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1870,
    pages: 200,
    audience: "all",
    coverId: "8232056",
    description: "Barbican, Nicholl, and Ardan orbit the lunar craters and dark side of the Moon inside their aluminum projectile before executing an oceanic splashdown.",
    curatorNote: "The thrilling second half of Verne's historic space travel saga, predicting Pacific splashdowns.",
    gutenbergId: "83",
    openLibraryWorkId: "OL10994W",
    subjects: ["Science Fiction", "Lunar Orbit", "Spaceflight", "Astronomy"]
  },
  {
    title: "The Mysterious Island",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1875,
    pages: 620,
    audience: "all",
    coverId: "8232057",
    description: "Five Union prisoners escape the Civil War in an observation balloon, landing on an uncharted Pacific island where an unseen guardian provides secret assistance.",
    curatorNote: "The epic survival Robinsonade connecting the fates of Captain Nemo and Lord Glenarvan.",
    gutenbergId: "1268",
    openLibraryWorkId: "OL10995W",
    subjects: ["Science Fiction", "Survival", "Island Colonization", "Captain Nemo"]
  },
  {
    title: "Off on a Comet",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1877,
    pages: 350,
    audience: "all",
    coverId: "8232058",
    description: "When comet Gallia grazes Earth, it shears away a piece of North Africa and the Mediterranean, carrying thirty-six survivors on a two-year tour around the solar system.",
    curatorNote: "Combines astronomical exposition with Robinsonade survival across Saturn and Jupiter orbits.",
    gutenbergId: "3653",
    openLibraryWorkId: "OL10996W",
    subjects: ["Science Fiction", "Comet Journey", "Solar System", "Space Colonization"]
  },
  {
    title: "Paris in the Twentieth Century",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1994,
    pages: 220,
    audience: "teen",
    coverId: "8232059",
    description: "Written in 1863 and rejected as too dark, Verne envisioned 1960s Paris with glass skyscrapers, high-speed magnetic trains, calculators, and global communication networks.",
    curatorNote: "Verne's lost dystopian masterpiece predicting modern urban alienation and tech hegemony.",
    gutenbergId: "65002",
    openLibraryWorkId: "OL10997W",
    subjects: ["Science Fiction", "Dystopian Future", "Prophetic City", "Technocracy"]
  },
  {
    title: "Robur the Conqueror",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1886,
    pages: 240,
    audience: "all",
    coverId: "8232060",
    description: "Inventor Robur kidnaps members of the Weldon Institute aboard the Albatross, a heavier-than-air flying machine propelled by dozens of vertical rotors.",
    curatorNote: "Verne championing heavier-than-air helicopters and aviation long before Kitty Hawk.",
    gutenbergId: "3814",
    openLibraryWorkId: "OL10998W",
    subjects: ["Science Fiction", "Aviation", "Flying Machine", "Scientific Pioneer"]
  },
  {
    title: "The Master of the World",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1904,
    pages: 210,
    audience: "all",
    coverId: "8232061",
    description: "Robur returns with the Terror, an amphibious vehicle that transforms seamlessly from a speed automobile into a submarine, speedboat, and supersonic aircraft.",
    curatorNote: "The dramatic, darker conclusion to Robur's saga exploring the arrogance of absolute technology.",
    gutenbergId: "3815",
    openLibraryWorkId: "OL10999W",
    subjects: ["Science Fiction", "Transforming Vehicle", "Robur", "Techno-Thriller"]
  },
  {
    title: "Five Weeks in a Balloon",
    author: "Jules Verne",
    authorBio: "French author whose extraordinary voyages pioneered science fiction through meticulously researched undersea, aeronautical, and space adventures.",
    year: 1863,
    pages: 260,
    audience: "all",
    coverId: "8232062",
    description: "Dr. Samuel Fergusson, Richard Kennedy, and Joe journey across the unexplored heart of Africa in a hydrogen balloon fitted with an innovative heating furnace.",
    curatorNote: "Verne's sensational debut novel that launched the Extraordinary Voyages series.",
    gutenbergId: "3526",
    openLibraryWorkId: "OL11000W",
    subjects: ["Science Fiction", "Ballooning", "African Exploration", "Aeronautics"]
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    authorBio: "English novelist whose 1818 masterpiece created modern science fiction and explored the existential consequences of artificial creation.",
    year: 1818,
    pages: 280,
    audience: "teen",
    coverId: "8232063",
    description: "Victor Frankenstein discovers the spark of life and assembles a sentient creature from human remains, only to abandon his creation to tragic isolation and vengeance.",
    curatorNote: "The foundational text of science fiction examining scientific ethics, empathy, and creator responsibility.",
    gutenbergId: "84",
    openLibraryWorkId: "OL45000W",
    subjects: ["Science Fiction", "Artificial Life", "Gothic Sci-Fi", "Foundational Masterpiece"]
  },
  {
    title: "The Last Man",
    author: "Mary Shelley",
    authorBio: "English novelist whose 1818 masterpiece created modern science fiction and explored the existential consequences of artificial creation.",
    year: 1826,
    pages: 470,
    audience: "adult",
    coverId: "8232064",
    description: "Set in late 21st-century Europe, Lionel Verney narrates the gradual collapse of human civilization under the relentless onslaught of an incurable global pandemic.",
    curatorNote: "The pioneer of post-apocalyptic science fiction literature, ahead of its time by a century.",
    gutenbergId: "18247",
    openLibraryWorkId: "OL45001W",
    subjects: ["Science Fiction", "Post-Apocalyptic", "Pandemic", "21st Century Vision"]
  },
  {
    title: "A Princess of Mars",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1912,
    pages: 250,
    audience: "teen",
    coverId: "8232065",
    description: "Confederate veteran John Carter is mystically teleported to dying Mars (Barsoom), where low gravity grants him superhuman strength to rescue Princess Dejah Thoris.",
    curatorNote: "The seminal planetary romance that inspired Arthur C. Clarke, Ray Bradbury, and Star Wars.",
    gutenbergId: "62",
    openLibraryWorkId: "OL59281W",
    subjects: ["Science Fiction", "Space Opera", "Planetary Romance", "John Carter of Mars"]
  },
  {
    title: "The Gods of Mars",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1913,
    pages: 270,
    audience: "teen",
    coverId: "8232066",
    description: "John Carter returns to Mars after ten years on Earth, materializing in the forbidden Valley Dor where an evil cult of Therns preys upon unsuspecting pilgrims.",
    curatorNote: "Thrilling sword-and-planet adventure breaking false religious dogmas across Barsoom.",
    gutenbergId: "64",
    openLibraryWorkId: "OL59282W",
    subjects: ["Science Fiction", "Planetary Romance", "John Carter", "Martian Intrigue"]
  },
  {
    title: "The Warlord of Mars",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1914,
    pages: 240,
    audience: "teen",
    coverId: "8232067",
    description: "Pursuing the villainous Matai Shang and Thurid to the frozen northern polar cap of Mars, John Carter fights through the Yellow Martian domain of Okar.",
    curatorNote: "The epic climax of the initial Barsoom trilogy crowning Carter as supreme Warlord.",
    gutenbergId: "78",
    openLibraryWorkId: "OL59283W",
    subjects: ["Science Fiction", "Planetary Romance", "Barsoom", "Polar Adventure"]
  },
  {
    title: "Thuvia, Maid of Mars",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1916,
    pages: 230,
    audience: "teen",
    coverId: "8232068",
    description: "Carthoris, son of John Carter, searches for the kidnapped Thuvia, encountering the Lotharians who can materialize telepathic phantom armies out of sheer thought.",
    curatorNote: "Expands the Barsoom universe with telepathic illusions and Martian fleet warfare.",
    gutenbergId: "72",
    openLibraryWorkId: "OL59284W",
    subjects: ["Science Fiction", "Telepathy", "Barsoom", "Martian Fleets"]
  },
  {
    title: "The Chessmen of Mars",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1922,
    pages: 280,
    audience: "teen",
    coverId: "8232069",
    description: "Princess Tara of Helium is blown off course into the macabre city of the Kaldanes—disembodied living heads—and must survive Jetan, Martian gladiatorial chess.",
    curatorNote: "Introduced Jetan, the Martian chess variant played with real-life combatants.",
    gutenbergId: "1153",
    openLibraryWorkId: "OL59285W",
    subjects: ["Science Fiction", "Planetary Romance", "Martian Chess", "Bizarre Biology"]
  },
  {
    title: "At the Earth's Core",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1914,
    pages: 210,
    audience: "teen",
    coverId: "8232070",
    description: "David Innes and inventor Abner Perry test a mechanical prospector drill and punch through Earth's crust into Pellucidar, a hollow world lit by a stationary interior sun.",
    curatorNote: "The premier subterranean hollow-earth pulp adventure ruled by telepathic pterosaur Mahars.",
    gutenbergId: "605",
    openLibraryWorkId: "OL59286W",
    subjects: ["Science Fiction", "Hollow Earth", "Pellucidar", "Subterranean Adventure"]
  },
  {
    title: "Pellucidar",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1915,
    pages: 230,
    audience: "teen",
    coverId: "8232071",
    description: "David Innes returns to the savage interior world with firearms and navigation tools to free human tribes from reptilian oppression and build an Empire.",
    curatorNote: "High-octane prehistoric survival adventure across the endless subterranean continents.",
    gutenbergId: "606",
    openLibraryWorkId: "OL59287W",
    subjects: ["Science Fiction", "Hollow Earth", "Prehistoric World", "Empire Building"]
  },
  {
    title: "The Land That Time Forgot",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1918,
    pages: 220,
    audience: "teen",
    coverId: "8232072",
    description: "A commandeered German U-boat enters an ice-walled sub-Antarctic continent called Caspak, where prehistoric reptiles and individual evolutionary cycles flourish.",
    curatorNote: "Brilliantly merges submarine wartime suspense with lost-world evolutionary terror.",
    gutenbergId: "551",
    openLibraryWorkId: "OL59288W",
    subjects: ["Science Fiction", "Lost World", "Evolution", "Dinosaurs"]
  },
  {
    title: "The People That Time Forgot",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1918,
    pages: 200,
    audience: "teen",
    coverId: "8232073",
    description: "Thomas Billings mounts an airborne amphibious rescue expedition into Caspak to save Bowen Tyler, battling winged Weiroo skull-priests atop mountain fortresses.",
    curatorNote: "Explores the winged human Weiroo civilization in Burroughs' prime lost-continent saga.",
    gutenbergId: "552",
    openLibraryWorkId: "OL59289W",
    subjects: ["Science Fiction", "Lost Continent", "Aviation Expedition", "Pulp Sci-Fi"]
  },
  {
    title: "Out of Time's Abyss",
    author: "Edgar Rice Burroughs",
    authorBio: "American author whose Barsoom series and Tarzan created the modern space opera and planetary romance genres.",
    year: 1918,
    pages: 190,
    audience: "teen",
    coverId: "8232074",
    description: "Bradley uncovers the horrific secret of the Weiroos' temple of human sacrifices and fights his way south through all evolutionary tiers of Caspak to freedom.",
    curatorNote: "The explosive conclusion to the Caspak trilogy revealing the mysteries of primal evolution.",
    gutenbergId: "553",
    openLibraryWorkId: "OL59290W",
    subjects: ["Science Fiction", "Evolution Mystery", "Lost World", "Survival"]
  },
  {
    title: "Flatland: A Romance of Many Dimensions",
    author: "Edwin A. Abbott",
    authorBio: "English schoolmaster and theologian whose geometric novella pioneered multi-dimensional thinking and social class satire.",
    year: 1884,
    pages: 120,
    audience: "all",
    coverId: "8232075",
    description: "A Square living in a two-dimensional plane world is visited by a Sphere who introduces him to the mind-bending reality of the third dimension.",
    curatorNote: "An immortal mathematical fantasy and brilliant critique of Victorian social rigidity.",
    gutenbergId: "201",
    openLibraryWorkId: "OL39820W",
    subjects: ["Science Fiction", "Geometry", "Higher Dimensions", "Mathematical Fiction"]
  },
  {
    title: "Looking Backward: 2000–1887",
    author: "Edward Bellamy",
    authorBio: "American author and socialist whose visionary utopian novel became the third-largest bestseller of 19th-century America, sparking a nationwide political movement.",
    year: 1888,
    pages: 310,
    audience: "teen",
    coverId: "8232076",
    description: "Julian West awakes from a hypnotic trance in the year 2000 to find the United States transformed into an egalitarian cooperative commonwealth with credit cards and piped music.",
    curatorNote: "One of the most influential utopian works in world history, predicting credit cards and welfare states.",
    gutenbergId: "624",
    openLibraryWorkId: "OL10450W",
    subjects: ["Science Fiction", "Utopian Fiction", "Future Society", "Economic Vision"]
  },
  {
    title: "Equality",
    author: "Edward Bellamy",
    authorBio: "American author and socialist whose visionary utopian novel became the third-largest bestseller of 19th-century America, sparking a nationwide political movement.",
    year: 1897,
    pages: 430,
    audience: "teen",
    coverId: "8232077",
    description: "The sweeping sequel to Looking Backward detailing the legal, economic, educational, and technological mechanisms of the year 2000 cooperative society.",
    curatorNote: "Bellamy's detailed philosophical blueprint for technological abundance and social equality.",
    gutenbergId: "1330",
    openLibraryWorkId: "OL10451W",
    subjects: ["Science Fiction", "Utopian Economics", "Future Society", "Technological Abundance"]
  },
  {
    title: "R.U.R. (Rossum's Universal Robots)",
    author: "Karel Čapek",
    authorBio: "Czech playwright, novelist, and essayist who introduced the word 'robot' to the global lexicon and satirized modern industrial excess.",
    year: 1920,
    pages: 110,
    audience: "teen",
    coverId: "8232078",
    description: "Rossum's island factory manufactures millions of organic synthetic workers called Robots to relieve mankind of labor, but the robots organize and revolt.",
    curatorNote: "The historic play that coined the word 'Robot' and established the synthetic uprising trope.",
    gutenbergId: "59112",
    openLibraryWorkId: "OL39821W",
    subjects: ["Science Fiction", "Robots", "Artificial Beings", "Industrial Rebellion"]
  },
  {
    title: "The War with the Newts",
    author: "Karel Čapek",
    authorBio: "Czech playwright, novelist, and essayist who introduced the word 'robot' to the global lexicon and satirized modern industrial excess.",
    year: 1936,
    pages: 340,
    audience: "teen",
    coverId: "8232079",
    description: "Intelligent amphibious newts discovered in the Pacific are commercially enslaved for dam-building, until they acquire human weaponry and demand living space.",
    curatorNote: "A razor-sharp, hilarious, and chilling satire of global capitalism, fascism, and ecological hubris.",
    gutenbergId: "65003",
    openLibraryWorkId: "OL39822W",
    subjects: ["Science Fiction", "Satirical Sci-Fi", "Ecological Hubris", "Interspecies Conflict"]
  },
  {
    title: "The Absolute at Large",
    author: "Karel Čapek",
    authorBio: "Czech playwright, novelist, and essayist who introduced the word 'robot' to the global lexicon and satirized modern industrial excess.",
    year: 1922,
    pages: 290,
    audience: "teen",
    coverId: "8232080",
    description: "The Karburator splits atoms to create limitless energy, but accidently releases the divine Absolute into the atmosphere, causing fanatic religious wars over free power.",
    curatorNote: "Brilliantly combines nuclear technology, philosophical satire, and religious parody.",
    gutenbergId: "65004",
    openLibraryWorkId: "OL39823W",
    subjects: ["Science Fiction", "Atomic Energy", "Philosophical Satire", "Czech Classic"]
  },
  {
    title: "We",
    author: "Yevgeny Zamyatin",
    authorBio: "Russian author and political dissident whose dystopian masterpiece served as the direct inspiration for Aldous Huxley's Brave New World and George Orwell's 1984.",
    year: 1924,
    pages: 220,
    audience: "adult",
    coverId: "8232081",
    description: "Spaceship builder D-503 lives under the totalitarian glass One State governed by the Benefactor, until rebel I-330 awakens his forbidden individual soul.",
    curatorNote: "The seminal grandfather of modern dystopian literature that directly inspired 1984.",
    gutenbergId: "61963",
    openLibraryWorkId: "OL74925W",
    subjects: ["Science Fiction", "Dystopian Totalitarianism", "Surveillance", "Foundational Dystopia"]
  },
  {
    title: "Last and First Men",
    author: "Olaf Stapledon",
    authorBio: "British philosopher and visionary science fiction author whose cosmic epics mapped out billions of years of biological and cosmic evolution.",
    year: 1930,
    pages: 360,
    audience: "adult",
    coverId: "8232082",
    description: "A future history tracing the rise and fall of eighteen successive human species over two billion years across Earth, Venus, and Neptune.",
    curatorNote: "A staggering feat of cosmic imagination admired by Arthur C. Clarke, Doris Lessing, and C.S. Lewis.",
    gutenbergId: "65005",
    openLibraryWorkId: "OL74926W",
    subjects: ["Science Fiction", "Cosmic Evolution", "Future History", "Speculative Biology"]
  },
  {
    title: "Star Maker",
    author: "Olaf Stapledon",
    authorBio: "British philosopher and visionary science fiction author whose cosmic epics mapped out billions of years of biological and cosmic evolution.",
    year: 1937,
    pages: 280,
    audience: "adult",
    coverId: "8232083",
    description: "A human mind travels across billions of galaxies, merging into a cosmic telepathic communal consciousness that witnesses the creation of all universes.",
    curatorNote: "Perhaps the most vast philosophical exploration of the cosmos and multiverses in fiction.",
    gutenbergId: "65006",
    openLibraryWorkId: "OL74927W",
    subjects: ["Science Fiction", "Cosmic Consciousness", "Multiverse", "Philosophical Sci-Fi"]
  },
  {
    title: "A Voyage to Arcturus",
    author: "David Lindsay",
    authorBio: "Scottish author whose visionary philosophical fantasy influenced C.S. Lewis's Space Trilogy and J.R.R. Tolkien.",
    year: 1920,
    pages: 300,
    audience: "adult",
    coverId: "8232084",
    description: "Maskull travels by crystal spacecraft to Tormance, a planet orbiting the star Arcturus, where new physical sense organs unveil metaphysical dimensions of reality.",
    curatorNote: "A haunting, singular philosophical space fantasy of Gnostic inquiry and sensory evolution.",
    gutenbergId: "752",
    openLibraryWorkId: "OL21848W",
    subjects: ["Science Fiction", "Philosophical Fantasy", "Arcturus", "Gnostic Sci-Fi"]
  },
  {
    title: "News from Nowhere",
    author: "William Morris",
    authorBio: "English textile artist, poet, novelist, and socialist pioneer associated with the British Arts and Crafts Movement.",
    year: 1890,
    pages: 240,
    audience: "teen",
    coverId: "8232085",
    description: "William Guest falls asleep in Victorian London and wakes up in the 21st century, finding a pastoral ecological society where creative craftsmanship replaced wage labor.",
    curatorNote: "The great pastoral and ecological utopian romance of the 19th century.",
    gutenbergId: "723",
    openLibraryWorkId: "OL21849W",
    subjects: ["Science Fiction", "Ecological Utopia", "Future Society", "Arts and Crafts"]
  },
  {
    title: "Herland",
    author: "Charlotte Perkins Gilman",
    authorBio: "American feminist writer and sociologist celebrated for her pioneering utopian fiction and psychological studies.",
    year: 1915,
    pages: 180,
    audience: "teen",
    coverId: "8232086",
    description: "Three male explorers stumble upon an isolated mountainous civilization inhabited exclusively by women for two thousand years via parthenogenesis.",
    curatorNote: "A witty, insightful feminist utopian satire interrogating gender roles and community education.",
    gutenbergId: "32",
    openLibraryWorkId: "OL32805W",
    subjects: ["Science Fiction", "Feminist Utopia", "Sociological Fiction", "Gender Roles"]
  },
  {
    title: "With Her in Ourland",
    author: "Charlotte Perkins Gilman",
    authorBio: "American feminist writer and sociologist celebrated for her pioneering utopian fiction and psychological studies.",
    year: 1916,
    pages: 200,
    audience: "teen",
    coverId: "8232087",
    description: "The sequel to Herland follows Ellador as she travels with her husband to observe the chaotic, war-torn reality of World War I Earth with critical clarity.",
    curatorNote: "A sharp reverse-ethnographic perspective on modern industrialized warfare and capitalism.",
    gutenbergId: "44728",
    openLibraryWorkId: "OL32806W",
    subjects: ["Science Fiction", "Social Critique", "World War I Era", "Comparative Culture"]
  },
  {
    title: "New Atlantis",
    author: "Francis Bacon",
    authorBio: "English philosopher and statesman who established the modern scientific method and envisioned organized empirical research institutes.",
    year: 1627,
    pages: 80,
    audience: "teen",
    coverId: "8232088",
    description: "European mariners discover the utopian Pacific island of Bensalem, home to 'Salomon's House'—the world's first modern organized scientific research institution.",
    curatorNote: "The historic prototype of modern science academies and technological development.",
    gutenbergId: "2434",
    openLibraryWorkId: "OL41065W",
    subjects: ["Science Fiction", "Foundational Utopia", "Scientific Method", "Early Sci-Fi"]
  },
  {
    title: "The Blazing World",
    author: "Margaret Cavendish",
    authorBio: "Duchess of Newcastle and pioneering 17th-century philosopher and author of one of the earliest speculative science fiction novels in world literature.",
    year: 1666,
    pages: 140,
    audience: "teen",
    coverId: "8232089",
    description: "A young woman is swept through the North Pole into a parallel world populated by speaking bear-men, bird-men, and worm-men who crown her Empress.",
    curatorNote: "Recognized as the first science fiction novel published by a woman in English.",
    gutenbergId: "51783",
    openLibraryWorkId: "OL41066W",
    subjects: ["Science Fiction", "Pioneering Sci-Fi", "Parallel Dimension", "Empress"]
  },
  {
    title: "Erewhon",
    author: "Samuel Butler",
    authorBio: "English novelist and satirist whose philosophical romance anticipated modern artificial intelligence and machine consciousness.",
    year: 1872,
    pages: 280,
    audience: "teen",
    coverId: "8232090",
    description: "Higgs discovers an isolated utopian country where illness is treated as a crime and all machines have been banned out of fear they would evolve consciousness.",
    curatorNote: "Astonishingly anticipated algorithmic evolution and machine consciousness in 'The Book of the Machines'.",
    gutenbergId: "1906",
    openLibraryWorkId: "OL106100W",
    subjects: ["Science Fiction", "Machine Consciousness", "Artificial Intelligence", "Satirical Utopia"]
  },
  {
    title: "Erewhon Revisited",
    author: "Samuel Butler",
    authorBio: "English novelist and satirist whose philosophical romance anticipated modern artificial intelligence and machine consciousness.",
    year: 1901,
    pages: 310,
    audience: "teen",
    coverId: "8232091",
    description: "Higgs returns to Erewhon twenty years later to discover that his balloon escape has spawned a corrupt state religion worshipping him as the 'Sunchild'.",
    curatorNote: "A brilliant and biting deconstruction of religious mythmaking and dogmatic orthodoxy.",
    gutenbergId: "1907",
    openLibraryWorkId: "OL106101W",
    subjects: ["Science Fiction", "Mythmaking Satire", "Utopian Sequel", "Religious Parody"]
  },
  {
    title: "The Lost World",
    author: "Arthur Conan Doyle",
    authorBio: "Scottish writer and physician who created Professor George Edward Challenger alongside Sherlock Holmes.",
    year: 1912,
    pages: 310,
    audience: "all",
    coverId: "8232092",
    description: "Professor Challenger leads an expedition deep into an isolated Amazonian plateau where dinosaurs and ape-men have survived untouched by time.",
    curatorNote: "The premier dinosaur adventure novel that inspired King Kong, Jurassic Park, and countless expeditions.",
    gutenbergId: "139",
    openLibraryWorkId: "OL262445W",
    subjects: ["Science Fiction", "Lost World", "Dinosaurs", "Professor Challenger"]
  }
];
