module.exports = [
  {
    title: "Commentaries on the Gallic War",
    author: "Julius Caesar",
    authorBio: "Roman general, statesman, and dictator whose campaigns and firsthand military commentaries transformed the Roman Republic into an Empire.",
    year: -50,
    pages: 310,
    audience: "teen",
    coverId: "8232287",
    description: "Caesar's legendary firsthand account of his nine years conquering Celtic and Germanic tribes, bridging the Rhine, and crossing to Britain.",
    curatorNote: "The supreme military memoir of antiquity, written with crisp Roman clarity and political genius.",
    gutenbergId: "10657",
    openLibraryWorkId: "OL21864W",
    subjects: ["History & Life", "Roman History", "Julius Caesar", "Gallic Wars", "Military Chronicles"]
  },
  {
    title: "The Civil War",
    author: "Julius Caesar",
    authorBio: "Roman general, statesman, and dictator whose campaigns and firsthand military commentaries transformed the Roman Republic into an Empire.",
    year: -47,
    pages: 260,
    audience: "teen",
    coverId: "8232288",
    description: "Caesar recounts crossing the Rubicon, pursuing Pompey the Great to Greece, the decisive Battle of Pharsalus, and the Alexandria campaign.",
    curatorNote: "Firsthand witness to the cataclysmic political struggle that established the Roman Empire.",
    gutenbergId: "10565",
    openLibraryWorkId: "OL21865W",
    subjects: ["History & Life", "Roman Civil War", "Crossing the Rubicon", "Pompey the Great", "Battle of Pharsalus"]
  },
  {
    title: "History of the Peloponnesian War",
    author: "Thucydides",
    authorBio: "Athenian general and historian regarded as the father of scientific history and political realism for his evidence-based analysis.",
    year: -404,
    pages: 600,
    audience: "adult",
    coverId: "8232289",
    description: "The devastating thirty-year war between democratic Athens and oligarchic Sparta, featuring Pericles' Funeral Oration and the Melian Dialogue.",
    curatorNote: "The foundational monument of political realism, geopolitics, and historical causation.",
    gutenbergId: "7142",
    openLibraryWorkId: "OL21866W",
    subjects: ["History & Life", "Peloponnesian War", "Athens and Sparta", "Thucydides", "Political Realism"]
  },
  {
    title: "The Histories",
    author: "Herodotus",
    authorBio: "Ancient Greek historian hailed by Cicero as the 'Father of History' who recorded the Greco-Persian Wars and diverse ancient civilizations.",
    year: -430,
    pages: 720,
    audience: "teen",
    coverId: "8232290",
    description: "The origins and clashes of the Greco-Persian Wars, enriched with vivid ethnographic explorations of Egypt, Scythia, Babylon, and Marathon.",
    curatorNote: "The opening chronicle of human historical writing, overflowing with storytelling wonder.",
    gutenbergId: "2707",
    openLibraryWorkId: "OL21867W",
    subjects: ["History & Life", "Greco-Persian Wars", "Herodotus", "Thermopylae", "Ancient World"]
  },
  {
    title: "Anabasis",
    subtitle: "The March of the Ten Thousand",
    author: "Xenophon",
    authorBio: "Athenian soldier, mercenary leader, and philosopher who led ten thousand Greek soldiers out of the heart of the Persian Empire to the Black Sea.",
    year: -370,
    pages: 340,
    audience: "teen",
    coverId: "8232291",
    description: "Trapped in the heart of Mesopotamia after Cyrus's death, Xenophon leads 10,000 Greek mercenaries through Kurdish mountains to the cry: 'Thalatta! Thalatta!'",
    curatorNote: "The greatest military retreat and survival odyssey in ancient historical literature.",
    gutenbergId: "1170",
    openLibraryWorkId: "OL21868W",
    subjects: ["History & Life", "Ten Thousand", "Persian Empire", "Xenophon", "Survival Trek"]
  },
  {
    title: "Cyropaedia",
    subtitle: "The Education of Cyrus",
    author: "Xenophon",
    authorBio: "Athenian soldier, mercenary leader, and philosopher who led ten thousand Greek soldiers out of the heart of the Persian Empire to the Black Sea.",
    year: -365,
    pages: 420,
    audience: "teen",
    coverId: "8232292",
    description: "A philosophical biographical chronicle of Cyrus the Great, founder of the Achaemenid Persian Empire, analyzing leadership, justice, and statecraft.",
    curatorNote: "The classic manual of enlightened leadership studied by Scipio Africanus and Machiavelli.",
    gutenbergId: "2085",
    openLibraryWorkId: "OL21869W",
    subjects: ["History & Life", "Cyrus the Great", "Leadership", "Persian Empire", "Statecraft"]
  },
  {
    title: "Memorabilia",
    author: "Xenophon",
    authorBio: "Athenian soldier, mercenary leader, and philosopher who led ten thousand Greek soldiers out of the heart of the Persian Empire to the Black Sea.",
    year: -371,
    pages: 210,
    audience: "teen",
    coverId: "8232293",
    description: "Xenophon's practical, biographical recollections defending his beloved teacher Socrates against Athens' charges of impiety and moral corruption.",
    curatorNote: "The down-to-earth biographical companion to Plato's dialogues, showing Socrates in daily life.",
    gutenbergId: "1177",
    openLibraryWorkId: "OL21870W",
    subjects: ["History & Life", "Socrates", "Xenophon", "Ancient Athens", "Biographical Defense"]
  },
  {
    title: "Plutarch's Lives (Volume 1)",
    author: "Plutarch",
    authorBio: "Greek biographer and essayist whose Parallel Lives compared famous Greek and Roman statesmen, shaping Shakespeare and the founding fathers.",
    year: 100,
    pages: 650,
    audience: "teen",
    coverId: "8232294",
    description: "Paired comparative biographies including Alexander the Great and Julius Caesar, Theseus and Romulus, exploring character and moral virtue in action.",
    curatorNote: "The quintessential biographical monument that supplied Shakespeare with his Roman plays.",
    gutenbergId: "674",
    openLibraryWorkId: "OL21871W",
    subjects: ["History & Life", "Parallel Lives", "Alexander the Great", "Julius Caesar", "Biographies"]
  },
  {
    title: "Plutarch's Lives (Volume 2)",
    author: "Plutarch",
    authorBio: "Greek biographer and essayist whose Parallel Lives compared famous Greek and Roman statesmen, shaping Shakespeare and the founding fathers.",
    year: 100,
    pages: 680,
    audience: "teen",
    coverId: "8232295",
    description: "Further paired profiles of Demosthenes and Cicero, Pericles and Fabius Maximus, and Mark Antony, examining triumph, eloquence, and tragic hubris.",
    curatorNote: "Unforgettable character studies of Cicero, Mark Antony, and Cleopatra.",
    gutenbergId: "675",
    openLibraryWorkId: "OL21872W",
    subjects: ["History & Life", "Cicero", "Mark Antony", "Parallel Lives", "Ancient Biographies"]
  },
  {
    title: "The Annals",
    author: "Tacitus",
    authorBio: "Roman senator and historian celebrated for his psychological analysis, scathing brevity, and unflinching exposure of imperial despotism.",
    year: 117,
    pages: 520,
    audience: "adult",
    coverId: "8232296",
    description: "Tacitus chronicles the Julio-Claudian dynasty from Tiberius through Caligula, Claudius, and Nero, exposing court corruption and reign of terror.",
    curatorNote: "The supreme masterpiece of Roman political history, laying bare the psychological mechanics of tyranny.",
    gutenbergId: "65027",
    openLibraryWorkId: "OL21873W",
    subjects: ["History & Life", "Julio-Claudian Dynasty", "Nero", "Tiberius", "Roman Imperial History"]
  },
  {
    title: "The Histories",
    author: "Tacitus",
    authorBio: "Roman senator and historian celebrated for his psychological analysis, scathing brevity, and unflinching exposure of imperial despotism.",
    year: 105,
    pages: 380,
    audience: "adult",
    coverId: "8232297",
    description: "A harrowing eyewitness chronicle of the Year of the Four Emperors (69 AD), following Galba, Otho, Vitellius, and the rise of Vespasian amid civil war.",
    curatorNote: "Dramatic, intense portrayal of military mutinies, street battles in Rome, and political collapse.",
    gutenbergId: "65028",
    openLibraryWorkId: "OL21874W",
    subjects: ["History & Life", "Four Emperors", "Roman Civil War", "Vespasian", "Tacitus"]
  },
  {
    title: "Germania and Agricola",
    author: "Tacitus",
    authorBio: "Roman senator and historian celebrated for his psychological analysis, scathing brevity, and unflinching exposure of imperial despotism.",
    year: 98,
    pages: 180,
    audience: "teen",
    coverId: "8232298",
    description: "Tacitus's ethnographic study of the fierce Germanic tribes, paired with a moving biography of his father-in-law Agricola's conquest and governance of Britain.",
    curatorNote: "Contains the immortal critique of Roman conquest: 'They make a desolation and call it peace.'",
    gutenbergId: "2024",
    openLibraryWorkId: "OL21875W",
    subjects: ["History & Life", "Ancient Germany", "Roman Britain", "Agricola", "Imperial Critique"]
  },
  {
    title: "The Twelve Caesars",
    author: "Suetonius",
    authorBio: "Roman biographer and personal secretary to Emperor Hadrian whose candid imperial biographies preserved invaluable cultural history and court anecdotes.",
    year: 121,
    pages: 460,
    audience: "teen",
    coverId: "8232299",
    description: "Candid, fascinating biographies of Rome's first twelve leaders from Julius Caesar through Domitian, detailing physical appearance, quirks, and court scandals.",
    curatorNote: "The most entertaining and intimate primary source on the personal lives of Roman emperors.",
    gutenbergId: "6400",
    openLibraryWorkId: "OL21876W",
    subjects: ["History & Life", "Twelve Caesars", "Roman Emperors", "Suetonius", "Imperial Anecdotes"]
  },
  {
    title: "The Jewish War",
    author: "Flavius Josephus",
    authorBio: "First-century Romano-Jewish historian and general whose eyewitness accounts recorded the Great Jewish Revolt and destruction of Jerusalem.",
    year: 75,
    pages: 580,
    audience: "adult",
    coverId: "8232300",
    description: "A harrowing eyewitness chronicle of the Jewish revolt against Rome, culminating in the siege of Jerusalem, destruction of the Second Temple, and Masada.",
    curatorNote: "The indispensable primary source for Judean history and the fall of the Second Temple in 70 AD.",
    gutenbergId: "2850",
    openLibraryWorkId: "OL21877W",
    subjects: ["History & Life", "Jewish Revolt", "Siege of Jerusalem", "Masada", "Second Temple"]
  },
  {
    title: "Antiquities of the Jews",
    author: "Flavius Josephus",
    authorBio: "First-century Romano-Jewish historian and general whose eyewitness accounts recorded the Great Jewish Revolt and destruction of Jerusalem.",
    year: 94,
    pages: 780,
    audience: "adult",
    coverId: "8232301",
    description: "A monumental twenty-book history of the Jewish people from the creation of the world to the outbreak of the Roman war, written for Greco-Roman readers.",
    curatorNote: "A massive historical achievement preserving Jewish heritage and ancient Mediterranean history.",
    gutenbergId: "2848",
    openLibraryWorkId: "OL21878W",
    subjects: ["History & Life", "Jewish History", "Biblical Antiquity", "Josephus", "Monumental History"]
  },
  {
    title: "The Histories of Polybius",
    author: "Polybius",
    authorBio: "Greek historian captured by Rome whose 40-book history explained the rise of the Roman Republic and its unique mixed constitutional system.",
    year: -146,
    pages: 620,
    audience: "adult",
    coverId: "8232302",
    description: "Polybius analyzes how Rome conquered the Mediterranean world in just fifty-three years through its mixed constitution, military discipline, and checks and balances.",
    curatorNote: "The seminal analysis of constitutional checks and balances that directly inspired the US Constitution.",
    gutenbergId: "65029",
    openLibraryWorkId: "OL21879W",
    subjects: ["History & Life", "Roman Republic", "Mixed Constitution", "Punic Wars", "Hannibal"]
  },
  {
    title: "The History of Rome",
    subtitle: "Ab Urbe Condita",
    author: "Livy",
    authorBio: "Monumental Roman historian who chronicled the legendary founding of Rome through the reign of Augustus in 142 majestic books.",
    year: -9,
    pages: 750,
    audience: "teen",
    coverId: "8232303",
    description: "Livy's sweeping narrative of Rome from Romulus and Remus, the expulsion of the Tarquins, the battle of Cannae, and Scipio's triumph over Hannibal.",
    curatorNote: "The epic prose monument celebrating Roman civic duty, martial courage, and founding legends.",
    gutenbergId: "19725",
    openLibraryWorkId: "OL21880W",
    subjects: ["History & Life", "Founding of Rome", "Hannibal Barca", "Scipio Africanus", "Livy"]
  },
  {
    title: "Decline and Fall of the Roman Empire (Vol 1)",
    author: "Edward Gibbon",
    authorBio: "English historian and parliamentarian whose six-volume masterpiece set the standard for modern Western narrative historical scholarship.",
    year: 1776,
    pages: 640,
    audience: "adult",
    coverId: "8232304",
    description: "From the Age of the Antonines through Commodus, the crisis of the third century, and Constantine's conversion and founding of Constantinople.",
    curatorNote: "The greatest prose history in the English language, written with majestic irony and erudition.",
    gutenbergId: "25717",
    openLibraryWorkId: "OL10701W",
    subjects: ["History & Life", "Roman Empire", "Edward Gibbon", "Age of Antonines", "Constantine"]
  },
  {
    title: "Decline and Fall of the Roman Empire (Vol 2)",
    author: "Edward Gibbon",
    authorBio: "English historian and parliamentarian whose six-volume masterpiece set the standard for modern Western narrative historical scholarship.",
    year: 1781,
    pages: 680,
    audience: "adult",
    coverId: "8232305",
    description: "Chronicles Julian the Apostate's attempt to restore paganism, barbarian invasions across the Rhine and Danube, and the Goths sacking Rome in 410 AD.",
    curatorNote: "Dazzling narrative of Alaric, Attila the Hun, and the fall of the Western Roman provinces.",
    gutenbergId: "25718",
    openLibraryWorkId: "OL10702W",
    subjects: ["History & Life", "Barbarian Invasions", "Alaric", "Attila the Hun", "Sack of Rome"]
  },
  {
    title: "Decline and Fall of the Roman Empire (Vol 3)",
    author: "Edward Gibbon",
    authorBio: "English historian and parliamentarian whose six-volume masterpiece set the standard for modern Western narrative historical scholarship.",
    year: 1788,
    pages: 720,
    audience: "adult",
    coverId: "8232306",
    description: "Justinian's reconquest, the rise of Islam, the Crusades, and the climactic Ottoman siege and fall of Constantinople in 1453.",
    curatorNote: "The monumental conclusion to Gibbon's epic, linking antiquity directly to the modern world.",
    gutenbergId: "25719",
    openLibraryWorkId: "OL10703W",
    subjects: ["History & Life", "Byzantine Empire", "Fall of Constantinople", "Ottoman Siege", "Justinian"]
  },
  {
    title: "The History of England",
    author: "Thomas Babington Macaulay",
    authorBio: "British historian, essayist, and Whig politician whose five-volume history became a sensational Victorian bestseller.",
    year: 1848,
    pages: 620,
    audience: "adult",
    coverId: "8232307",
    description: "A sparkling, vivid narrative of the Glorious Revolution of 1688, the deposition of James II, and the establishment of constitutional parliamentary monarchy under William and Mary.",
    curatorNote: "The supreme exemplar of the Whig interpretation of history, written with cinematic narrative energy.",
    gutenbergId: "1468",
    openLibraryWorkId: "OL10704W",
    subjects: ["History & Life", "Glorious Revolution", "English History", "Constitutional Monarchy", "Macaulay"]
  },
  {
    title: "The French Revolution: A History",
    author: "Thomas Carlyle",
    authorBio: "Scottish essayist, historian, and philosopher whose fiery prose and Great Man theory transformed Victorian historical perspective.",
    year: 1837,
    pages: 820,
    audience: "adult",
    coverId: "8232308",
    description: "A passionate, prose-poetic epic recreating the storming of the Bastille, the guillotine Reign of Terror, Robespierre, and the rise of Napoleon.",
    curatorNote: "Charles Dickens kept this book on his desk as primary inspiration while writing A Tale of Two Cities.",
    gutenbergId: "1301",
    openLibraryWorkId: "OL10705W",
    subjects: ["History & Life", "French Revolution", "Storming of Bastille", "Reign of Terror", "Robespierre"]
  },
  {
    title: "On Heroes and Hero-Worship",
    author: "Thomas Carlyle",
    authorBio: "Scottish essayist, historian, and philosopher whose fiery prose and Great Man theory transformed Victorian historical perspective.",
    year: 1841,
    pages: 280,
    audience: "adult",
    coverId: "8232309",
    description: "Carlyle examines the hero across six avatars: the Hero as Divinity (Odin), Prophet (Muhammad), Poet (Dante, Shakespeare), Priest (Luther), Man of Letters (Johnson, Rousseau), and King (Cromwell, Napoleon).",
    curatorNote: "The definitive exposition of the Great Man theory of history and charismatic leadership.",
    gutenbergId: "1091",
    openLibraryWorkId: "OL10706W",
    subjects: ["History & Life", "Great Man Theory", "Heroism", "Leadership History", "Carlyle"]
  },
  {
    title: "The Oregon Trail",
    author: "Francis Parkman",
    authorBio: "American historian who lived among the Oglala Sioux and traveled the frontier before writing his classic histories of early America.",
    year: 1849,
    pages: 390,
    audience: "teen",
    coverId: "8232310",
    description: "Parkman's firsthand 1846 journey along the Oregon Trail, hunting buffalo on the Great Plains and dwelling in Sioux encampments in the Black Hills.",
    curatorNote: "An invaluable eyewitness snapshot of the American frontier just before the gold rush transformed it.",
    gutenbergId: "1078",
    openLibraryWorkId: "OL10707W",
    subjects: ["History & Life", "Oregon Trail", "American Frontier", "Sioux Nation", "Buffalo Hunt"]
  },
  {
    title: "The Conspiracy of Pontiac",
    author: "Francis Parkman",
    authorBio: "American historian who lived among the Oglala Sioux and traveled the frontier before writing his classic histories of early America.",
    year: 1851,
    pages: 580,
    audience: "adult",
    coverId: "8232311",
    description: "The uprising of Native American tribes led by Ottawa chief Pontiac against British rule in the Great Lakes region following the French and Indian War.",
    curatorNote: "Parkman's gripping, deeply researched epic of indigenous resistance in colonial America.",
    gutenbergId: "13511",
    openLibraryWorkId: "OL10708W",
    subjects: ["History & Life", "Chief Pontiac", "Great Lakes", "Colonial America", "Frontier Warfare"]
  },
  {
    title: "Democracy in America (Volume 1)",
    author: "Alexis de Tocqueville",
    authorBio: "French political scientist, historian, and philosopher who analyzed American democratic institutions and equality in his classic study.",
    year: 1835,
    pages: 520,
    audience: "adult",
    coverId: "8232312",
    description: "Tocqueville's brilliant analysis of the American constitutional framework, township democracy, judicial review, the press, and the danger of the 'tyranny of the majority'.",
    curatorNote: "The most profound and perceptive foreign analysis of American democratic culture ever written.",
    gutenbergId: "815",
    openLibraryWorkId: "OL10709W",
    subjects: ["History & Life", "Democracy in America", "Township Governance", "Tyranny of Majority", "Tocqueville"]
  },
  {
    title: "Democracy in America (Volume 2)",
    author: "Alexis de Tocqueville",
    authorBio: "French political scientist, historian, and philosopher who analyzed American democratic institutions and equality in his classic study.",
    year: 1840,
    pages: 480,
    audience: "adult",
    coverId: "8232313",
    description: "How equality of conditions impacts philosophy, religion, science, arts, women, family life, and warns against modern bureaucratic soft despotism.",
    curatorNote: "Visionary prophecies on mass society, individualism, and bureaucratic centralism.",
    gutenbergId: "816",
    openLibraryWorkId: "OL10710W",
    subjects: ["History & Life", "Individualism", "Democratic Culture", "Soft Despotism", "Sociology"]
  },
  {
    title: "The Old Regime and the Revolution",
    author: "Alexis de Tocqueville",
    authorBio: "French political scientist, historian, and philosopher who analyzed American democratic institutions and equality in his classic study.",
    year: 1856,
    pages: 320,
    audience: "adult",
    coverId: "8232314",
    description: "Tocqueville reveals that the French Revolution was not a radical clean break, but the culmination of administrative centralisation begun under the Bourbon monarchy.",
    curatorNote: "A landmark sociological history demonstrating the roots of modern state centralization.",
    gutenbergId: "65030",
    openLibraryWorkId: "OL10711W",
    subjects: ["History & Life", "French Revolution", "Old Regime", "Centralization", "Political Sociology"]
  },
  {
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    authorBio: "Abolitionist leader, orator, writer, and former enslaved American whose autobiographies mobilized world opinion against slavery.",
    year: 1845,
    pages: 140,
    audience: "all",
    coverId: "8231996",
    description: "Douglass's searing firsthand account of growing up enslaved in Maryland, learning to read, physically confronting slavebreaker Covey, and escaping to freedom.",
    curatorNote: "A monumental American classic that proved literacy is the indispensable path to freedom.",
    gutenbergId: "23",
    openLibraryWorkId: "OL10712W",
    subjects: ["History & Life", "Frederick Douglass", "Abolition", "Slave Narrative", "American Classic"]
  },
  {
    title: "My Bondage and My Freedom",
    author: "Frederick Douglass",
    authorBio: "Abolitionist leader, orator, writer, and former enslaved American whose autobiographies mobilized world opinion against slavery.",
    year: 1855,
    pages: 460,
    audience: "teen",
    coverId: "8232315",
    description: "The expanded, mature second autobiography of Douglass, detailing his international abolitionist lecture tours in Britain, founding his newspaper, and intellectual independence.",
    curatorNote: "Douglass's deeper political analysis of racial oppression, international abolition, and self-made dignity.",
    gutenbergId: "248",
    openLibraryWorkId: "OL10713W",
    subjects: ["History & Life", "Abolitionist Movement", "Civil Rights", "Oratory", "Frederick Douglass"]
  },
  {
    title: "The Autobiography of Benjamin Franklin",
    author: "Benjamin Franklin",
    authorBio: "American Founding Father, polymath, inventor, scientist, printer, and diplomat who shaped the culture of the American Enlightenment.",
    year: 1791,
    pages: 230,
    audience: "all",
    coverId: "8232316",
    description: "Franklin's charming memoir of arriving penniless in Philadelphia, founding civic institutions, conducting electrical experiments, and his thirteen virtues.",
    curatorNote: "The founding text of the American self-made man and practical Enlightenment ethics.",
    gutenbergId: "20203",
    openLibraryWorkId: "OL10714W",
    subjects: ["History & Life", "Benjamin Franklin", "Founding Fathers", "Self-Made Man", "13 Virtues"]
  },
  {
    title: "Personal Memoirs of U.S. Grant",
    author: "Ulysses S. Grant",
    authorBio: "Commanding General of the Union Army during the American Civil War and 18th President of the United States.",
    year: 1885,
    pages: 720,
    audience: "teen",
    coverId: "8232317",
    description: "Written while dying of throat cancer to support his family, Grant recounts the Mexican-American War, Vicksburg, and the defeat of Robert E. Lee with unvarnished clarity.",
    curatorNote: "Mark Twain called it the greatest military memoir since Julius Caesar's Commentaries.",
    gutenbergId: "4367",
    openLibraryWorkId: "OL10715W",
    subjects: ["History & Life", "Ulysses S Grant", "American Civil War", "Military Strategy", "Vicksburg"]
  },
  {
    title: "The Life of Samuel Johnson",
    author: "James Boswell",
    authorBio: "Scottish biographer and lawyer whose intimate, exhaustive portrait of lexicographer Dr. Samuel Johnson redefined the biographical genre.",
    year: 1791,
    pages: 940,
    audience: "adult",
    coverId: "8232318",
    description: "Boswell's magnificent biography capturing Dr. Johnson's brilliant tavern conversation, moral wisdom, literary struggles, and towering personality over decades.",
    curatorNote: "Widely regarded as the greatest biography ever written in the English language.",
    gutenbergId: "1564",
    openLibraryWorkId: "OL10716W",
    subjects: ["History & Life", "Samuel Johnson", "James Boswell", "Literary Biography", "18th Century London"]
  },
  {
    title: "The Life of Olaudah Equiano",
    author: "Olaudah Equiano",
    authorBio: "African writer, merchant, and abolitionist whose autobiography opened European eyes to the horrors of the Middle Passage and transatlantic slave trade.",
    year: 1789,
    pages: 280,
    audience: "teen",
    coverId: "8232319",
    description: "Equiano narrates his childhood in Igbo land, surviving the transatlantic Middle Passage, serving aboard Royal Navy ships, purchasing his freedom, and lobbying for abolition.",
    curatorNote: "The foundational African narrative of transatlantic enslavement and abolitionist activism.",
    gutenbergId: "15399",
    openLibraryWorkId: "OL10717W",
    subjects: ["History & Life", "Olaudah Equiano", "Middle Passage", "Slave Trade Abolition", "Igbo Heritage"]
  },
  {
    title: "Incidents in the Life of a Slave Girl",
    author: "Harriet Jacobs",
    authorBio: "African-American writer and abolitionist who hid for seven years in a tiny attic crawlspace to escape sexual exploitation before reaching freedom.",
    year: 1861,
    pages: 310,
    audience: "adult",
    coverId: "8232320",
    description: "Jacobs' autobiographical testimony of resisting sexual abuse from her enslaver, hiding for seven years in a three-foot attic space, and rescuing her children.",
    curatorNote: "A heroic, harrowing landmark documenting the specific horrors inflicted upon enslaved women.",
    gutenbergId: "11030",
    openLibraryWorkId: "OL10718W",
    subjects: ["History & Life", "Harriet Jacobs", "Enslaved Women", "Attic Sanctuary", "Abolition"]
  },
  {
    title: "Up from Slavery",
    author: "Booker T. Washington",
    authorBio: "American educator, author, and orator who rose from enslavement to establish the Tuskegee Institute and lead educational advancement.",
    year: 1901,
    pages: 280,
    audience: "all",
    coverId: "8232321",
    description: "Washington's inspirational journey from an impoverished slave cabin in Virginia to founding Tuskegee Institute and championing industrial education.",
    curatorNote: "An uplifting classic of perseverance, dignity of labor, and community institution-building.",
    gutenbergId: "2376",
    openLibraryWorkId: "OL10719W",
    subjects: ["History & Life", "Booker T Washington", "Tuskegee Institute", "Industrial Education", "Perseverance"]
  },
  {
    title: "The Souls of Black Folk",
    author: "W.E.B. Du Bois",
    authorBio: "American sociologist, historian, civil rights activist, and co-founder of the NAACP whose seminal work introduced the concept of double consciousness.",
    year: 1903,
    pages: 270,
    audience: "teen",
    coverId: "8232322",
    description: "Fourteen essays examining the Veil of race, the color-line, the Sorrow Songs, and 'double-consciousness'—measuring oneself through the eyes of an exclusionary world.",
    curatorNote: "The seminal foundational masterpiece of African-American sociology, history, and civil rights.",
    gutenbergId: "408",
    openLibraryWorkId: "OL10720W",
    subjects: ["History & Life", "Double Consciousness", "WEB Du Bois", "Civil Rights", "The Veil"]
  },
  {
    title: "Twelve Years a Slave",
    author: "Solomon Northup",
    authorBio: "Free African-American violinist from New York who was kidnapped in Washington D.C. in 1841 and sold into Louisiana plantation slavery for twelve years.",
    year: 1853,
    pages: 330,
    audience: "teen",
    coverId: "8232323",
    description: "Northup's detailed memoir of being drugged, kidnapped into Southern bondage, surviving brutal cotton plantations on the Red River, and his dramatic legal rescue.",
    curatorNote: "An extraordinary, meticulous historical document capturing the harrowing reality of plantation slavery.",
    gutenbergId: "45631",
    openLibraryWorkId: "OL10721W",
    subjects: ["History & Life", "Solomon Northup", "Kidnapping", "Red River Plantations", "Freedom"]
  },
  {
    title: "The Confessions of Saint Augustine",
    author: "Saint Augustine",
    authorBio: "Bishop of Hippo, theologian, and philosopher whose spiritual autobiography invented Western introspective psychological self-examination.",
    year: 397,
    pages: 420,
    audience: "adult",
    coverId: "8232324",
    description: "Augustine's spiritual autobiography addressing God directly, tracing his youth in North Africa, philosophical wandering through Manichaeism, and garden conversion.",
    curatorNote: "The founding text of Western introspective autobiography and spiritual philosophy.",
    gutenbergId: "3296",
    openLibraryWorkId: "OL10722W",
    subjects: ["History & Life", "Saint Augustine", "Confessions", "Spiritual Conversion", "Christian Philosophy"]
  },
  {
    title: "The Confessions of Rousseau",
    author: "Jean-Jacques Rousseau",
    authorBio: "Genevan philosopher whose completely candid personal confessions set the modern benchmark for autobiographical self-revelation.",
    year: 1782,
    pages: 620,
    audience: "adult",
    coverId: "8232325",
    description: "Rousseau vows to depict himself with complete, unflinching honesty—virtues, shameful secrets, sexual awakening, and persecution mania alike.",
    curatorNote: "The groundbreaking precursor of modern psychological and confessional autobiography.",
    gutenbergId: "3913",
    openLibraryWorkId: "OL10723W",
    subjects: ["History & Life", "Rousseau", "Confessional Memoir", "Romantic Self", "Psychological Honesty"]
  },
  {
    title: "Poetry and Truth",
    subtitle: "From My Life",
    author: "Johann Wolfgang von Goethe",
    authorBio: "Germany's greatest literary figure, poet, novelist, and polymath whose autobiography captured the intellectual dawn of European Romanticism.",
    year: 1811,
    pages: 650,
    audience: "adult",
    coverId: "8232326",
    description: "Goethe recounts his Frankfurt childhood, university studies in Leipzig and Strasbourg, early loves, and the Sturm und Drang explosion of young Werther.",
    curatorNote: "A majestic panorama of European cultural and artistic flourishing in the late 18th century.",
    gutenbergId: "5300",
    openLibraryWorkId: "OL10724W",
    subjects: ["History & Life", "Goethe", "Sturm und Drang", "Frankfurt", "German Literature"]
  },
  {
    title: "Autobiography of Benvenuto Cellini",
    author: "Benvenuto Cellini",
    authorBio: "Florentine Renaissance sculptor, goldsmith, and adventurer whose boastful memoir captures the vibrant, dangerous energy of the 16th century.",
    year: 1563,
    pages: 450,
    audience: "teen",
    coverId: "8232327",
    description: "Cellini's swashbuckling memoir of duels, prison escapes from Castel Sant'Angelo, casting the bronze statue of Perseus, and serving popes and kings.",
    curatorNote: "A roaring, vivid window into the artistic genius, swagger, and perils of Renaissance Italy.",
    gutenbergId: "4028",
    openLibraryWorkId: "OL10725W",
    subjects: ["History & Life", "Benvenuto Cellini", "Italian Renaissance", "Bronze Casting", "Castel Sant'Angelo"]
  },
  {
    title: "The Story of My Life",
    author: "Giacomo Casanova",
    authorBio: "Venetian adventurer, author, and diplomat whose sweeping twelve-volume memoirs provide the definitive chronicle of 18th-century European court society.",
    year: 1798,
    pages: 580,
    audience: "adult",
    coverId: "8232328",
    description: "Casanova's memoirs spanning daring escapes from the Doge's Palace Leads prison, encounters with Voltaire, Catherine the Great, and countless romantic intrigues.",
    curatorNote: "An incomparable historical portrait of European Enlightenment courts, theaters, and salons.",
    gutenbergId: "2981",
    openLibraryWorkId: "OL10726W",
    subjects: ["History & Life", "Casanova", "Venice", "European Courts", "18th Century Memoir"]
  },
  {
    title: "The Autobiography of Charles Darwin",
    author: "Charles Darwin",
    authorBio: "English naturalist whose theory of evolution by natural selection permanently transformed scientific understanding of life on Earth.",
    year: 1887,
    pages: 160,
    audience: "all",
    coverId: "8232329",
    description: "Written for his children, Darwin reflects with modest charm on his youth, the Beagle voyage, formulating natural selection, and scientific method.",
    curatorNote: "A gentle, inspiring glimpse into the intellectual habits of one of history's greatest scientists.",
    gutenbergId: "2010",
    openLibraryWorkId: "OL10727W",
    subjects: ["History & Life", "Charles Darwin", "Evolution", "Scientific Method", "Naturalist Life"]
  },
  {
    title: "Apologia Pro Vita Sua",
    author: "John Henry Newman",
    authorBio: "English theologian, cardinal, and poet whose defense of his spiritual opinions and conversion to Catholicism became a classic of religious prose.",
    year: 1864,
    pages: 390,
    audience: "adult",
    coverId: "8232330",
    description: "Cardinal Newman's defense of his religious integrity and intellectual journey from Oxford Movement Anglicanism to the Catholic Church.",
    curatorNote: "A masterpiece of spiritual autobiography and subtle theological argumentation.",
    gutenbergId: "4928",
    openLibraryWorkId: "OL10728W",
    subjects: ["History & Life", "John Henry Newman", "Oxford Movement", "Spiritual Autobiography", "Theology"]
  },
  {
    title: "Autobiography of John Stuart Mill",
    author: "John Stuart Mill",
    authorBio: "British philosopher, political economist, and MP who advocated utilitarianism, individual liberty, and women's rights.",
    year: 1873,
    pages: 260,
    audience: "adult",
    coverId: "8232331",
    description: "Mill describes his extraordinary childhood education in Greek and calculus under his father James Mill, his twenties mental crisis, and emotional rebirth through poetry.",
    curatorNote: "A classic study of intellectual prodigy, mental breakdown, and the humanizing power of art.",
    gutenbergId: "10378",
    openLibraryWorkId: "OL10729W",
    subjects: ["History & Life", "John Stuart Mill", "Prodigy Education", "Utilitarianism", "Intellectual Rebirth"]
  },
  {
    title: "Memoirs of the Duc de Saint-Simon",
    author: "Louis de Rouvroy, Duc de Saint-Simon",
    authorBio: "French soldier, diplomat, and memoirist who documented the court of Louis XIV at Versailles with peerless psychological detail.",
    year: 1788,
    pages: 580,
    audience: "adult",
    coverId: "8232332",
    description: "An insider's psychological portrait of the Sun King's court at Versailles, observing the rituals, intrigues, jealousies, and decay of the French monarchy.",
    curatorNote: "The supreme primary source on the court etiquette, politics, and personalities of Versailles.",
    gutenbergId: "3875",
    openLibraryWorkId: "OL10730W",
    subjects: ["History & Life", "Versailles", "Louis XIV", "French Court", "Saint-Simon"]
  },
  {
    title: "The Prince",
    author: "Niccolò Machiavelli",
    authorBio: "Florentine diplomat, political philosopher, and writer whose realistic treatise on power politics established modern political science.",
    year: 1532,
    pages: 140,
    audience: "adult",
    coverId: "12726168",
    description: "Machiavelli advises rulers on acquiring and maintaining political power, asserting that princes must learn how not to be good when political necessity demands.",
    curatorNote: "The foundational text of political realism that shook Western moral philosophy to its foundations.",
    gutenbergId: "1232",
    openLibraryWorkId: "OL10731W",
    subjects: ["History & Life", "Machiavelli", "Political Realism", "The Prince", "Statecraft"]
  },
  {
    title: "Discourses on Livy",
    author: "Niccolò Machiavelli",
    authorBio: "Florentine diplomat, political philosopher, and writer whose realistic treatise on power politics established modern political science.",
    year: 1531,
    pages: 440,
    audience: "adult",
    coverId: "8232333",
    description: "Machiavelli's republican masterpiece analyzing the Roman Republic to discover how free citizen commonwealths can maintain liberty and prevent corruption.",
    curatorNote: "The essential republican counterpart to The Prince, celebrating civic liberty and citizen armies.",
    gutenbergId: "10827",
    openLibraryWorkId: "OL10732W",
    subjects: ["History & Life", "Republicanism", "Civic Liberty", "Roman Republic", "Discourses"]
  },
  {
    title: "The History of the Conquest of Mexico",
    author: "William H. Prescott",
    authorBio: "American historian who, despite near-blindness, created monumental, pioneering literary histories of the Spanish conquests in the Americas.",
    year: 1843,
    pages: 720,
    audience: "teen",
    coverId: "8232334",
    description: "Prescott's sweeping historical epic of Hernando Cortés leading five hundred conquistadors into the heart of the Aztec Empire and Tenochtitlan.",
    curatorNote: "A towering literary history that brought the Aztec world and Spanish clash to life worldwide.",
    gutenbergId: "2445",
    openLibraryWorkId: "OL10733W",
    subjects: ["History & Life", "Conquest of Mexico", "Aztec Empire", "Cortes", "Tenochtitlan"]
  }
];
