module.exports = [
  {
    title: "The Iliad",
    author: "Homer",
    authorBio: "Legendary ancient Greek poet of Ionia credited with composing the Iliad and Odyssey, the twin foundational epics of Western literature.",
    year: -750,
    pages: 560,
    audience: "all",
    coverId: "8232385",
    description: "The wrath of Achilles during the final weeks of the Trojan War, culminating in the duel between Achilles and Trojan prince Hector.",
    curatorNote: "The fountainhead of Western epic poetry, exploring honor, mortality, and the tragic waste of war.",
    gutenbergId: "6130",
    openLibraryWorkId: "OL10603W",
    subjects: ["Poetry & Epics", "Homer", "Trojan War", "Achilles", "Heroic Epic"]
  },
  {
    title: "The Odyssey",
    author: "Homer",
    authorBio: "Legendary ancient Greek poet of Ionia credited with composing the Iliad and Odyssey, the twin foundational epics of Western literature.",
    year: -725,
    pages: 540,
    audience: "all",
    coverId: "9045853",
    description: "The ten-year wanderings of Odysseus returning home from Troy, overcoming the Cyclops Polyphemus, Circe, the Sirens, and slaying the insolent suitors in Ithaca.",
    curatorNote: "The supreme maritime odyssey of world storytelling: cunning, perseverance, and homecoming.",
    gutenbergId: "1727",
    openLibraryWorkId: "OL10604W",
    subjects: ["Poetry & Epics", "Odysseus", "Cyclops", "Penelope", "Ancient Greek Epic"]
  },
  {
    title: "The Aeneid",
    author: "Virgil",
    authorBio: "Rome's greatest classical poet whose twelve-book hexameter epic celebrated the founding of the Roman race through Trojan hero Aeneas.",
    year: -19,
    pages: 440,
    audience: "teen",
    coverId: "8232386",
    description: "Trojan prince Aeneas escapes the burning ruins of Troy, weathers shipwreck with Queen Dido in Carthage, descends to the Underworld, and settles in Italy.",
    curatorNote: "Rome's national epic: majestic Latin hexameters meditating on duty (pietas), sacrifice, and empire.",
    gutenbergId: "228",
    openLibraryWorkId: "OL10605W",
    subjects: ["Poetry & Epics", "Virgil", "Aeneas", "Dido of Carthage", "Founding of Rome"]
  },
  {
    title: "Georgics and Eclogues",
    author: "Virgil",
    authorBio: "Rome's greatest classical poet whose pastoral poetry celebrated rural agriculture, beekeeping, and pastoral serenity.",
    year: -29,
    pages: 200,
    audience: "all",
    coverId: "8232387",
    description: "Virgil's pastoral songs and agricultural poems celebrating crop rotation, arboriculture, cattle, and the social harmony of beekeeping.",
    curatorNote: "The summit of classical pastoral poetry honoring the sacred rhythm of nature and rural labor.",
    gutenbergId: "230",
    openLibraryWorkId: "OL10606W",
    subjects: ["Poetry & Epics", "Pastoral Poetry", "Agriculture", "Beekeeping", "Roman Verse"]
  },
  {
    title: "Metamorphoses",
    author: "Ovid",
    authorBio: "Roman poet of the Augustan age whose fifteen books preserved classical Greek and Roman myths through themes of constant transformation.",
    year: 8,
    pages: 580,
    audience: "teen",
    coverId: "8232388",
    description: "Over 250 classical myths of physical and emotional transformation, including Apollo and Daphne, Daedalus and Icarus, Pygmalion, and Narcissus.",
    curatorNote: "The supreme repository of classical mythology that nourished Western art, poetry, and sculpture.",
    gutenbergId: "21765",
    openLibraryWorkId: "OL10607W",
    subjects: ["Poetry & Epics", "Ovid", "Classical Mythology", "Metamorphosis", "Greek Myths"]
  },
  {
    title: "The Divine Comedy: Inferno",
    author: "Dante Alighieri",
    authorBio: "Italian poet of Florence whose three-part Christian epic established the modern Italian literary language and mapped medieval theology.",
    year: 1320,
    pages: 320,
    audience: "adult",
    coverId: "8232389",
    description: "Guided by the Roman poet Virgil, Dante journeys through the nine descending circles of Hell, witnessing the contrapasso punishments of sinners.",
    curatorNote: "The architectural pinnacle of medieval world literature, moral cosmology, and visionary poetry.",
    gutenbergId: "8800",
    openLibraryWorkId: "OL10608W",
    subjects: ["Poetry & Epics", "Dante", "Inferno", "Nine Circles of Hell", "Virgil"]
  },
  {
    title: "The Divine Comedy: Purgatorio",
    author: "Dante Alighieri",
    authorBio: "Italian poet of Florence whose three-part Christian epic established the modern Italian literary language and mapped medieval theology.",
    year: 1320,
    pages: 320,
    audience: "adult",
    coverId: "8232390",
    description: "Dante and Virgil ascend the seven terraces of Mount Purgatory, where penitent souls purge the seven deadly sins through prayer, art, and love.",
    curatorNote: "The most human and psychologically touching cantica of Dante's Comedy, filled with dawn and hope.",
    gutenbergId: "8801",
    openLibraryWorkId: "OL10609W",
    subjects: ["Poetry & Epics", "Purgatorio", "Mount Purgatory", "Seven Sins", "Dante"]
  },
  {
    title: "The Divine Comedy: Paradiso",
    author: "Dante Alighieri",
    authorBio: "Italian poet of Florence whose three-part Christian epic established the modern Italian literary language and mapped medieval theology.",
    year: 1320,
    pages: 340,
    audience: "adult",
    coverId: "8232391",
    description: "Guided by his beloved Beatrice, Dante ascends through the celestial heavenly spheres, culminating in the vision of the divine Love that moves the sun and other stars.",
    curatorNote: "The sublime, radiant conclusion: 'L'amor che move il sole e l'altre stelle.'",
    gutenbergId: "8802",
    openLibraryWorkId: "OL10610W",
    subjects: ["Poetry & Epics", "Paradiso", "Beatrice", "Celestial Spheres", "Divine Love"]
  },
  {
    title: "La Vita Nuova",
    author: "Dante Alighieri",
    authorBio: "Italian poet of Florence whose three-part Christian epic established the modern Italian literary language and mapped medieval theology.",
    year: 1294,
    pages: 120,
    audience: "teen",
    coverId: "8232392",
    description: "A prosimetrum of alternating sonnets and prose commentaries celebrating Dante's courtly spiritual love for Beatrice Portinari from youth to her death.",
    curatorNote: "The exquisite dawn of Dante's poetic genius that set the stage for the Divine Comedy.",
    gutenbergId: "41085",
    openLibraryWorkId: "OL10611W",
    subjects: ["Poetry & Epics", "Courtly Love", "Beatrice Portinari", "Sonnets", "Early Dante"]
  },
  {
    title: "Paradise Lost",
    author: "John Milton",
    authorBio: "English poet, polemicist, and civil servant whose monumental blank verse epic justified the ways of God to men.",
    year: 1667,
    pages: 450,
    audience: "adult",
    coverId: "8232393",
    description: "Satan's rebellion and expulsion from Heaven into Pandemonium, leading to the temptation of Adam and Eve in Eden and the Fall of mankind.",
    curatorNote: "The greatest epic poem in the English language, filled with towering rhetoric and cosmic grandeur.",
    gutenbergId: "20",
    openLibraryWorkId: "OL10612W",
    subjects: ["Poetry & Epics", "John Milton", "Paradise Lost", "Satan", "Garden of Eden"]
  },
  {
    title: "Paradise Regained",
    author: "John Milton",
    authorBio: "English poet, polemicist, and civil servant whose monumental blank verse epic justified the ways of God to men.",
    year: 1671,
    pages: 140,
    audience: "adult",
    coverId: "8232394",
    description: "Milton's four-book companion epic depicting Christ's temptation by Satan in the wilderness, conquering temptation through quiet spiritual fortitude.",
    curatorNote: "A masterclass in dialectical moral reasoning, philosophical austerity, and spiritual discipline.",
    gutenbergId: "58",
    openLibraryWorkId: "OL10613W",
    subjects: ["Poetry & Epics", "Milton", "Temptation in Wilderness", "Spiritual Fortitude", "Blank Verse"]
  },
  {
    title: "Samson Agonistes",
    author: "John Milton",
    authorBio: "English poet, polemicist, and civil servant whose monumental blank verse epic justified the ways of God to men.",
    year: 1671,
    pages: 110,
    audience: "adult",
    coverId: "8232395",
    description: "A classical Greek-style verse tragedy depicting the blinded biblical champion Samson in Philistine captivity at Gaza, bringing down the temple pillars.",
    curatorNote: "Milton's deeply personal poetic reflection on blindness, defeat, and ultimate spiritual vindication.",
    gutenbergId: "65031",
    openLibraryWorkId: "OL10614W",
    subjects: ["Poetry & Epics", "Samson Agonistes", "Verse Tragedy", "Blindness", "Biblical Epic"]
  },
  {
    title: "The Canterbury Tales",
    author: "Geoffrey Chaucer",
    authorBio: "Father of English poetry whose collection of pilgrim stories established Middle English as a rich literary medium.",
    year: 1400,
    pages: 580,
    audience: "teen",
    coverId: "8232396",
    description: "A diverse company of medieval pilgrims traveling to Canterbury Cathedral share stories ranging from chivalric romance to bawdy fabliaux at the Tabard Inn.",
    curatorNote: "The vibrant, immortal portrait of medieval English society, humanity, wit, and dialogue.",
    gutenbergId: "2383",
    openLibraryWorkId: "OL10615W",
    subjects: ["Poetry & Epics", "Chaucer", "Canterbury Pilgrims", "Wife of Bath", "Middle English"]
  },
  {
    title: "Troilus and Criseyde",
    author: "Geoffrey Chaucer",
    authorBio: "Father of English poetry whose collection of pilgrim stories established Middle English as a rich literary medium.",
    year: 1385,
    pages: 340,
    audience: "adult",
    coverId: "8232397",
    description: "Set during the siege of Troy, Trojan prince Troilus falls in love with Criseyde with help from Pandarus, but heartbreak follows when she is traded to the Greek camp.",
    curatorNote: "Widely regarded as Chaucer's greatest psychological and philosophical poetic achievement.",
    gutenbergId: "257",
    openLibraryWorkId: "OL10616W",
    subjects: ["Poetry & Epics", "Troilus and Criseyde", "Trojan Romance", "Chaucer", "Tragic Love"]
  },
  {
    title: "Beowulf",
    author: "Anonymous",
    authorBio: "Unknown Anglo-Saxon scop whose Old English alliterative masterpiece remains the oldest surviving epic poem in the English language.",
    year: 1000,
    pages: 160,
    audience: "all",
    coverId: "8232398",
    description: "Geatish warrior Beowulf sails to Denmark to defend King Hrothgar's mead-hall Heorot against the monster Grendel and his mother, later facing a dragon.",
    curatorNote: "The monumental foundation stone of English poetry, full of alliterative power and heroic elegies.",
    gutenbergId: "16328",
    openLibraryWorkId: "OL10617W",
    subjects: ["Poetry & Epics", "Old English", "Beowulf", "Grendel", "Anglo-Saxon Heroic"]
  },
  {
    title: "The Song of Roland",
    author: "Anonymous",
    authorBio: "Anonymous medieval French poet whose 11th-century chanson de geste celebrated the chivalric rearguard stand of Charlemagne's paladin Roland.",
    year: 1100,
    pages: 180,
    audience: "teen",
    coverId: "8232399",
    description: "Charlemagne's nephew Count Roland leads the rearguard at Roncevaux Pass, fighting heroically against Saracen forces and sounding his ivory horn Olifant.",
    curatorNote: "The supreme French medieval chanson de geste of chivalric honor, brotherhood, and tragic sacrifice.",
    gutenbergId: "391",
    openLibraryWorkId: "OL10618W",
    subjects: ["Poetry & Epics", "Chanson de Geste", "Charlemagne", "Count Roland", "Roncevaux"]
  },
  {
    title: "The Nibelungenlied",
    author: "Anonymous",
    authorBio: "Unknown Middle High German poet of the Danube region who codified the ancient Germanic epic of dragon-slayer Siegfried and Kriemhild.",
    year: 1200,
    pages: 320,
    audience: "teen",
    coverId: "8232400",
    description: "The heroic exploits and murder of dragon-slayer Siegfried, followed by his widow Kriemhild's apocalyptic vengeance against the Burgundian kings at Attila's court.",
    curatorNote: "The Germanic national epic of loyalty, betrayal, and catastrophic revenge that inspired Wagner.",
    gutenbergId: "7321",
    openLibraryWorkId: "OL10619W",
    subjects: ["Poetry & Epics", "Siegfried", "Nibelungenlied", "Kriemhild", "Germanic Epic"]
  },
  {
    title: "Sir Gawain and the Green Knight",
    author: "Anonymous",
    authorBio: "Unknown 14th-century Northwest Midlands poet whose Arthurian alliterative verse romance is celebrated for chivalric psychological complexity.",
    year: 1400,
    pages: 140,
    audience: "all",
    coverId: "8232401",
    description: "A gigantic Green Knight rides into Camelot challenging any knight to strike him with an axe and receive a blow in return one year later at the Green Chapel.",
    curatorNote: "A dazzling Arthurian gem of chivalric honor, temptation, and moral humility.",
    gutenbergId: "65032",
    openLibraryWorkId: "OL10620W",
    subjects: ["Poetry & Epics", "Sir Gawain", "Green Knight", "Arthurian Legend", "Alliterative Verse"]
  },
  {
    title: "Shakespeare's Sonnets",
    author: "William Shakespeare",
    authorBio: "English playwright and poet widely regarded as the greatest dramatist of all time and England's national poet.",
    year: 1609,
    pages: 190,
    audience: "teen",
    coverId: "8232402",
    description: "154 sonnets exploring love, beauty, the ravages of time, mortality, the Fair Youth, and the mysterious Dark Lady.",
    curatorNote: "The pinnacle of lyric poetry in the English language, containing 'Shall I compare thee to a summer's day?'.",
    gutenbergId: "1041",
    openLibraryWorkId: "OL10621W",
    subjects: ["Poetry & Epics", "Shakespeare", "Sonnets", "Fair Youth", "Dark Lady", "Love Poetry"]
  },
  {
    title: "Venus and Adonis",
    author: "William Shakespeare",
    authorBio: "English playwright and poet widely regarded as the greatest dramatist of all time and England's national poet.",
    year: 1593,
    pages: 90,
    audience: "adult",
    coverId: "8232403",
    description: "The goddess of love Venus passionately woos the reluctant, hunting-obsessed youth Adonis, leading to tragic disaster when he hunts a ferocious wild boar.",
    curatorNote: "Shakespeare's earliest published work: a sensual, sparkling Renaissance narrative poem.",
    gutenbergId: "1045",
    openLibraryWorkId: "OL10622W",
    subjects: ["Poetry & Epics", "Shakespeare", "Venus and Adonis", "Narrative Poetry", "Renaissance"]
  },
  {
    title: "The Rape of Lucrece",
    author: "William Shakespeare",
    authorBio: "English playwright and poet widely regarded as the greatest dramatist of all time and England's national poet.",
    year: 1594,
    pages: 110,
    audience: "adult",
    coverId: "8232404",
    description: "A dark, intense tragic narrative poem following Tarquin's assault on noble Roman matron Lucrece and the subsequent revolution that overthrew the Roman monarchy.",
    curatorNote: "A devastating psychological study of guilt, violated honor, and political revolution.",
    gutenbergId: "1042",
    openLibraryWorkId: "OL10623W",
    subjects: ["Poetry & Epics", "Shakespeare", "Lucrece", "Roman Monarchy", "Tragic Verse"]
  },
  {
    title: "Songs and Sonnets",
    author: "John Donne",
    authorBio: "English poet and cleric, the greatest of the Metaphysical poets, renowned for intellectual wit, startling conceits, and passionate intensity.",
    year: 1633,
    pages: 180,
    audience: "adult",
    coverId: "8232405",
    description: "Sensual, brilliant love lyrics including 'The Flea', 'The Good-Morrow', 'The Sun Rising', and 'A Valediction: Forbidding Mourning'.",
    curatorNote: "The peak of Metaphysical poetry: dazzling intellectual conceit fused with erotic passion.",
    gutenbergId: "4877",
    openLibraryWorkId: "OL10624W",
    subjects: ["Poetry & Epics", "John Donne", "Metaphysical Poetry", "Love Poems", "The Flea"]
  },
  {
    title: "Holy Sonnets",
    author: "John Donne",
    authorBio: "English poet and cleric, the greatest of the Metaphysical poets, renowned for intellectual wit, startling conceits, and passionate intensity.",
    year: 1633,
    pages: 70,
    audience: "teen",
    coverId: "8232406",
    description: "Nineteen intense religious sonnets wrestling with mortality, divine grace, judgment, and faith, featuring 'Death, be not proud' and 'Batter my heart'.",
    curatorNote: "Contains the immortal defiant challenge: 'Death, be not proud, though some have called thee mighty.'",
    gutenbergId: "4878",
    openLibraryWorkId: "OL10625W",
    subjects: ["Poetry & Epics", "Holy Sonnets", "Death Be Not Proud", "Religious Poetry", "Donne"]
  },
  {
    title: "Songs of Innocence and Experience",
    author: "William Blake",
    authorBio: "English visionary poet, painter, and printmaker whose prophetic illuminated books celebrated spiritual imagination and social justice.",
    year: 1794,
    pages: 120,
    audience: "all",
    coverId: "8232407",
    description: "Two contrary states of the human soul contrasted through paired poems, featuring 'The Lamb' and 'The Tyger' ('Tyger Tyger, burning bright').",
    curatorNote: "One of the most extraordinary lyrical achievements in English, illuminating childhood and industrial cruelty.",
    gutenbergId: "1934",
    openLibraryWorkId: "OL10626W",
    subjects: ["Poetry & Epics", "William Blake", "The Tyger", "The Lamb", "Visionary Poetry"]
  },
  {
    title: "The Marriage of Heaven and Hell",
    author: "William Blake",
    authorBio: "English visionary poet, painter, and printmaker whose prophetic illuminated books celebrated spiritual imagination and social justice.",
    year: 1793,
    pages: 90,
    audience: "adult",
    coverId: "8232408",
    description: "Prose, poetry, and prophetic aphorisms ('Proverbs of Hell') subverting Swedenborgian theology to celebrate primal creative energy over passive reason.",
    curatorNote: "Contains the iconic maxim: 'The road of excess leads to the palace of wisdom.'",
    gutenbergId: "65033",
    openLibraryWorkId: "OL10627W",
    subjects: ["Poetry & Epics", "Proverbs of Hell", "Visionary Prose", "Creative Energy", "Blake"]
  },
  {
    title: "The Prelude",
    subtitle: "Growth of a Poet's Mind",
    author: "William Wordsworth",
    authorBio: "Major English Romantic poet who launched the Romantic movement with Coleridge, celebrating the spiritual presence in nature.",
    year: 1850,
    pages: 380,
    audience: "adult",
    coverId: "8232409",
    description: "Wordsworth's spiritual and intellectual autobiography in blank verse, tracing childhood in the Lake District, the French Revolution, and restoration through nature.",
    curatorNote: "The crowning autobiographical blank verse masterpiece of the English Romantic movement.",
    gutenbergId: "12383",
    openLibraryWorkId: "OL10628W",
    subjects: ["Poetry & Epics", "Wordsworth", "The Prelude", "Romanticism", "Nature's Presence"]
  },
  {
    title: "Lyrical Ballads",
    author: "William Wordsworth & Samuel Taylor Coleridge",
    authorBio: "Pioneering Romantic poets whose 1798 joint collection overthrew 18th-century poetic diction in favor of ordinary rustic speech and supernatural wonder.",
    year: 1798,
    pages: 210,
    audience: "all",
    coverId: "8232410",
    description: "The revolutionary collection that launched British Romanticism, featuring 'The Rime of the Ancyent Marinere' and 'Lines written a few miles above Tintern Abbey'.",
    curatorNote: "The manifesto of Romanticism returning poetry to natural emotion and common humanity.",
    gutenbergId: "9622",
    openLibraryWorkId: "OL10629W",
    subjects: ["Poetry & Epics", "Lyrical Ballads", "Tintern Abbey", "Romantic Manifesto", "Coleridge"]
  },
  {
    title: "The Rime of the Ancient Mariner",
    author: "Samuel Taylor Coleridge",
    authorBio: "English Romantic poet, literary critic, and philosopher who created haunting supernatural ballads of guilt, curse, and cosmic redemption.",
    year: 1798,
    pages: 60,
    audience: "all",
    coverId: "8232411",
    description: "A sailor stops a wedding guest to recount shooting an Albatross at the South Pole, enduring spectral dead ships, ghostly retribution, and finding grace in water-snakes.",
    curatorNote: "Contains the immortal lines: 'Water, water, everywhere, / Nor any drop to drink.'",
    gutenbergId: "151",
    openLibraryWorkId: "OL10630W",
    subjects: ["Poetry & Epics", "Ancient Mariner", "The Albatross", "Supernatural Ballad", "Coleridge"]
  },
  {
    title: "Christabel and Kubla Khan",
    author: "Samuel Taylor Coleridge",
    authorBio: "English Romantic poet, literary critic, and philosopher who created haunting supernatural ballads of guilt, curse, and cosmic redemption.",
    year: 1816,
    pages: 70,
    audience: "teen",
    coverId: "8232412",
    description: "Includes the unfinished Gothic vampire ballad 'Christabel' and the legendary opium dream vision 'Kubla Khan: Or, a Vision in a Dream. A Fragment'.",
    curatorNote: "Features 'Kubla Khan' and its 'stately pleasure-dome' on the sacred river Alph.",
    gutenbergId: "8496",
    openLibraryWorkId: "OL10631W",
    subjects: ["Poetry & Epics", "Kubla Khan", "Xanadu", "Opium Dream", "Christabel"]
  },
  {
    title: "Odes and Selected Poems",
    author: "John Keats",
    authorBio: "English Romantic poet whose sensual imagery, exquisite music, and profound meditations on beauty made him one of the supreme lyric poets in world history.",
    year: 1820,
    pages: 180,
    audience: "all",
    coverId: "8232413",
    description: "The miraculous Great Odes of 1819 including 'Ode to a Nightingale', 'Ode on a Grecian Urn', 'To Autumn', 'Ode on Melancholy', and 'La Belle Dame sans Merci'.",
    curatorNote: "Contains the immortal line: 'Beauty is truth, truth beauty,—that is all / Ye know on earth, and all ye need to know.'",
    gutenbergId: "23684",
    openLibraryWorkId: "OL10632W",
    subjects: ["Poetry & Epics", "John Keats", "Great Odes", "Ode to Nightingale", "Grecian Urn"]
  },
  {
    title: "Endymion",
    subtitle: "A Poetic Romance",
    author: "John Keats",
    authorBio: "English Romantic poet whose sensual imagery, exquisite music, and profound meditations on beauty made him one of the supreme lyric poets in world history.",
    year: 1818,
    pages: 210,
    audience: "teen",
    coverId: "8232414",
    description: "A mythological romance following the shepherd Endymion and his passionate pursuit of Cynthia, the goddess of the Moon, through earth, sea, and underworld.",
    curatorNote: "Opens with one of the most famous lines in English poetry: 'A thing of beauty is a joy for ever.'",
    gutenbergId: "24269",
    openLibraryWorkId: "OL10633W",
    subjects: ["Poetry & Epics", "Endymion", "Thing of Beauty", "Moon Goddess", "Mythological Romance"]
  },
  {
    title: "Hyperion and The Fall of Hyperion",
    author: "John Keats",
    authorBio: "English Romantic poet whose sensual imagery, exquisite music, and profound meditations on beauty made him one of the supreme lyric poets in world history.",
    year: 1820,
    pages: 120,
    audience: "adult",
    coverId: "8232415",
    description: "Keats' epic blank verse fragment depicting the defeat of the ancient Titan gods by the young Olympian deities, exploring suffering as the necessary catalyst of poetic wisdom.",
    curatorNote: "Keats' highest reach toward Miltonic epic grandeur and tragic philosophical weight.",
    gutenbergId: "65034",
    openLibraryWorkId: "OL10634W",
    subjects: ["Poetry & Epics", "Hyperion", "Titans vs Olympians", "Blank Verse", "Keats"]
  },
  {
    title: "Prometheus Unbound",
    author: "Percy Bysshe Shelley",
    authorBio: "Radical English Romantic poet whose lyrical dramas championed political liberty, defiance of tyranny, and universal love.",
    year: 1820,
    pages: 200,
    audience: "adult",
    coverId: "8232416",
    description: "A four-act lyrical drama where Prometheus renounces hatred for Zeus, precipitating the overthrow of tyrannical Jupiter by Demogorgon and universal cosmic liberation.",
    curatorNote: "Shelley's visionary masterwork: conquering tyranny through unyielding forgiveness and love.",
    gutenbergId: "4776",
    openLibraryWorkId: "OL10635W",
    subjects: ["Poetry & Epics", "Prometheus Unbound", "Shelley", "Lyrical Drama", "Defiance of Tyranny"]
  },
  {
    title: "Adonais",
    subtitle: "An Elegy on the Death of John Keats",
    author: "Percy Bysshe Shelley",
    authorBio: "Radical English Romantic poet whose lyrical dramas championed political liberty, defiance of tyranny, and universal love.",
    year: 1821,
    pages: 60,
    audience: "all",
    coverId: "8232417",
    description: "A pastoral elegy in fifty-five Spenserian stanzas mourning the early death of John Keats in Rome, culminating in Neo-Platonic transcendence of earthly mortality.",
    curatorNote: "Contains the immortal line: 'The One remains, the many change and pass; / Heaven's light forever shines.'",
    gutenbergId: "4770",
    openLibraryWorkId: "OL10636W",
    subjects: ["Poetry & Epics", "Adonais", "Elegy for Keats", "Spenserian Stanza", "Shelley"]
  },
  {
    title: "Don Juan",
    author: "Lord Byron",
    authorBio: "English Romantic poet and peer whose satirical wit, Byronic heroes, and rebellious adventures captivated all of Europe.",
    year: 1819,
    pages: 680,
    audience: "adult",
    coverId: "8232418",
    description: "Byron reverses the legendary seducer myth: Don Juan is an innocent youth easily seduced by women across Spain, Greek pirate islands, Turkish harems, and Russian sieges.",
    curatorNote: "A tour de force of comic ottava rima verse and sparkling, cynical social satire.",
    gutenbergId: "21700",
    openLibraryWorkId: "OL10637W",
    subjects: ["Poetry & Epics", "Lord Byron", "Don Juan", "Ottava Rima", "Satirical Epic"]
  },
  {
    title: "Childe Harold's Pilgrimage",
    author: "Lord Byron",
    authorBio: "English Romantic poet and peer whose satirical wit, Byronic heroes, and rebellious adventures captivated all of Europe.",
    year: 1812,
    pages: 280,
    audience: "teen",
    coverId: "8232419",
    description: "A disillusioned young nobleman wanders across war-torn Portugal, Spain, Greece, and Italy, reflecting on ruined empires and sublime Alpine landscapes.",
    curatorNote: "The sensational travel poem that made Byron famously declare: 'I awoke one morning and found myself famous.'",
    gutenbergId: "5131",
    openLibraryWorkId: "OL10638W",
    subjects: ["Poetry & Epics", "Byronic Hero", "Childe Harold", "Grand Tour", "Alpine Sublime"]
  },
  {
    title: "Manfred",
    author: "Lord Byron",
    authorBio: "English Romantic poet and peer whose satirical wit, Byronic heroes, and rebellious adventures captivated all of Europe.",
    year: 1817,
    pages: 90,
    audience: "adult",
    coverId: "8232420",
    description: "Living in solitary despair in the Swiss Alps, sorcerer Manfred summons nature spirits and the phantom of his beloved Astarte, refusing submission even to demons in death.",
    curatorNote: "The supreme manifestation of the defiant, remorse-stricken Byronic hero.",
    gutenbergId: "2353",
    openLibraryWorkId: "OL10639W",
    subjects: ["Poetry & Epics", "Manfred", "Byronic Hero", "Faustian Drama", "Swiss Alps"]
  },
  {
    title: "Leaves of Grass",
    author: "Walt Whitman",
    authorBio: "The bard of American democracy whose free verse celebrations of the self, nature, and comradeship revolutionized world poetry.",
    year: 1855,
    pages: 450,
    audience: "adult",
    coverId: "8232421",
    description: "Whitman's groundbreaking free-verse epic celebrating the body, democracy, cosmic oneness, and camaraderie, featuring 'Song of Myself' and 'Crossing Brooklyn Ferry'.",
    curatorNote: "The supreme hymn of American democracy, vitality, and universal human brotherhood.",
    gutenbergId: "1322",
    openLibraryWorkId: "OL10641W",
    subjects: ["Poetry & Epics", "Leaves of Grass", "Song of Myself", "Free Verse", "Walt Whitman"]
  },
  {
    title: "Complete Poems of Emily Dickinson",
    author: "Emily Dickinson",
    authorBio: "Reclusive American poet of Amherst whose revolutionary slant rhymes, dashes, and metaphysical brilliance redefined modern lyric poetry.",
    year: 1890,
    pages: 360,
    audience: "all",
    coverId: "8232422",
    description: "Over 1,700 concise, crystalline lyrics exploring immortality, death, hope, ecstasy, and nature ('Because I could not stop for Death', 'Hope is the thing with feathers').",
    curatorNote: "A towering monument of original lyric compression and transcendent metaphysical vision.",
    gutenbergId: "12242",
    openLibraryWorkId: "OL10642W",
    subjects: ["Poetry & Epics", "Emily Dickinson", "Hope is the Thing", "American Lyric", "Metaphysical Poems"]
  },
  {
    title: "Idylls of the King",
    author: "Alfred, Lord Tennyson",
    authorBio: "Poet Laureate of the United Kingdom during the Victorian era whose musical verse captured the ideals and anxieties of his age.",
    year: 1859,
    pages: 390,
    audience: "all",
    coverId: "8232423",
    description: "Twelve narrative poems recounting the rise and tragic fall of King Arthur's realm, Camelot, the quest for the Holy Grail, and Lancelot and Guinevere.",
    curatorNote: "The definitive Victorian retelling of Arthurian romance, written in gorgeous blank verse.",
    gutenbergId: "610",
    openLibraryWorkId: "OL10643W",
    subjects: ["Poetry & Epics", "Arthurian Epic", "Tennyson", "Holy Grail", "Lancelot and Guinevere"]
  },
  {
    title: "In Memoriam A.H.H.",
    author: "Alfred, Lord Tennyson",
    authorBio: "Poet Laureate of the United Kingdom during the Victorian era whose musical verse captured the ideals and anxieties of his age.",
    year: 1850,
    pages: 180,
    audience: "all",
    coverId: "8232424",
    description: "A monumental sequence of 133 cantos mourning the sudden death of Tennyson's closest friend Arthur Henry Hallam, moving from despair to spiritual hope.",
    curatorNote: "Contains the immortal lines: ''Tis better to have loved and lost / Than never to have loved at all.'",
    gutenbergId: "360",
    openLibraryWorkId: "OL10644W",
    subjects: ["Poetry & Epics", "Tennyson", "In Memoriam", "Loved and Lost", "Elegiac Masterpiece"]
  },
  {
    title: "The Ring and the Book",
    author: "Robert Browning",
    authorBio: "Victorian master of the dramatic monologue whose psychological depth and conversational verse influenced modern 20th-century poetry.",
    year: 1868,
    pages: 620,
    audience: "adult",
    coverId: "8232425",
    description: "A monumental verse novel in twelve dramatic monologues examining a 1698 Rome murder trial from multiple conflicting perspectives.",
    curatorNote: "Browning's supreme masterpiece pioneering modern multi-perspective narrative structure.",
    gutenbergId: "4023",
    openLibraryWorkId: "OL10645W",
    subjects: ["Poetry & Epics", "Robert Browning", "Dramatic Monologue", "Verse Novel", "Rome Trial"]
  },
  {
    title: "Men and Women",
    author: "Robert Browning",
    authorBio: "Victorian master of the dramatic monologue whose psychological depth and conversational verse influenced modern 20th-century poetry.",
    year: 1855,
    pages: 290,
    audience: "teen",
    coverId: "8232426",
    description: "Fifty-one dramatic monologues including 'Fra Lippo Lippi', 'Andrea del Sarto', 'Childe Roland to the Dark Tower Came', and 'A Toccata of Galuppi's'.",
    curatorNote: "The greatest single collection of dramatic monologues in English literature.",
    gutenbergId: "5095",
    openLibraryWorkId: "OL10646W",
    subjects: ["Poetry & Epics", "Fra Lippo Lippi", "Childe Roland", "Dramatic Monologues", "Browning"]
  },
  {
    title: "Sonnets from the Portuguese",
    author: "Elizabeth Barrett Browning",
    authorBio: "Renowned Victorian poet whose passionate sonnet sequence celebrated her secret courtship and marriage to fellow poet Robert Browning.",
    year: 1850,
    pages: 90,
    audience: "all",
    coverId: "8232427",
    description: "Forty-four intimate love sonnets chronicling Elizabeth's awakening love for Robert Browning, overcoming chronic invalidism through devotion.",
    curatorNote: "Contains Sonnet 43: 'How do I love thee? Let me count the ways.'",
    gutenbergId: "12245",
    openLibraryWorkId: "OL10647W",
    subjects: ["Poetry & Epics", "How Do I Love Thee", "Barrett Browning", "Love Sonnets", "Victorian Lyric"]
  },
  {
    title: "Aurora Leigh",
    author: "Elizabeth Barrett Browning",
    authorBio: "Renowned Victorian poet whose passionate sonnet sequence celebrated her secret courtship and marriage to fellow poet Robert Browning.",
    year: 1856,
    pages: 420,
    audience: "adult",
    coverId: "8232428",
    description: "An epic novel in blank verse following an independent woman poet, Aurora Leigh, as she refuses domestic subjection to pursue her professional artistic calling.",
    curatorNote: "The first great feminist epic in English verse, championed by Virginia Woolf.",
    gutenbergId: "24451",
    openLibraryWorkId: "OL10648W",
    subjects: ["Poetry & Epics", "Aurora Leigh", "Woman Artist", "Verse Novel", "Feminist Epic"]
  },
  {
    title: "The Raven and Other Poems",
    author: "Edgar Allan Poe",
    authorBio: "American master of the macabre whose hypnotic rhythms and melodic refrains made poems like 'The Raven' iconic worldwide.",
    year: 1845,
    pages: 110,
    audience: "all",
    coverId: "8232429",
    description: "Poe's greatest verse including 'The Raven' with its haunting 'Nevermore', 'Annabel Lee', 'The Bells', 'Ulalume', and 'A Dream Within a Dream'.",
    curatorNote: "Contains the immortal lines of grief and eerie musical perfection in 'The Raven'.",
    gutenbergId: "10031",
    openLibraryWorkId: "OL10649W",
    subjects: ["Poetry & Epics", "The Raven", "Annabel Lee", "Edgar Allan Poe", "Gothic Verse"]
  },
  {
    title: "Goblin Market and Other Poems",
    author: "Christina Rossetti",
    authorBio: "English Pre-Raphaelite poet whose rich sensory imagery and spiritual devotion created innovative Victorian poetic fairy tales.",
    year: 1862,
    pages: 140,
    audience: "teen",
    coverId: "8232430",
    description: "Sisters Laura and Lizzie are tempted by goblin merchants selling forbidden fruit, leading to Lizzie's heroic sisterly sacrifice to save her sister's life.",
    curatorNote: "A lush, sensuous masterpiece of sisterhood, temptation, and Pre-Raphaelite symbolism.",
    gutenbergId: "16801",
    openLibraryWorkId: "OL10650W",
    subjects: ["Poetry & Epics", "Goblin Market", "Christina Rossetti", "Pre-Raphaelite", "Sisterhood"]
  },
  {
    title: "The Flowers of Evil",
    subtitle: "Les Fleurs du mal",
    author: "Charles Baudelaire",
    authorBio: "French poet whose Symbolist and Modernist poems captured urban spleen, sensual beauty, and the alienation of Parisian modernity.",
    year: 1857,
    pages: 280,
    audience: "adult",
    coverId: "8232431",
    description: "Baudelaire's revolutionary collection capturing the tension between heavenly ideal and urban despair (Spleen et Idéal), transforming ugly reality into art.",
    curatorNote: "The foundational monument of modern European poetry that launched Symbolism and Modernism.",
    gutenbergId: "65035",
    openLibraryWorkId: "OL10651W",
    subjects: ["Poetry & Epics", "Baudelaire", "Symbolism", "Parisian Modernity", "Spleen and Ideal"]
  },
  {
    title: "Gitanjali",
    subtitle: "Song Offerings",
    author: "Rabindranath Tagore",
    authorBio: "Bengali polymath, poet, musician, and philosopher who became the first non-European to win the Nobel Prize in Literature in 1913.",
    year: 1912,
    pages: 130,
    audience: "all",
    coverId: "8232432",
    description: "103 devotional prose-poems translated into English by Tagore himself, filled with mystical simplicity, communion with nature, and divine love.",
    curatorNote: "W.B. Yeats wrote that these poems 'stirred my blood as nothing has for years.'",
    gutenbergId: "7164",
    openLibraryWorkId: "OL10652W",
    subjects: ["Poetry & Epics", "Tagore", "Gitanjali", "Nobel Laureate", "Mystical Verse"]
  },
  {
    title: "The Rubaiyat of Omar Khayyam",
    author: "Omar Khayyam",
    authorBio: "Persian polymath, mathematician, astronomer, and poet whose quatrains celebrating the fleeting present moment captivated the Victorian world.",
    year: 1120,
    pages: 110,
    audience: "all",
    coverId: "8232433",
    description: "Edward FitzGerald's famous English translation of Persian quatrains celebrating wine, love, carpe diem, and the mystery of existence under the stars.",
    curatorNote: "Contains the immortal lines: 'A Book of Verses underneath the Bough, / A Jug of Wine, a Loaf of Bread—and Thou.'",
    gutenbergId: "246",
    openLibraryWorkId: "OL10653W",
    subjects: ["Poetry & Epics", "Omar Khayyam", "Rubaiyat", "Carpe Diem", "Persian Poetry"]
  }
];
