module.exports = [
  {
    title: "The Importance of Being Earnest",
    author: "Oscar Wilde",
    authorBio: "Irish playwright, novelist, and legendary wit whose sparkling social comedies and epigrams conquered late Victorian London.",
    year: 1895,
    pages: 120,
    audience: "teen",
    coverId: "8226191",
    description: "Gentlemen Jack Worthing and Algernon Moncrieff adopt fictitious alter-egos named Ernest to escape social obligations and court Gwendolen and Cecily.",
    curatorNote: "The sharpest, most sparkling and perfect high-comedy farce in the English language.",
    gutenbergId: "844",
    openLibraryWorkId: "OL1488108W",
    subjects: ["Wit & Satire", "Oscar Wilde", "Lady Bracknell", "Bunburying", "Comedy of Manners"]
  },
  {
    title: "Lady Windermere's Fan",
    author: "Oscar Wilde",
    authorBio: "Irish playwright, novelist, and legendary wit whose sparkling social comedies and epigrams conquered late Victorian London.",
    year: 1892,
    pages: 130,
    audience: "teen",
    coverId: "8232434",
    description: "Lady Windermere suspects her husband of infidelity with mysterious Mrs. Erlynne, unaware that Mrs. Erlynne is her own disgraced mother sacrificing her reputation to save her.",
    curatorNote: "Contains the iconic line: 'We are all in the gutter, but some of us are looking at the stars.'",
    gutenbergId: "790",
    openLibraryWorkId: "OL1488109W",
    subjects: ["Wit & Satire", "Society Drama", "Epigrams", "Oscar Wilde", "Social Morality"]
  },
  {
    title: "A Woman of No Importance",
    author: "Oscar Wilde",
    authorBio: "Irish playwright, novelist, and legendary wit whose sparkling social comedies and epigrams conquered late Victorian London.",
    year: 1893,
    pages: 140,
    audience: "teen",
    coverId: "8232435",
    description: "Witty bachelor Lord Illingworth hires young Gerald Arbuthnot as private secretary, only for Gerald's mother to recognize Illingworth as the man who abandoned them.",
    curatorNote: "A razor-sharp social satire dissecting Victorian double standards regarding men and women.",
    gutenbergId: "854",
    openLibraryWorkId: "OL1488110W",
    subjects: ["Wit & Satire", "Victorian Hypocrisy", "Lord Illingworth", "Motherhood", "Wilde Satire"]
  },
  {
    title: "An Ideal Husband",
    author: "Oscar Wilde",
    authorBio: "Irish playwright, novelist, and legendary wit whose sparkling social comedies and epigrams conquered late Victorian London.",
    year: 1895,
    pages: 150,
    audience: "teen",
    coverId: "8232436",
    description: "Sir Robert Chiltern's promising political career is threatened by Mrs. Cheveley with past insider trading secrets, until witty dandy Lord Goring intervenes.",
    curatorNote: "Combines political blackmail intrigue with some of Wilde's most brilliant aphorisms.",
    gutenbergId: "882",
    openLibraryWorkId: "OL1488118W",
    subjects: ["Wit & Satire", "Political Blackmail", "Lord Goring", "Cabinet Politics", "Ideal Husband"]
  },
  {
    title: "Lord Arthur Savile's Crime",
    author: "Oscar Wilde",
    authorBio: "Irish playwright, novelist, and legendary wit whose sparkling social comedies and epigrams conquered late Victorian London.",
    year: 1891,
    pages: 90,
    audience: "teen",
    coverId: "8232437",
    description: "A chiromantist reads Lord Arthur Savile's palm and predicts he will commit a murder, leading the conscientious aristocrat to delay his wedding until he gets the murder over with.",
    curatorNote: "A delightfully absurd black comedy turning Victorian duty and social etiquette on its head.",
    gutenbergId: "773",
    openLibraryWorkId: "OL1488119W",
    subjects: ["Wit & Satire", "Black Comedy", "Chiromancy", "Lord Arthur Savile", "Humorous Parody"]
  },
  {
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1876,
    pages: 274,
    audience: "all",
    coverId: "8232438",
    description: "Tom Sawyer whitewashes fences, hunts treasure with Huckleberry Finn, witnesses Injun Joe in the graveyard, and gets lost with Becky Thatcher in McDougal's Cave.",
    curatorNote: "The supreme celebration of American boyhood mischief, adventure, and summer freedom.",
    gutenbergId: "74",
    openLibraryWorkId: "OL53896W",
    subjects: ["Wit & Satire", "Tom Sawyer", "Mississippi River", "Boyhood Freedom", "American Humor"]
  },
  {
    title: "Adventures of Huckleberry Finn",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1884,
    pages: 366,
    audience: "all",
    coverId: "8232439",
    description: "Huck Finn escapes his drunken father and rafts down the Mississippi River with runaway slave Jim, famously choosing to 'go to hell' rather than betray his friend.",
    curatorNote: "Ernest Hemingway declared: 'All modern American literature comes from one book by Mark Twain called Huckleberry Finn.'",
    gutenbergId: "76",
    openLibraryWorkId: "OL53897W",
    subjects: ["Wit & Satire", "Huckleberry Finn", "Mississippi Raft", "Jim", "American Masterpiece"]
  },
  {
    title: "A Connecticut Yankee in King Arthur's Court",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1889,
    pages: 360,
    audience: "all",
    coverId: "8232440",
    description: "Hartford factory engineer Hank Morgan is knocked unconscious and wakes up in Camelot in 528 AD, using 19th-century technology to out-magic Merlin.",
    curatorNote: "A hilarious and biting satire contrasting industrial Yankee ingenuity with feudal superstition.",
    gutenbergId: "86",
    openLibraryWorkId: "OL53898W",
    subjects: ["Wit & Satire", "Connecticut Yankee", "King Arthur", "Time Travel Comedy", "Mark Twain"]
  },
  {
    title: "The Prince and the Pauper",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1881,
    pages: 290,
    audience: "all",
    coverId: "8232441",
    description: "In Tudor London, young Prince Edward VI and beggar boy Tom Canty discover they look identical and swap clothes on a whim, experiencing life on both sides of society.",
    curatorNote: "A beloved historical comedy of identity and social justice for readers of all ages.",
    gutenbergId: "1837",
    openLibraryWorkId: "OL53899W",
    subjects: ["Wit & Satire", "Prince and Pauper", "Tudor London", "Swapped Identities", "Twain Classic"]
  },
  {
    title: "The Innocents Abroad",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1869,
    pages: 580,
    audience: "teen",
    coverId: "8232442",
    description: "Twain's uproarious travelogue aboard the Quaker City through France, Italy, Greece, and the Holy Land, puncturing European pretension with frontier skepticism.",
    curatorNote: "Twain's best-selling lifetime work, creating modern irreverent travel satire.",
    gutenbergId: "3176",
    openLibraryWorkId: "OL53900W",
    subjects: ["Wit & Satire", "Travel Satire", "Quaker City", "Grand Tour Parody", "Mark Twain"]
  },
  {
    title: "Roughing It",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1872,
    pages: 520,
    audience: "teen",
    coverId: "8232443",
    description: "Twain's semi-autobiographical adventures heading West by stagecoach through Nevada, Virginia City silver mining boomtowns, San Francisco, and Hawaii.",
    curatorNote: "A roaring, riotous portrait of the Wild West boomtown era packed with tall tales.",
    gutenbergId: "3177",
    openLibraryWorkId: "OL53901W",
    subjects: ["Wit & Satire", "Wild West", "Nevada Silver Boom", "Tall Tales", "American Frontier"]
  },
  {
    title: "Life on the Mississippi",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1883,
    pages: 480,
    audience: "all",
    coverId: "8232444",
    description: "Twain recalls his apprentice years learning the treacherous snags and bends of the Mississippi under steamboat pilot Horace Bixby before the Civil War.",
    curatorNote: "A sparkling, nostalgic love letter to the golden era of Mississippi steamboats.",
    gutenbergId: "245",
    openLibraryWorkId: "OL53902W",
    subjects: ["Wit & Satire", "Steamboats", "Mississippi Pilot", "Memoir", "River Lore"]
  },
  {
    title: "The Celebrated Jumping Frog",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1867,
    pages: 140,
    audience: "all",
    coverId: "8232445",
    description: "Simon Wheeler cornering an unwilling listener in Angel's Camp to recount Jim Smiley and his frog Dan'l Webster, filled with quail-shot by a stranger.",
    curatorNote: "The tall tale that first launched Mark Twain's national fame as an American humorist.",
    gutenbergId: "78",
    openLibraryWorkId: "OL53903W",
    subjects: ["Wit & Satire", "Jumping Frog", "Angels Camp", "Tall Tale", "Frontier Humor"]
  },
  {
    title: "The Man That Corrupted Hadleyburg",
    author: "Mark Twain",
    authorBio: "American humorist, novelist, and lecturer whose Mississippi river novels captured authentic American speech and boyhood freedom.",
    year: 1899,
    pages: 80,
    audience: "teen",
    coverId: "8232446",
    description: "A mysterious stranger leaves a sack of gold in Hadleyburg—reputed to be the most incorruptible town in America—tempting the nineteen leading citizens into exposed greed.",
    curatorNote: "Twain's darkest, most brilliant satirical dissection of self-righteous provincial hypocrisy.",
    gutenbergId: "119",
    openLibraryWorkId: "OL53904W",
    subjects: ["Wit & Satire", "Hadleyburg", "Hypocrisy", "Sack of Gold", "Social Satire"]
  },
  {
    title: "Three Men in a Boat",
    subtitle: "To Say Nothing of the Dog",
    author: "Jerome K. Jerome",
    authorBio: "English humorist and playwright whose account of a Thames boating holiday remains a universally treasured comic classic.",
    year: 1889,
    pages: 240,
    audience: "all",
    coverId: "8232447",
    description: "Three hypochondriacal Victorian clerks—George, Harris, J., and Montmorency the fox terrier—take a two-week boating holiday up the River Thames.",
    curatorNote: "Universally considered one of the funniest, warmest comic novels ever written.",
    gutenbergId: "308",
    openLibraryWorkId: "OL21881W",
    subjects: ["Wit & Satire", "Thames Boating", "Montmorency", "Hypochondria", "British Comedy"]
  },
  {
    title: "Three Men on the Bummel",
    author: "Jerome K. Jerome",
    authorBio: "English humorist and playwright whose account of a Thames boating holiday remains a universally treasured comic classic.",
    year: 1900,
    pages: 260,
    audience: "all",
    coverId: "8232448",
    description: "George, Harris, and J. reunite ten years later for a bicycle tour through Germany's Black Forest, navigating imperial German rules, tandem bikes, and beer gardens.",
    curatorNote: "The delightful bicycling sequel to Three Men in a Boat, full of affectionate European observations.",
    gutenbergId: "2183",
    openLibraryWorkId: "OL21882W",
    subjects: ["Wit & Satire", "Black Forest", "Bicycle Tour", "German Rules", "Comic Sequel"]
  },
  {
    title: "Idle Thoughts of an Idle Fellow",
    author: "Jerome K. Jerome",
    authorBio: "English humorist and playwright whose account of a Thames boating holiday remains a universally treasured comic classic.",
    year: 1886,
    pages: 180,
    audience: "all",
    coverId: "8232449",
    description: "Fourteen humorous essays on being idle, falling in love, getting on in the world, memory, babies, eating, and the joy of doing nothing.",
    curatorNote: "The charming predecessor to Three Men in a Boat celebrating the fine art of unhurried living.",
    gutenbergId: "849",
    openLibraryWorkId: "OL21883W",
    subjects: ["Wit & Satire", "Art of Idleness", "Humorous Essays", "Jerome K Jerome", "Gentle Wit"]
  },
  {
    title: "Gulliver's Travels",
    author: "Jonathan Swift",
    authorBio: "Anglo-Irish satirist, essayist, and Dean of St. Patrick's Cathedral Dublin whose savage indignation exposed human folly.",
    year: 1726,
    pages: 350,
    audience: "all",
    coverId: "8232450",
    description: "Ship's surgeon Lemuel Gulliver voyages to the tiny Lilliputians, the giant Brobdingnagians, the flying island of Laputa, and the noble equine Houyhnhnms.",
    curatorNote: "The supreme masterpiece of political and philosophical satire in world literature.",
    gutenbergId: "829",
    openLibraryWorkId: "OL21884W",
    subjects: ["Wit & Satire", "Gulliver", "Lilliput", "Houyhnhnms", "Philosophical Satire"]
  },
  {
    title: "A Modest Proposal",
    author: "Jonathan Swift",
    authorBio: "Anglo-Irish satirist, essayist, and Dean of St. Patrick's Cathedral Dublin whose savage indignation exposed human folly.",
    year: 1729,
    pages: 40,
    audience: "adult",
    coverId: "8232451",
    description: "Swift satirically suggests that impoverished Irish parents sell their babies as culinary delicacies to wealthy English landlords to solve famine and poverty.",
    curatorNote: "The most famous and devastating piece of political irony and economic satire ever penned.",
    gutenbergId: "1080",
    openLibraryWorkId: "OL21885W",
    subjects: ["Wit & Satire", "Modest Proposal", "Irony", "Irish Famine", "Savage Satire"]
  },
  {
    title: "A Tale of a Tub",
    author: "Jonathan Swift",
    authorBio: "Anglo-Irish satirist, essayist, and Dean of St. Patrick's Cathedral Dublin whose savage indignation exposed human folly.",
    year: 1704,
    pages: 230,
    audience: "adult",
    coverId: "8232452",
    description: "An allegory of three brothers—Peter, Martin, and Jack—inheriting coats from their father, satirizing religious corruption, scholarly vanity, and modern critics.",
    curatorNote: "Swift's earliest major satire, overflowing with dazzling linguistic parody and digressions.",
    gutenbergId: "4737",
    openLibraryWorkId: "OL21886W",
    subjects: ["Wit & Satire", "Tale of a Tub", "Religious Parody", "Digressions", "Early Swift"]
  },
  {
    title: "The Battle of the Books",
    author: "Jonathan Swift",
    authorBio: "Anglo-Irish satirist, essayist, and Dean of St. Patrick's Cathedral Dublin whose savage indignation exposed human folly.",
    year: 1704,
    pages: 60,
    audience: "teen",
    coverId: "8232453",
    description: "A mock-heroic battle in the King's Library between ancient classical books (Homer, Plato) and modern publications (Descartes, modern critics), featuring the Spider and the Bee.",
    curatorNote: "Famous for the fable of the Spider and the Bee that gave us 'sweetness and light'.",
    gutenbergId: "623",
    openLibraryWorkId: "OL21887W",
    subjects: ["Wit & Satire", "Ancients and Moderns", "Mock-Heroic", "Sweetness and Light", "Library Battle"]
  },
  {
    title: "Candide",
    author: "Voltaire",
    authorBio: "French Enlightenment writer and philosopher whose biting satire and advocacy of civil liberties dismantled philosophical optimism.",
    year: 1759,
    pages: 140,
    audience: "adult",
    coverId: "8232454",
    description: "Naïve Candide and his tutor Dr. Pangloss endure earthquakes, inquisitions, shipwrecks, and wars, testing the doctrine that 'all is for the best in the best of all possible worlds.'",
    curatorNote: "Voltaire's lightning-fast satirical masterpiece concluding with the wisdom: 'We must cultivate our garden.'",
    gutenbergId: "19942",
    openLibraryWorkId: "OL21888W",
    subjects: ["Wit & Satire", "Candide", "Pangloss", "Cultivate Our Garden", "Enlightenment Satire"]
  },
  {
    title: "Zadig",
    subtitle: "Or, The Book of Fate",
    author: "Voltaire",
    authorBio: "French Enlightenment writer and philosopher whose biting satire and advocacy of civil liberties dismantled philosophical optimism.",
    year: 1747,
    pages: 130,
    audience: "teen",
    coverId: "8232455",
    description: "The wise Babylonian philosopher Zadig uses deductive reasoning to describe a queen's dog and king's horse without ever seeing them, facing envy and exile.",
    curatorNote: "The seminal philosophical tale credited with inspiring the method of modern forensic detective fiction.",
    gutenbergId: "18972",
    openLibraryWorkId: "OL21889W",
    subjects: ["Wit & Satire", "Zadig", "Babylon", "Deductive Method", "Philosophical Tale"]
  },
  {
    title: "Micromégas",
    author: "Voltaire",
    authorBio: "French Enlightenment writer and philosopher whose biting satire and advocacy of civil liberties dismantled philosophical optimism.",
    year: 1752,
    pages: 50,
    audience: "teen",
    coverId: "8232456",
    description: "A 120,000-foot alien giant from Sirius and his companion from Saturn visit Earth, marveling with amusement at the pride and endless wars of tiny human insects.",
    curatorNote: "One of the earliest works of philosophical science fiction satirizing human arrogance from a cosmic scale.",
    gutenbergId: "30123",
    openLibraryWorkId: "OL21890W",
    subjects: ["Wit & Satire", "Cosmic Satire", "Extraterrestrial Giants", "Human Vanity", "Voltaire Sci-Fi"]
  },
  {
    title: "Letters on England",
    author: "Voltaire",
    authorBio: "French Enlightenment writer and philosopher whose biting satire and advocacy of civil liberties dismantled philosophical optimism.",
    year: 1733,
    pages: 190,
    audience: "adult",
    coverId: "8232457",
    description: "Voltaire's witty essays praising English religious tolerance, Newtonian science, Parliament, and smallpox inoculation while satirizing French censorship.",
    curatorNote: "A landmark Enlightenment manifesto on liberty of conscience and scientific inquiry.",
    gutenbergId: "2445",
    openLibraryWorkId: "OL21891W",
    subjects: ["Wit & Satire", "Enlightenment Essays", "Religious Tolerance", "Newtonian Science", "Voltaire"]
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    authorBio: "Spanish writer whose 1605 masterpiece created the modern Western novel and the immortal pairing of Don Quixote and Sancho Panza.",
    year: 1605,
    pages: 860,
    audience: "all",
    coverId: "14428305",
    description: "Aging country gentleman Alonso Quixano reads so many chivalric romances that he sets out as knight-errant Don Quixote with squire Sancho Panza, tilting at windmills.",
    curatorNote: "The founding masterpiece of the modern novel: hilarious, tragic, and profoundly humane.",
    gutenbergId: "996",
    openLibraryWorkId: "OL21892W",
    subjects: ["Wit & Satire", "Don Quixote", "Sancho Panza", "Tilting at Windmills", "Spanish Masterpiece"]
  },
  {
    title: "Exemplary Novels",
    author: "Miguel de Cervantes",
    authorBio: "Spanish writer whose 1605 masterpiece created the modern Western novel and the immortal pairing of Don Quixote and Sancho Panza.",
    year: 1613,
    pages: 420,
    audience: "teen",
    coverId: "8232458",
    description: "Twelve sparkling novellas including 'Rinconete and Cortadillo' depicting Seville pickpockets, and 'The Dialogue of the Dogs' between talking dogs Scipio and Berganza.",
    curatorNote: "Cervantes' delightful showcase of picaresque rogues, sparkling wit, and Italianate intrigue.",
    gutenbergId: "14100",
    openLibraryWorkId: "OL21893W",
    subjects: ["Wit & Satire", "Picaresque", "Rinconete and Cortadillo", "Talking Dogs", "Cervantes"]
  },
  {
    title: "My Man Jeeves",
    author: "P.G. Wodehouse",
    authorBio: "English author and humorist whose peerless comic prose created the immortal gentleman Bertie Wooster and his genius valet Jeeves.",
    year: 1919,
    pages: 200,
    audience: "all",
    coverId: "8232459",
    description: "Eight sparkling stories introducing wealthy, amiable Bertie Wooster and his unflappable, intellectual valet Jeeves who untangles matrimonial scrapes.",
    curatorNote: "The opening classic of the greatest light comedic partnership in British literature.",
    gutenbergId: "8164",
    openLibraryWorkId: "OL21894W",
    subjects: ["Wit & Satire", "Jeeves and Wooster", "Bertie Wooster", "British Humor", "Comic Valet"]
  },
  {
    title: "The Inimitable Jeeves",
    author: "P.G. Wodehouse",
    authorBio: "English author and humorist whose peerless comic prose created the immortal gentleman Bertie Wooster and his genius valet Jeeves.",
    year: 1923,
    pages: 260,
    audience: "all",
    coverId: "8232460",
    description: "Bertie Wooster helps his hapless friend Bingo Little through a succession of disastrous infatuations, saved each time by Jeeves' psychological brilliance.",
    curatorNote: "Pure comedic champagne from the golden age of English humorous writing.",
    gutenbergId: "65036",
    openLibraryWorkId: "OL21895W",
    subjects: ["Wit & Satire", "Bingo Little", "Jeeves", "Bertie Wooster", "Comic Scrapes"]
  },
  {
    title: "Right Ho, Jeeves",
    author: "P.G. Wodehouse",
    authorBio: "English author and humorist whose peerless comic prose created the immortal gentleman Bertie Wooster and his genius valet Jeeves.",
    year: 1934,
    pages: 280,
    audience: "all",
    coverId: "8232461",
    description: "Bertie ignores Jeeves' advice and attempts to fix the romantic problems of Gussie Fink-Nottle and Angela Travers at Brinkley Court, causing hilarious mayhem.",
    curatorNote: "Features Gussie Fink-Nottle's drunken Market Snodsbury grammar school prize-giving speech.",
    gutenbergId: "10554",
    openLibraryWorkId: "OL21896W",
    subjects: ["Wit & Satire", "Brinkley Court", "Gussie Fink-Nottle", "Prize Giving", "Wodehouse Masterpiece"]
  },
  {
    title: "Something Fresh",
    author: "P.G. Wodehouse",
    authorBio: "English author and humorist whose peerless comic prose created the immortal gentleman Bertie Wooster and his genius valet Jeeves.",
    year: 1915,
    pages: 270,
    audience: "all",
    coverId: "8232462",
    description: "The historical first novel set at Blandings Castle, following Ashe Marson and Joan Valentine as they infiltrate the castle in disguise to retrieve a stolen scarab.",
    curatorNote: "Introduced the idyllic world of Lord Emsworth, Blandings Castle, and Beach the butler.",
    gutenbergId: "2042",
    openLibraryWorkId: "OL21897W",
    subjects: ["Wit & Satire", "Blandings Castle", "Lord Emsworth", "Stolen Scarab", "Country House Farce"]
  },
  {
    title: "Psmith in the City",
    author: "P.G. Wodehouse",
    authorBio: "English author and humorist whose peerless comic prose created the immortal gentleman Bertie Wooster and his genius valet Jeeves.",
    year: 1910,
    pages: 250,
    audience: "all",
    coverId: "8232463",
    description: "Flamboyant, monocled dandy Rupert Psmith and Mike Jackson work as clerks in the New Asiatic Bank in London, turning banking bureaucracy on its ear.",
    curatorNote: "A hilarious satire of London financial offices starring Wodehouse's smoothest hero.",
    gutenbergId: "4507",
    openLibraryWorkId: "OL21898W",
    subjects: ["Wit & Satire", "Psmith", "London Banking", "Financial Satire", "Monocle"]
  },
  {
    title: "Psmith, Journalist",
    author: "P.G. Wodehouse",
    authorBio: "English author and humorist whose peerless comic prose created the immortal gentleman Bertie Wooster and his genius valet Jeeves.",
    year: 1915,
    pages: 270,
    audience: "all",
    coverId: "8232464",
    description: "Psmith takes over an innocuous New York family magazine called Cozy Moments, transforming it into a crusading muckraking paper battling corrupt tenement slumlords.",
    curatorNote: "A wonderful blend of American gangster adventure and quintessential English dandyism.",
    gutenbergId: "4753",
    openLibraryWorkId: "OL21899W",
    subjects: ["Wit & Satire", "Cozy Moments", "Muckraking", "New York Gangsters", "Psmith"]
  },
  {
    title: "Tartuffe",
    subtitle: "The Impostor",
    author: "Molière",
    authorBio: "French playwright and actor considered the supreme master of comedy in Western theater, using farce to unmask religious hypocrisy.",
    year: 1664,
    pages: 120,
    audience: "teen",
    coverId: "8232465",
    description: "Wealthy bourgeois Orgon falls completely under the spell of Tartuffe, a sanctimonious religious hypocrite who schemes to steal Orgon's fortune and wife.",
    curatorNote: "The supreme theatrical satire exposing the dangerous manipulation of religious piety.",
    gutenbergId: "2011",
    openLibraryWorkId: "OL21900W",
    subjects: ["Wit & Satire", "Molière", "Tartuffe", "Religious Hypocrisy", "French Farce"]
  },
  {
    title: "The Misanthrope",
    author: "Molière",
    authorBio: "French playwright and actor considered the supreme master of comedy in Western theater, using farce to unmask religious hypocrisy.",
    year: 1666,
    pages: 110,
    audience: "adult",
    coverId: "8232466",
    description: "Alceste despises the flattery and polite hypocrisies of French high society, yet is helplessly in love with Célimène, a flirtatious Parisian coquette.",
    curatorNote: "Molière's most sophisticated and poignant comedy of character and social compromise.",
    gutenbergId: "2012",
    openLibraryWorkId: "OL21901W",
    subjects: ["Wit & Satire", "The Misanthrope", "Alceste", "Social Hypocrisy", "High Comedy"]
  },
  {
    title: "The Miser",
    subtitle: "L'Avare",
    author: "Molière",
    authorBio: "French playwright and actor considered the supreme master of comedy in Western theater, using farce to unmask religious hypocrisy.",
    year: 1668,
    pages: 120,
    audience: "all",
    coverId: "8232467",
    description: "The parsimonious Harpagon loves his strongbox of buried gold above all else, attempting to marry off his children to wealthy elders to save dowries.",
    curatorNote: "The archetype of obsessive greed and comic parental tyranny in world theater.",
    gutenbergId: "4070",
    openLibraryWorkId: "OL21902W",
    subjects: ["Wit & Satire", "Harpagon", "Miser", "Buried Gold", "Family Farce"]
  },
  {
    title: "The Bourgeois Gentleman",
    author: "Molière",
    authorBio: "French playwright and actor considered the supreme master of comedy in Western theater, using farce to unmask religious hypocrisy.",
    year: 1670,
    pages: 120,
    audience: "all",
    coverId: "8232468",
    description: "Foolish merchant Monsieur Jourdain hires fencing, philosophy, and music masters to become an aristocrat, delightfully learning he has been speaking prose his whole life.",
    curatorNote: "Contains the immortal comic revelation: 'Good heavens! For more than forty years I have been speaking prose without knowing it!'",
    gutenbergId: "2993",
    openLibraryWorkId: "OL21903W",
    subjects: ["Wit & Satire", "Bourgeois Gentleman", "Speaking Prose", "Social Climbing", "Molière"]
  },
  {
    title: "The Imaginary Invalid",
    author: "Molière",
    authorBio: "French playwright and actor considered the supreme master of comedy in Western theater, using farce to unmask religious hypocrisy.",
    year: 1673,
    pages: 120,
    audience: "all",
    coverId: "8232469",
    description: "Severe hypochondriac Argan schemes to marry his daughter to a doctor for free medical care, while his greedy second wife plots to inherit his fortune.",
    curatorNote: "Molière's final comic triumph mocking quack medical pomposity, performed on the day he died.",
    gutenbergId: "9070",
    openLibraryWorkId: "OL21904W",
    subjects: ["Wit & Satire", "Hypochondria", "Medical Quackery", "Argan", "Molière Farce"]
  },
  {
    title: "Dead Souls",
    author: "Nikolai Gogol",
    authorBio: "Russian dramatist and novelist whose surreal, satirical masterpieces captured the absurdity and bureaucratic corruption of imperial Russia.",
    year: 1842,
    pages: 430,
    audience: "adult",
    coverId: "8232470",
    description: "Pavel Chichikov travels through provincial Russia buying up 'dead souls'—deceased serfs still listed on government tax censuses—for a grand mortgage fraud scheme.",
    curatorNote: "A panoramic, satirical triumph of Russian provincial eccentricity, greed, and soul.",
    gutenbergId: "1081",
    openLibraryWorkId: "OL21905W",
    subjects: ["Wit & Satire", "Dead Souls", "Chichikov", "Russian Bureaucracy", "Gogol Masterpiece"]
  },
  {
    title: "The Government Inspector",
    author: "Nikolai Gogol",
    authorBio: "Russian dramatist and novelist whose surreal, satirical masterpieces captured the absurdity and bureaucratic corruption of imperial Russia.",
    year: 1836,
    pages: 130,
    audience: "teen",
    coverId: "8232471",
    description: "Corrupt provincial town officials mistake a penniless, traveling civil servant named Khlestakov for an undercover incognito Inspector General from Saint Petersburg.",
    curatorNote: "One of the greatest satirical comedies ever staged, exposing panic and bribery among corrupt bureaucrats.",
    gutenbergId: "3735",
    openLibraryWorkId: "OL21906W",
    subjects: ["Wit & Satire", "Government Inspector", "Khlestakov", "Bureaucratic Panic", "Gogol"]
  },
  {
    title: "The Overcoat and Other Stories",
    author: "Nikolai Gogol",
    authorBio: "Russian dramatist and novelist whose surreal, satirical masterpieces captured the absurdity and bureaucratic corruption of imperial Russia.",
    year: 1842,
    pages: 190,
    audience: "teen",
    coverId: "8232472",
    description: "Includes 'The Overcoat' featuring timid copyist Akaky Akakievich whose stolen winter coat spawns a ghost, and 'Diary of a Madman'.",
    curatorNote: "Dostoevsky famously remarked: 'We all came out from under Gogol's Overcoat.'",
    gutenbergId: "3623",
    openLibraryWorkId: "OL21907W",
    subjects: ["Wit & Satire", "The Overcoat", "Akaky Akakievich", "Saint Petersburg", "Russian Realism"]
  },
  {
    title: "The Nose",
    author: "Nikolai Gogol",
    authorBio: "Russian dramatist and novelist whose surreal, satirical masterpieces captured the absurdity and bureaucratic corruption of imperial Russia.",
    year: 1836,
    pages: 50,
    audience: "all",
    coverId: "8232473",
    description: "Collegiate Assessor Kovalyov awakens to discover that his nose has left his face, attained higher civil service rank than him, and is strolling about town in uniform.",
    curatorNote: "A brilliant, laugh-out-loud masterpiece of surreal bureaucratic satire.",
    gutenbergId: "65037",
    openLibraryWorkId: "OL21908W",
    subjects: ["Wit & Satire", "The Nose", "Surreal Satire", "Kovalyov", "Absurdist Classic"]
  },
  {
    title: "The Life and Opinions of Tristram Shandy",
    author: "Laurence Sterne",
    authorBio: "Anglo-Irish novelist and clergyman whose experimental, digressive narrative style anticipated modernism and postmodernism by two centuries.",
    year: 1759,
    pages: 600,
    audience: "adult",
    coverId: "8232474",
    description: "Tristram Shandy attempts to narrate his autobiography, getting sidetracked by Uncle Toby's bowling-green war games, Corporal Trim, and philosophical hobby-horses.",
    curatorNote: "The astonishing grandfather of experimental comedy, filled with black pages, blank pages, and digressions.",
    gutenbergId: "1079",
    openLibraryWorkId: "OL21909W",
    subjects: ["Wit & Satire", "Tristram Shandy", "Uncle Toby", "Experimental Novel", "Digressions"]
  },
  {
    title: "A Sentimental Journey",
    author: "Laurence Sterne",
    authorBio: "Anglo-Irish novelist and clergyman whose experimental, digressive narrative style anticipated modernism and postmodernism by two centuries.",
    year: 1768,
    pages: 160,
    audience: "teen",
    coverId: "8232475",
    description: "Reverend Yorick travels through France and Italy, satirizing pompous travel guidebooks by focusing on tiny emotional encounters, lost snuff-boxes, and kind gestures.",
    curatorNote: "A charming, tender, and witty celebration of empathy, sensibility, and human quirks.",
    gutenbergId: "1076",
    openLibraryWorkId: "OL21910W",
    subjects: ["Wit & Satire", "Sentimental Journey", "Yorick", "Travel Satire", "Sensibility"]
  },
  {
    title: "The Clouds",
    author: "Aristophanes",
    authorBio: "Ancient Greek comic playwright known as the 'Father of Comedy' whose biting political and philosophical satires defined Old Comedy in Athens.",
    year: -423,
    pages: 110,
    audience: "teen",
    coverId: "8232476",
    description: "In debt due to his horse-racing son, Strepsiades enrolls in Socrates' 'Thinkery' to learn how to argue deceitfully and defeat his creditors in court.",
    curatorNote: "The historic comedy parodying Socrates, philosophy schools, and sophistry in ancient Athens.",
    gutenbergId: "7701",
    openLibraryWorkId: "OL21911W",
    subjects: ["Wit & Satire", "Aristophanes", "Socrates Satire", "The Clouds", "Old Comedy"]
  },
  {
    title: "The Birds",
    author: "Aristophanes",
    authorBio: "Ancient Greek comic playwright known as the 'Father of Comedy' whose biting political and philosophical satires defined Old Comedy in Athens.",
    year: -414,
    pages: 120,
    audience: "all",
    coverId: "8232477",
    description: "Two Athenians convince the birds of the air to build a utopian avian fortress city in the clouds—Cloud Cuckoo Land—to intercept sacrifices to the gods.",
    curatorNote: "The origin of the phrase 'Cloud Cuckoo Land': a soaring, lyrical, and hilarious political fantasy.",
    gutenbergId: "3013",
    openLibraryWorkId: "OL21912W",
    subjects: ["Wit & Satire", "Cloud Cuckoo Land", "Aristophanes", "Avian Utopia", "Athenian Satire"]
  },
  {
    title: "The Frogs",
    author: "Aristophanes",
    authorBio: "Ancient Greek comic playwright known as the 'Father of Comedy' whose biting political and philosophical satires defined Old Comedy in Athens.",
    year: -405,
    pages: 120,
    audience: "teen",
    coverId: "8232478",
    description: "Dionysus descends to Hades to bring back a great tragic poet, staging a verse-weighing contest between Aeschylus and Euripides to save Athens.",
    curatorNote: "Features the famous croaking frog chorus 'Brekekekèx-koàx-koákx' and dramatic literary criticism.",
    gutenbergId: "7998",
    openLibraryWorkId: "OL21913W",
    subjects: ["Wit & Satire", "Dionysus in Hades", "Aeschylus vs Euripides", "The Frogs", "Literary Parody"]
  },
  {
    title: "Lysistrata",
    author: "Aristophanes",
    authorBio: "Ancient Greek comic playwright known as the 'Father of Comedy' whose biting political and philosophical satires defined Old Comedy in Athens.",
    year: -411,
    pages: 100,
    audience: "adult",
    coverId: "8232479",
    description: "Athenian woman Lysistrata organizes women from all Greek city-states to withhold marital intimacy until the men agree to sign a treaty ending the Peloponnesian War.",
    curatorNote: "The legendary anti-war comedy demonstrating the power of united civil resistance.",
    gutenbergId: "7700",
    openLibraryWorkId: "OL21914W",
    subjects: ["Wit & Satire", "Lysistrata", "Anti-War Comedy", "Greek Theatre", "Peace Strike"]
  },
  {
    title: "The Praise of Folly",
    author: "Desiderius Erasmus",
    authorBio: "Dutch Renaissance humanist, Catholic priest, and theologian whose satirical masterpiece lampooned corruption across European society and church.",
    year: 1511,
    pages: 150,
    audience: "adult",
    coverId: "8232480",
    description: "Dame Folly personified delivers an ironic oration in praise of herself, demonstrating how human self-delusion, vanity, and folly keep society functioning.",
    curatorNote: "One of the most catalytic satires of the European Renaissance that catalyzed the Reformation.",
    gutenbergId: "9371",
    openLibraryWorkId: "OL21915W",
    subjects: ["Wit & Satire", "Erasmus", "Dame Folly", "Renaissance Humanism", "Religious Satire"]
  },
  {
    title: "Literary Lapses",
    author: "Stephen Leacock",
    authorBio: "Canadian economist and humorist whose sparkling wit made him the most internationally popular English-speaking comic writer of the early 20th century.",
    year: 1910,
    pages: 180,
    audience: "all",
    coverId: "8232481",
    description: "Thirty-nine hilarious comic sketches including the legendary 'My Financial Career', where opening a bank account becomes an escalating social panic.",
    curatorNote: "Contains 'My Financial Career', universally anthologized as a pinnacle of short comic timing.",
    gutenbergId: "4033",
    openLibraryWorkId: "OL21916W",
    subjects: ["Wit & Satire", "Stephen Leacock", "My Financial Career", "Canadian Humor", "Comic Sketches"]
  }
];
