module.exports = [
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1813,
    pages: 432,
    audience: "all",
    coverId: "12645114",
    description: "The spirited Elizabeth Bennet and aristocratic Fitzwilliam Darcy overcome pride, initial prejudice, and social snobbery in rural Regency England.",
    curatorNote: "The sharpest, most sparkling romantic satire of manners in the English language.",
    gutenbergId: "1342",
    openLibraryWorkId: "OL66554W",
    subjects: ["Romance & Society", "Regency Romance", "Comedy of Manners", "Elizabeth Bennet", "Mr Darcy"]
  },
  {
    title: "Sense and Sensibility",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1811,
    pages: 400,
    audience: "all",
    coverId: "9278292",
    description: "Sisters Elinor and Marianne Dashwood navigate social destitution, romantic heartbreak, and the tension between prudent judgment and emotional passion.",
    curatorNote: "Austen's dazzling debut contrasting moral restraint with romantic vulnerability.",
    gutenbergId: "161",
    openLibraryWorkId: "OL66555W",
    subjects: ["Romance & Society", "Dashwood Sisters", "Regency Romance", "Emotional Balance"]
  },
  {
    title: "Emma",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1815,
    pages: 474,
    audience: "all",
    coverId: "8232239",
    description: "Handsome, clever, and rich Emma Woodhouse delights in matchmaking for her village neighbors, blind to her own romantic blindness and Mr. Knightley's affection.",
    curatorNote: "A tour de force of narrative voice and delightful comic self-discovery.",
    gutenbergId: "158",
    openLibraryWorkId: "OL66556W",
    subjects: ["Romance & Society", "Matchmaking", "Emma Woodhouse", "Mr Knightley", "Highbury"]
  },
  {
    title: "Mansfield Park",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1814,
    pages: 460,
    audience: "teen",
    coverId: "8232240",
    description: "Gentle Fanny Price is raised by wealthy relatives at Mansfield Park, holding fast to moral integrity when seductive London interlopers disrupt the family estate.",
    curatorNote: "Austen's most complex and morally probing study of conscience and societal values.",
    gutenbergId: "141",
    openLibraryWorkId: "OL66557W",
    subjects: ["Romance & Society", "Fanny Price", "Mansfield Park", "Moral Integrity"]
  },
  {
    title: "Northanger Abbey",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1817,
    pages: 260,
    audience: "all",
    coverId: "8232241",
    description: "Gothic novel enthusiast Catherine Morland visits fashionable Bath and Northanger Abbey, learning to distinguish Gothic melodrama from real human virtue.",
    curatorNote: "A sparkling, witty parody of Gothic romances and delightful coming-of-age comedy.",
    gutenbergId: "121",
    openLibraryWorkId: "OL66558W",
    subjects: ["Romance & Society", "Gothic Parody", "Catherine Morland", "Henry Tilney", "Bath Society"]
  },
  {
    title: "Persuasion",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1817,
    pages: 300,
    audience: "all",
    coverId: "8232242",
    description: "Eight years after being persuaded to break her engagement to penniless naval officer Frederick Wentworth, Anne Elliot meets him again as a wealthy, eligible captain.",
    curatorNote: "Austen's most deeply poignant, mature, and romantic masterpiece of second chances.",
    gutenbergId: "105",
    openLibraryWorkId: "OL66559W",
    subjects: ["Romance & Society", "Second Chances", "Anne Elliot", "Captain Wentworth", "Regency Romance"]
  },
  {
    title: "Lady Susan",
    author: "Jane Austen",
    authorBio: "English novelist celebrated worldwide for her brilliant social satire, acute psychological observation, and sparkling romantic comedy of manners.",
    year: 1871,
    pages: 120,
    audience: "teen",
    coverId: "8232243",
    description: "An epistolary novella following the delightfully manipulative, beautiful, and unscrupulous widow Lady Susan Vernon as she hunts for wealthy matches.",
    curatorNote: "Features Austen's most deliciously wicked and brilliant anti-heroine.",
    gutenbergId: "946",
    openLibraryWorkId: "OL66560W",
    subjects: ["Romance & Society", "Epistolary Novella", "Anti-Heroine", "Witty Manipulation"]
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    authorBio: "English novelist whose passionate, independent protagonist and Gothic atmosphere transformed Victorian domestic literature.",
    year: 1847,
    pages: 507,
    audience: "teen",
    coverId: "8232244",
    description: "Orphaned governess Jane Eyre falls in love with the brooding Edward Rochester at Thornfield Hall, uncovering a dark secret concealed in the attic.",
    curatorNote: "An unforgettable story of moral integrity, fierce female independence, and Gothic romance.",
    gutenbergId: "1260",
    openLibraryWorkId: "OL1488111W",
    subjects: ["Romance & Society", "Gothic Romance", "Jane Eyre", "Rochester", "Female Autonomy"]
  },
  {
    title: "Villette",
    author: "Charlotte Brontë",
    authorBio: "English novelist whose passionate, independent protagonist and Gothic atmosphere transformed Victorian domestic literature.",
    year: 1853,
    pages: 590,
    audience: "adult",
    coverId: "8232245",
    description: "Lucy Snowe travels alone to the French-speaking city of Villette to teach at a boarding school, battling solitude, Catholic surveillance, and passionate love for Monsieur Paul Emanuel.",
    curatorNote: "George Eliot considered Villette superior even to Jane Eyre for its psychological brilliance.",
    gutenbergId: "993",
    openLibraryWorkId: "OL1488113W",
    subjects: ["Romance & Society", "Psychological Realism", "Lucy Snowe", "Belgian Boarding School"]
  },
  {
    title: "Shirley",
    author: "Charlotte Brontë",
    authorBio: "English novelist whose passionate, independent protagonist and Gothic atmosphere transformed Victorian domestic literature.",
    year: 1849,
    pages: 560,
    audience: "teen",
    coverId: "8232246",
    description: "Set during the Luddite machine-breaking riots in Yorkshire, exploring the friendship between timid Caroline Helstone and independent heiress Shirley Keeldar.",
    curatorNote: "Intertwines industrial unrest, economic independence, and passionate courtship.",
    gutenbergId: "3048",
    openLibraryWorkId: "OL1488114W",
    subjects: ["Romance & Society", "Industrial Unrest", "Yorkshire", "Female Friendship"]
  },
  {
    title: "The Professor",
    author: "Charlotte Brontë",
    authorBio: "English novelist whose passionate, independent protagonist and Gothic atmosphere transformed Victorian domestic literature.",
    year: 1857,
    pages: 310,
    audience: "teen",
    coverId: "8232247",
    description: "William Crimsworth seeks a career teaching English in Brussels, navigating romantic intrigue with the headmistress and falling in love with lace-worker Frances Henri.",
    curatorNote: "Charlotte Brontë's first written novel, drawn directly from her Belgian teaching experiences.",
    gutenbergId: "1028",
    openLibraryWorkId: "OL1488115W",
    subjects: ["Romance & Society", "Brussels", "Teaching Romance", "Victorian Work"]
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    authorBio: "English poet and novelist whose only novel remains one of the most turbulent, poetic, and fiercely passionate tragedies of world literature.",
    year: 1847,
    pages: 416,
    audience: "teen",
    coverId: "8232248",
    description: "The destructive, supernatural passion between Heathcliff and Catherine Earnshaw on the windswept Yorkshire moors wrecks vengeance across two generations.",
    curatorNote: "A raw, untamable force of passionate revenge and tragic devotion on the Yorkshire moors.",
    gutenbergId: "768",
    openLibraryWorkId: "OL1488112W",
    subjects: ["Romance & Society", "Yorkshire Moors", "Heathcliff", "Catherine Earnshaw", "Gothic Passion"]
  },
  {
    title: "The Tenant of Wildfell Hall",
    author: "Anne Brontë",
    authorBio: "English author whose courageous second novel broke Victorian taboos by portraying a woman fleeing an abusive, alcoholic marriage to protect her son.",
    year: 1848,
    pages: 490,
    audience: "adult",
    coverId: "8232249",
    description: "Mysterious widow Helen Graham rents secluded Wildfell Hall, hiding her real identity as an artist who fled an alcoholic husband to raise her child independently.",
    curatorNote: "One of the first and most fearless feminist novels in English literature.",
    gutenbergId: "969",
    openLibraryWorkId: "OL1488116W",
    subjects: ["Romance & Society", "Feminist Classic", "Helen Graham", "Marital Escape", "Wildfell Hall"]
  },
  {
    title: "Agnes Grey",
    author: "Anne Brontë",
    authorBio: "English author whose courageous second novel broke Victorian taboos by portraying a woman fleeing an abusive, alcoholic marriage to protect her son.",
    year: 1847,
    pages: 210,
    audience: "all",
    coverId: "8232250",
    description: "The humble daughter of an impoverished clergyman works as a governess for snobbish gentry families, maintaining quiet dignity and finding love with curate Weston.",
    curatorNote: "An honest, unadorned, and deeply moving portrayal of the Victorian governess's plight.",
    gutenbergId: "767",
    openLibraryWorkId: "OL1488117W",
    subjects: ["Romance & Society", "Governess Life", "Agnes Grey", "Quiet Dignity"]
  },
  {
    title: "Middlemarch",
    subtitle: "A Study of Provincial Life",
    author: "George Eliot",
    authorBio: "English novelist whose psychological insight, panoramic social breadth, and intellectual depth make her one of the supreme Victorian writers.",
    year: 1871,
    pages: 880,
    audience: "adult",
    coverId: "8232251",
    description: "Dorothea Brooke's idealistic marriage to pedantic scholar Casaubon, and Dr. Lydgate's scientific ambitions in a provincial English town during political reform.",
    curatorNote: "Virginia Woolf called it 'one of the few English novels written for grown-up people.'",
    gutenbergId: "145",
    openLibraryWorkId: "OL10670W",
    subjects: ["Romance & Society", "Dorothea Brooke", "Provincial Life", "George Eliot", "Masterpiece"]
  },
  {
    title: "Silas Marner",
    subtitle: "The Weaver of Raveloe",
    author: "George Eliot",
    authorBio: "English novelist whose psychological insight, panoramic social breadth, and intellectual depth make her one of the supreme Victorian writers.",
    year: 1861,
    pages: 230,
    audience: "all",
    coverId: "8232252",
    description: "A bitter, reclusive linen weaver loses his hoarded gold to a thief, only for an abandoned golden-haired child named Eppie to redeem his heart and community.",
    curatorNote: "A warm, deeply moral pastoral parable of redemption, parenthood, and grace.",
    gutenbergId: "550",
    openLibraryWorkId: "OL10671W",
    subjects: ["Romance & Society", "Silas Marner", "Eppie", "Redemption", "Pastoral"]
  },
  {
    title: "The Mill on the Floss",
    author: "George Eliot",
    authorBio: "English novelist whose psychological insight, panoramic social breadth, and intellectual depth make her one of the supreme Victorian writers.",
    year: 1860,
    pages: 580,
    audience: "teen",
    coverId: "8232253",
    description: "The turbulent relationship between passionate, intellectual Maggie Tulliver and her rigid brother Tom, set against the tragic family mill on the River Floss.",
    curatorNote: "A poignant, heart-wrenching study of sibling love, societal censure, and tragic sacrifice.",
    gutenbergId: "6688",
    openLibraryWorkId: "OL10672W",
    subjects: ["Romance & Society", "Maggie Tulliver", "River Floss", "Sibling Bond", "Victorian Tragedy"]
  },
  {
    title: "Adam Bede",
    author: "George Eliot",
    authorBio: "English novelist whose psychological insight, panoramic social breadth, and intellectual depth make her one of the supreme Victorian writers.",
    year: 1859,
    pages: 560,
    audience: "adult",
    coverId: "8232254",
    description: "Upright carpenter Adam Bede loves vain Hetty Sorrel, whose secret seduction by the young squire Arthur Donnithorne leads into pregnancy and moral downfall.",
    curatorNote: "Eliot's breakthrough novel featuring Methodist preacher Dinah Morris and rural community realism.",
    gutenbergId: "507",
    openLibraryWorkId: "OL10673W",
    subjects: ["Romance & Society", "Adam Bede", "Hetty Sorrel", "Moral Consequence", "Rural England"]
  },
  {
    title: "Daniel Deronda",
    author: "George Eliot",
    authorBio: "English novelist whose psychological insight, panoramic social breadth, and intellectual depth make her one of the supreme Victorian writers.",
    year: 1876,
    pages: 820,
    audience: "adult",
    coverId: "8232255",
    description: "Contrasts the mercenary marriage of spirited Gwendolen Harleth to abusive Henleigh Grandcourt with Daniel Deronda's search for his Jewish ancestry and destiny.",
    curatorNote: "Eliot's final, cosmopolitan masterpiece pioneering Jewish identity and proto-Zionist empathy.",
    gutenbergId: "7469",
    openLibraryWorkId: "OL10674W",
    subjects: ["Romance & Society", "Gwendolen Harleth", "Daniel Deronda", "Jewish Heritage"]
  },
  {
    title: "Tess of the d'Urbervilles",
    author: "Thomas Hardy",
    authorBio: "English novelist and poet whose Wessex novels explored rural tragic fate, the cruelty of Victorian social codes, and nature's indifference.",
    year: 1891,
    pages: 500,
    audience: "adult",
    coverId: "8232256",
    description: "Innocent country girl Tess Durbeyfield is seduced by Alec d'Urberville and subsequently rejected by idealistic husband Angel Clare under hypocritical Victorian morals.",
    curatorNote: "Hardy's heartbreaking tragedy defending a 'pure woman' against the double standards of society.",
    gutenbergId: "110",
    openLibraryWorkId: "OL21859W",
    subjects: ["Romance & Society", "Tess", "Wessex Tragedy", "Victorian Double Standards", "Angel Clare"]
  },
  {
    title: "Far from the Madding Crowd",
    author: "Thomas Hardy",
    authorBio: "English novelist and poet whose Wessex novels explored rural tragic fate, the cruelty of Victorian social codes, and nature's indifference.",
    year: 1874,
    pages: 450,
    audience: "all",
    coverId: "8232257",
    description: "Spirited Bathsheba Everdene inherits her uncle's farming estate and is courted by three suitors: devoted shepherd Gabriel Oak, farmer Boldwood, and Sergeant Troy.",
    curatorNote: "A glorious Wessex pastoral romance celebrating Gabriel Oak's enduring loyalty and patience.",
    gutenbergId: "107",
    openLibraryWorkId: "OL21860W",
    subjects: ["Romance & Society", "Bathsheba Everdene", "Gabriel Oak", "Wessex Pastoral", "Farming Life"]
  },
  {
    title: "Jude the Obscure",
    author: "Thomas Hardy",
    authorBio: "English novelist and poet whose Wessex novels explored rural tragic fate, the cruelty of Victorian social codes, and nature's indifference.",
    year: 1895,
    pages: 490,
    audience: "adult",
    coverId: "8232258",
    description: "Working-class stonemason Jude Fawley dreams of studying at Christminster university, finding tragic love with his unconventional cousin Sue Bridehead.",
    curatorNote: "Hardy's devastating final novel attacking class barriers and rigid Victorian marriage conventions.",
    gutenbergId: "153",
    openLibraryWorkId: "OL21861W",
    subjects: ["Romance & Society", "Jude Fawley", "Sue Bridehead", "Class Barriers", "Tragic Fate"]
  },
  {
    title: "The Mayor of Casterbridge",
    author: "Thomas Hardy",
    authorBio: "English novelist and poet whose Wessex novels explored rural tragic fate, the cruelty of Victorian social codes, and nature's indifference.",
    year: 1886,
    pages: 390,
    audience: "teen",
    coverId: "8232259",
    description: "Michael Henchard drunkenly sells his wife and baby daughter at a country fair, repents, and rises to mayor, only for his past to catch up with him.",
    curatorNote: "A Shakespearean tragedy of character: 'Character is Fate' in the heart of rural Wessex.",
    gutenbergId: "222",
    openLibraryWorkId: "OL21862W",
    subjects: ["Romance & Society", "Michael Henchard", "Casterbridge", "Character is Fate", "Wessex"]
  },
  {
    title: "The Return of the Native",
    author: "Thomas Hardy",
    authorBio: "English novelist and poet whose Wessex novels explored rural tragic fate, the cruelty of Victorian social codes, and nature's indifference.",
    year: 1878,
    pages: 440,
    audience: "adult",
    coverId: "8232260",
    description: "Clym Yeobright leaves Paris to open a school on brooding Egdon Heath, marrying passionate Eustacia Vye who dreams only of exotic city escape.",
    curatorNote: "Dominated by the sublime, primeval presence of Egdon Heath governing human destinies.",
    gutenbergId: "122",
    openLibraryWorkId: "OL21863W",
    subjects: ["Romance & Society", "Egdon Heath", "Eustacia Vye", "Wessex", "Passionate Tragedy"]
  },
  {
    title: "The Age of Innocence",
    author: "Edith Wharton",
    authorBio: "American novelist whose Pulitzer Prize-winning masterpieces dissected the gilded social hypocrisies of Old New York with razor precision.",
    year: 1920,
    pages: 360,
    audience: "adult",
    coverId: "8232261",
    description: "Newland Archer prepares for a conventional marriage to May Welland in 1870s New York, but is overwhelmed by love for her scandalous Europeanized cousin, Countess Olenska.",
    curatorNote: "The first novel by a woman to win the Pulitzer Prize: exquisite heartbreak and social duty.",
    gutenbergId: "541",
    openLibraryWorkId: "OL10675W",
    subjects: ["Romance & Society", "Old New York", "Countess Olenska", "Newland Archer", "Pulitzer Prize"]
  },
  {
    title: "The House of Mirth",
    author: "Edith Wharton",
    authorBio: "American novelist whose Pulitzer Prize-winning masterpieces dissected the gilded social hypocrisies of Old New York with razor precision.",
    year: 1905,
    pages: 390,
    audience: "adult",
    coverId: "8232262",
    description: "Beautiful and impoverished Lily Bart seeks a wealthy husband among New York's ruthless high society, but moral reservations and rumors precipitate her downward spiral.",
    curatorNote: "A devastating tragedy exposing the commodification of women in Gilded Age capitalism.",
    gutenbergId: "284",
    openLibraryWorkId: "OL10676W",
    subjects: ["Romance & Society", "Lily Bart", "Gilded Age", "High Society Tragedy", "New York"]
  },
  {
    title: "Ethan Frome",
    author: "Edith Wharton",
    authorBio: "American novelist whose Pulitzer Prize-winning masterpieces dissected the gilded social hypocrisies of Old New York with razor precision.",
    year: 1911,
    pages: 140,
    audience: "teen",
    coverId: "8232263",
    description: "In the bleak New England town of Starkfield, trapped farmer Ethan Frome falls in love with his hypochondriac wife's cousin Mattie Silver, resulting in a fateful sled ride.",
    curatorNote: "A chilling, austere masterpiece of silent longing and lifelong winter entrapment.",
    gutenbergId: "4517",
    openLibraryWorkId: "OL10677W",
    subjects: ["Romance & Society", "New England Tragedy", "Ethan Frome", "Starkfield", "Forbidden Love"]
  },
  {
    title: "The Custom of the Country",
    author: "Edith Wharton",
    authorBio: "American novelist whose Pulitzer Prize-winning masterpieces dissected the gilded social hypocrisies of Old New York with razor precision.",
    year: 1913,
    pages: 480,
    audience: "adult",
    coverId: "8232264",
    description: "Undine Spragg, an insatiably ambitious midwestern beauty, claws her way through marriages in New York and French aristocracy in relentless pursuit of luxury and status.",
    curatorNote: "Features Undine Spragg, one of the most brilliantly ruthless social climbers in literature.",
    gutenbergId: "287",
    openLibraryWorkId: "OL10678W",
    subjects: ["Romance & Society", "Undine Spragg", "Social Climbing", "American Ambition"]
  },
  {
    title: "Summer",
    author: "Edith Wharton",
    authorBio: "American novelist whose Pulitzer Prize-winning masterpieces dissected the gilded social hypocrisies of Old New York with razor precision.",
    year: 1917,
    pages: 200,
    audience: "adult",
    coverId: "8232265",
    description: "Charity Royall lives in isolated North Dormer, experiencing an intense summer sexual awakening with city architect Lucius Harney before harsh social reality sets in.",
    curatorNote: "Wharton's frank, passionate companion piece to Ethan Frome set in lush summer greenery.",
    gutenbergId: "283",
    openLibraryWorkId: "OL10679W",
    subjects: ["Romance & Society", "Summer Awakening", "Charity Royall", "Rural New England"]
  },
  {
    title: "The Portrait of a Lady",
    author: "Henry James",
    authorBio: "American-British author regarded as a key transitional figure between literary realism and modernism, known for complex psychological nuance.",
    year: 1881,
    pages: 640,
    audience: "adult",
    coverId: "8232266",
    description: "Spirited American heiress Isabel Archer travels to Europe to seek life and independence, falling victim to the sophisticated, manipulative Gilbert Osmond and Madame Merle.",
    curatorNote: "James' supreme masterpiece exploring freedom, innocence, and betrayal across European culture.",
    gutenbergId: "2833",
    openLibraryWorkId: "OL10680W",
    subjects: ["Romance & Society", "Isabel Archer", "Transatlantic Culture", "Gilbert Osmond", "Henry James"]
  },
  {
    title: "Washington Square",
    author: "Henry James",
    authorBio: "American-British author regarded as a key transitional figure between literary realism and modernism, known for complex psychological nuance.",
    year: 1880,
    pages: 220,
    audience: "teen",
    coverId: "8232267",
    description: "Plain, shy Catherine Sloper is courted by handsome fortune-hunter Morris Townsend, forcing a painful standoff with her bitterly tyrannical physician father.",
    curatorNote: "A compact, tragicomic gem adapted into the classic play and film The Heiress.",
    gutenbergId: "211",
    openLibraryWorkId: "OL10681W",
    subjects: ["Romance & Society", "Catherine Sloper", "Washington Square", "Fortune Hunter", "Old New York"]
  },
  {
    title: "Daisy Miller",
    author: "Henry James",
    authorBio: "American-British author regarded as a key transitional figure between literary realism and modernism, known for complex psychological nuance.",
    year: 1878,
    pages: 80,
    audience: "all",
    coverId: "8232268",
    description: "Innocent, vivacious American tourist Daisy Miller scandalizes the rigid expatriate society of Geneva and Rome by defying chaperone conventions.",
    curatorNote: "James' first major international success capturing the fresh charm of the 'American Girl'.",
    gutenbergId: "208",
    openLibraryWorkId: "OL10682W",
    subjects: ["Romance & Society", "Daisy Miller", "American Girl", "Roman Society", "Social Snobbery"]
  },
  {
    title: "The Bostonians",
    author: "Henry James",
    authorBio: "American-British author regarded as a key transitional figure between literary realism and modernism, known for complex psychological nuance.",
    year: 1886,
    pages: 460,
    audience: "adult",
    coverId: "8232269",
    description: "A bitter battle for the heart and mind of gifted young feminist orator Verena Tarrant between radical feminist Olive Chancellor and conservative lawyer Basil Ransom.",
    curatorNote: "A brilliant, witty satire on 19th-century American reform movements and Boston society.",
    gutenbergId: "471",
    openLibraryWorkId: "OL10683W",
    subjects: ["Romance & Society", "Boston Society", "Feminist Movement", "Verena Tarrant", "Satire"]
  },
  {
    title: "The Wings of the Dove",
    author: "Henry James",
    authorBio: "American-British author regarded as a key transitional figure between literary realism and modernism, known for complex psychological nuance.",
    year: 1902,
    pages: 530,
    audience: "adult",
    coverId: "8232270",
    description: "Impoverished London lovers Kate Croy and Merton Densher befriend dying American heiress Milly Theale in Venice, plotting an inheritance scheme with tragic consequences.",
    curatorNote: "The summit of James' late style: exquisite moral subtlety and heartbreaking psychological depth.",
    gutenbergId: "212",
    openLibraryWorkId: "OL10684W",
    subjects: ["Romance & Society", "Milly Theale", "Venetian Palace", "Late James", "Moral Tragedy"]
  },
  {
    title: "Little Women",
    author: "Louisa May Alcott",
    authorBio: "American author whose semi-autobiographical March family chronicles created one of the most enduring and beloved domestic classics in world literature.",
    year: 1868,
    pages: 540,
    audience: "all",
    coverId: "8232271",
    description: "The heartwarming struggles and sisterhood of Meg, Jo, Beth, and Amy March growing up in Civil War Massachusetts alongside next-door friend Laurie.",
    curatorNote: "The immortal classic of sisterhood, creative ambition, and warm domestic joy.",
    gutenbergId: "514",
    openLibraryWorkId: "OL10685W",
    subjects: ["Romance & Society", "March Sisters", "Jo March", "Family Classics", "Coming of Age"]
  },
  {
    title: "Good Wives",
    author: "Louisa May Alcott",
    authorBio: "American author whose semi-autobiographical March family chronicles created one of the most enduring and beloved domestic classics in world literature.",
    year: 1869,
    pages: 350,
    audience: "all",
    coverId: "8232272",
    description: "The March sisters enter adulthood: Meg begins marriage, Amy studies art in Europe, Jo pursues writing in New York and meets Professor Bhaer, and Beth's health wanes.",
    curatorNote: "The deeply satisfying second half of Little Women tracing marriages, grief, and adulthood.",
    gutenbergId: "65026",
    openLibraryWorkId: "OL10686W",
    subjects: ["Romance & Society", "Good Wives", "Jo March", "Professor Bhaer", "Sisterhood"]
  },
  {
    title: "Little Men",
    author: "Louisa May Alcott",
    authorBio: "American author whose semi-autobiographical March family chronicles created one of the most enduring and beloved domestic classics in world literature.",
    year: 1871,
    pages: 370,
    audience: "all",
    coverId: "8232273",
    description: "Jo and Professor Bhaer run Plumfield, an experimental boarding school where orphaned and energetic boys learn through nature, kindness, and practical tasks.",
    curatorNote: "A joyous, progressive vision of compassionate holistic education and boyhood development.",
    gutenbergId: "2788",
    openLibraryWorkId: "OL10687W",
    subjects: ["Romance & Society", "Plumfield School", "Jo March", "Boyhood Adventures", "Education"]
  },
  {
    title: "Jo's Boys",
    author: "Louisa May Alcott",
    authorBio: "American author whose semi-autobiographical March family chronicles created one of the most enduring and beloved domestic classics in world literature.",
    year: 1886,
    pages: 340,
    audience: "all",
    coverId: "8232274",
    description: "Ten years later, the Plumfield boys return as college students, seamen, and artists, navigating careers, love, and world challenges under Aunt Jo's guidance.",
    curatorNote: "The affectionate final chapter concluding Louisa May Alcott's March family chronicles.",
    gutenbergId: "3796",
    openLibraryWorkId: "OL10688W",
    subjects: ["Romance & Society", "March Chronicles", "Jo's Boys", "College Life", "Adulthood"]
  },
  {
    title: "An Old-Fashioned Girl",
    author: "Louisa May Alcott",
    authorBio: "American author whose semi-autobiographical March family chronicles created one of the most enduring and beloved domestic classics in world literature.",
    year: 1870,
    pages: 370,
    audience: "all",
    coverId: "8232275",
    description: "Sensible country girl Polly Milton visits her wealthy Boston friend Fanny Shaw, winning friends with unpretentious charm and later supporting herself as a music teacher.",
    curatorNote: "A delightful, warm critique of frivolous high-society fashion and praise of self-reliance.",
    gutenbergId: "2787",
    openLibraryWorkId: "OL10689W",
    subjects: ["Romance & Society", "Polly Milton", "Old-Fashioned Girl", "Self-Reliance", "Boston"]
  },
  {
    title: "North and South",
    author: "Elizabeth Gaskell",
    authorBio: "English novelist and biographer whose social novels explored Victorian industrial class strife and compassionate reconciliation.",
    year: 1854,
    pages: 520,
    audience: "all",
    coverId: "8232276",
    description: "Southern gentry girl Margaret Hale moves to the northern industrial mill town of Milton, clashing with and falling in love with cotton-mill owner John Thornton.",
    curatorNote: "Often called the Victorian industrial Pride and Prejudice: passionate, socially rich, and intelligent.",
    gutenbergId: "4276",
    openLibraryWorkId: "OL10690W",
    subjects: ["Romance & Society", "Margaret Hale", "John Thornton", "Industrial North", "Class Strife"]
  },
  {
    title: "Cranford",
    author: "Elizabeth Gaskell",
    authorBio: "English novelist and biographer whose social novels explored Victorian industrial class strife and compassionate reconciliation.",
    year: 1853,
    pages: 210,
    audience: "all",
    coverId: "8232277",
    description: "A tender, affectionate, and gently humorous portrait of a small English country village ruled by genteel spinsters and widows adhering to 'elegant economy'.",
    curatorNote: "Gaskell's most beloved and humorous gem of communal kindness and quiet eccentricity.",
    gutenbergId: "394",
    openLibraryWorkId: "OL10691W",
    subjects: ["Romance & Society", "Cranford", "Village Life", "Genteel Spinsters", "Humorous Realism"]
  },
  {
    title: "Wives and Daughters",
    author: "Elizabeth Gaskell",
    authorBio: "English novelist and biographer whose social novels explored Victorian industrial class strife and compassionate reconciliation.",
    year: 1866,
    pages: 680,
    audience: "all",
    coverId: "8232278",
    description: "The coming-of-age of sweet Molly Gibson after her widowed doctor father remarries, navigating her dazzling stepsister Cynthia Kirkpatrick and naturalist Roger Hamley.",
    curatorNote: "Gaskell's masterpiece: warm, subtle, emotionally profound domestic realism.",
    gutenbergId: "4274",
    openLibraryWorkId: "OL10692W",
    subjects: ["Romance & Society", "Molly Gibson", "Roger Hamley", "Domestic Realism", "Gaskell Masterpiece"]
  },
  {
    title: "Mary Barton",
    author: "Elizabeth Gaskell",
    authorBio: "English novelist and biographer whose social novels explored Victorian industrial class strife and compassionate reconciliation.",
    year: 1848,
    pages: 460,
    audience: "teen",
    coverId: "8232279",
    description: "In 1840s Manchester, mill-worker's daughter Mary Barton is caught between wealthy mill-owner's son Henry Carson and working-class suitor Jem Wilson amid trade-union murder.",
    curatorNote: "A powerful, groundbreaking social novel highlighting the plight of Manchester factory workers.",
    gutenbergId: "2153",
    openLibraryWorkId: "OL10693W",
    subjects: ["Romance & Society", "Manchester Mills", "Trade Union", "Mary Barton", "Working Class"]
  },
  {
    title: "The Warden",
    author: "Anthony Trollope",
    authorBio: "Prolific Victorian novelist whose Chronicles of Barsetshire and Palliser novels provided peerless social portraits of clergy and politics.",
    year: 1855,
    pages: 240,
    audience: "teen",
    coverId: "8232280",
    description: "Gentle warden Septimus Harding finds himself caught in an aggressive public scandal regarding church charity revenues championed by his future son-in-law.",
    curatorNote: "The brilliant opening novel of Trollope's Barsetshire series, examining conscience and media frenzy.",
    gutenbergId: "619",
    openLibraryWorkId: "OL10694W",
    subjects: ["Romance & Society", "Barsetshire", "Septimus Harding", "Church Politics", "Victorian Satire"]
  },
  {
    title: "Barchester Towers",
    author: "Anthony Trollope",
    authorBio: "Prolific Victorian novelist whose Chronicles of Barsetshire and Palliser novels provided peerless social portraits of clergy and politics.",
    year: 1857,
    pages: 530,
    audience: "teen",
    coverId: "8232281",
    description: "A battle for control of Barchester diocese erupts between proud Archdeacon Grantly and the bishop's tyrannical wife Mrs. Proudie, alongside the wily chaplain Mr. Slope.",
    curatorNote: "Trollope's comic triumph featuring the immortal domestic tyrant Mrs. Proudie.",
    gutenbergId: "3409",
    openLibraryWorkId: "OL10695W",
    subjects: ["Romance & Society", "Mrs Proudie", "Barchester", "Comic Masterpiece", "Clerical Satire"]
  },
  {
    title: "Doctor Thorne",
    author: "Anthony Trollope",
    authorBio: "Prolific Victorian novelist whose Chronicles of Barsetshire and Palliser novels provided peerless social portraits of clergy and politics.",
    year: 1858,
    pages: 560,
    audience: "all",
    coverId: "8232282",
    description: "Young Frank Gresham is pressured to 'marry money' to save Greshambury estate, but loves Mary Thorne, unaware that her illegitimate birth conceals a massive fortune.",
    curatorNote: "Trollope's most enduringly popular romantic novel of true love overcoming aristocratic greed.",
    gutenbergId: "3166",
    openLibraryWorkId: "OL10696W",
    subjects: ["Romance & Society", "Doctor Thorne", "Mary Thorne", "Barsetshire Romance", "Inheritance"]
  },
  {
    title: "A Room with a View",
    author: "E.M. Forster",
    authorBio: "English novelist whose humanist romances criticized Edwardian social convention, hypocrisy, and emotional repression.",
    year: 1908,
    pages: 250,
    audience: "all",
    coverId: "8232283",
    description: "Young Lucy Honeychurch visits Florence and falls in love with the passionate, unconventional George Emerson, choosing genuine feeling over conventional engagement.",
    curatorNote: "A sparkling, joyful celebration of romantic liberation beneath the Tuscan sun.",
    gutenbergId: "264",
    openLibraryWorkId: "OL10697W",
    subjects: ["Romance & Society", "Florence", "Lucy Honeychurch", "George Emerson", "Edwardian Romance"]
  },
  {
    title: "Howards End",
    author: "E.M. Forster",
    authorBio: "English novelist whose humanist romances criticized Edwardian social convention, hypocrisy, and emotional repression.",
    year: 1910,
    pages: 350,
    audience: "adult",
    coverId: "8232284",
    description: "The intellectual Schlegel sisters intersect with the capitalist Wilcox family and impoverished clerk Leonard Bast around the rural Hertfordshire house of Howards End.",
    curatorNote: "Famous for its defining motto: 'Only connect the prose and the passion.'",
    gutenbergId: "2891",
    openLibraryWorkId: "OL10698W",
    subjects: ["Romance & Society", "Howards End", "Schlegel Sisters", "Only Connect", "Edwardian Society"]
  },
  {
    title: "Where Angels Fear to Tread",
    author: "E.M. Forster",
    authorBio: "English novelist whose humanist romances criticized Edwardian social convention, hypocrisy, and emotional repression.",
    year: 1905,
    pages: 210,
    audience: "teen",
    coverId: "8232285",
    description: "Widow Lilia Herriton travels to Tuscany and impulsively marries a penniless Italian dentist's son, shocking her stuffy English in-laws who travel to rescue the family honor.",
    curatorNote: "Forster's witty and poignant debut exploring the clash between English propriety and Italian passion.",
    gutenbergId: "2946",
    openLibraryWorkId: "OL10699W",
    subjects: ["Romance & Society", "Anglo-Italian Clash", "Tuscany", "Edwardian Satire", "Forster Debut"]
  },
  {
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    authorBio: "Russian literary titan whose epic realism captured the entire breadth of human emotion, society, and existential searching.",
    year: 1877,
    pages: 864,
    audience: "adult",
    coverId: "8232286",
    description: "Aristocrat Anna Karenina abandons her loveless marriage for Count Vronsky, counterpointed by Konstantin Levin's spiritual search and joyful rural family life.",
    curatorNote: "Universally acclaimed by writers from Faulkner to Nabokov as the greatest novel ever written.",
    gutenbergId: "1399",
    openLibraryWorkId: "OL10700W",
    subjects: ["Romance & Society", "Anna Karenina", "Count Vronsky", "Levin", "Russian Masterpiece"]
  }
];
